//! Compiler option inheritance uses Go field zero values and exact JSON tags.
use crate::ConfigValue;
use ts_core::CompilerOptions;

/// port: tsc/internal/tsoptions/parsinghelpers.go:mergeCompilerOptions
pub fn merge_compiler_options(
    target: &mut CompilerOptions,
    source: &CompilerOptions,
    raw: &ConfigValue,
) {
    let explicit_null = raw.get(b"compilerOptions");
    macro_rules! merge { ($($field:ident => $key:literal),* $(,)?) => { $(
        if explicit_null.and_then(|options| options.get($key)).is_some_and(ConfigValue::is_null) {
            target.$field = Default::default();
        } else if source.$field != Default::default() {
            target.$field.clone_from(&source.$field);
        }
    )* }; }
    merge! {
        allow_js => b"allowJs",
        allow_arbitrary_extensions => b"allowArbitraryExtensions",
        allow_importing_ts_extensions => b"allowImportingTsExtensions",
        allow_non_ts_extensions => b"allowNonTsExtensions",
        allow_umd_global_access => b"allowUmdGlobalAccess",
        allow_unreachable_code => b"allowUnreachableCode",
        allow_unused_labels => b"allowUnusedLabels",
        assume_changes_only_affect_direct_dependencies => b"assumeChangesOnlyAffectDirectDependencies",
        check_js => b"checkJs",
        custom_conditions => b"customConditions",
        composite => b"composite",
        emit_declaration_only => b"emitDeclarationOnly",
        emit_bom => b"emitBOM",
        emit_decorator_metadata => b"emitDecoratorMetadata",
        declaration => b"declaration",
        declaration_dir => b"declarationDir",
        declaration_map => b"declarationMap",
        deduplicate_packages => b"deduplicatePackages",
        disable_size_limit => b"disableSizeLimit",
        disable_source_of_project_reference_redirect => b"disableSourceOfProjectReferenceRedirect",
        disable_solution_searching => b"disableSolutionSearching",
        disable_referenced_project_load => b"disableReferencedProjectLoad",
        erasable_syntax_only => b"erasableSyntaxOnly",
        exact_optional_property_types => b"exactOptionalPropertyTypes",
        experimental_decorators => b"experimentalDecorators",
        force_consistent_casing_in_file_names => b"forceConsistentCasingInFileNames",
        isolated_modules => b"isolatedModules",
        isolated_declarations => b"isolatedDeclarations",
        ignore_config => b"ignoreConfig",
        ignore_deprecations => b"ignoreDeprecations",
        import_helpers => b"importHelpers",
        inline_source_map => b"inlineSourceMap",
        inline_sources => b"inlineSources",
        init => b"init",
        incremental => b"incremental",
        jsx => b"jsx",
        jsx_factory => b"jsxFactory",
        jsx_fragment_factory => b"jsxFragmentFactory",
        jsx_import_source => b"jsxImportSource",
        lib => b"lib",
        lib_replacement => b"libReplacement",
        locale => b"locale",
        map_root => b"mapRoot",
        module => b"module",
        module_resolution => b"moduleResolution",
        module_suffixes => b"moduleSuffixes",
        module_detection => b"moduleDetection",
        new_line => b"newLine",
        no_emit => b"noEmit",
        no_check => b"noCheck",
        no_error_truncation => b"noErrorTruncation",
        no_fallthrough_cases_in_switch => b"noFallthroughCasesInSwitch",
        no_implicit_any => b"noImplicitAny",
        no_implicit_this => b"noImplicitThis",
        no_implicit_returns => b"noImplicitReturns",
        no_emit_helpers => b"noEmitHelpers",
        no_lib => b"noLib",
        no_property_access_from_index_signature => b"noPropertyAccessFromIndexSignature",
        no_unchecked_indexed_access => b"noUncheckedIndexedAccess",
        no_emit_on_error => b"noEmitOnError",
        no_unused_locals => b"noUnusedLocals",
        no_unused_parameters => b"noUnusedParameters",
        no_resolve => b"noResolve",
        no_implicit_override => b"noImplicitOverride",
        no_unchecked_side_effect_imports => b"noUncheckedSideEffectImports",
        out_dir => b"outDir",
        paths => b"paths",
        preserve_const_enums => b"preserveConstEnums",
        preserve_symlinks => b"preserveSymlinks",
        project => b"project",
        resolve_json_module => b"resolveJsonModule",
        resolve_package_json_exports => b"resolvePackageJsonExports",
        resolve_package_json_imports => b"resolvePackageJsonImports",
        remove_comments => b"removeComments",
        rewrite_relative_import_extensions => b"rewriteRelativeImportExtensions",
        react_namespace => b"reactNamespace",
        root_dir => b"rootDir",
        root_dirs => b"rootDirs",
        skip_lib_check => b"skipLibCheck",
        stable_type_ordering => b"stableTypeOrdering",
        strict => b"strict",
        strict_bind_call_apply => b"strictBindCallApply",
        strict_builtin_iterator_return => b"strictBuiltinIteratorReturn",
        strict_function_types => b"strictFunctionTypes",
        strict_null_checks => b"strictNullChecks",
        strict_property_initialization => b"strictPropertyInitialization",
        strip_internal => b"stripInternal",
        skip_default_lib_check => b"skipDefaultLibCheck",
        source_map => b"sourceMap",
        source_root => b"sourceRoot",
        suppress_output_path_check => b"suppressOutputPathCheck",
        target => b"target",
        trace_resolution => b"traceResolution",
        ts_build_info_file => b"tsBuildInfoFile",
        type_roots => b"typeRoots",
        types => b"types",
        use_define_for_class_fields => b"useDefineForClassFields",
        use_unknown_in_catch_variables => b"useUnknownInCatchVariables",
        verbatim_module_syntax => b"verbatimModuleSyntax",
        max_node_module_js_depth => b"maxNodeModuleJsDepth",
        allow_synthetic_default_imports => b"allowSyntheticDefaultImports",
        always_strict => b"alwaysStrict",
        base_url => b"baseUrl",
        downlevel_iteration => b"downlevelIteration",
        es_module_interop => b"esModuleInterop",
        out_file => b"outFile",
        config_file_path => b"configFilePath",
        no_dts_resolution => b"noDtsResolution",
        paths_base_path => b"pathsBasePath",
        diagnostics => b"diagnostics",
        extended_diagnostics => b"extendedDiagnostics",
        generate_cpu_profile => b"generateCpuProfile",
        generate_trace => b"generateTrace",
        list_emitted_files => b"listEmittedFiles",
        list_files => b"listFiles",
        explain_files => b"explainFiles",
        list_files_only => b"listFilesOnly",
        no_emit_for_js_files => b"noEmitForJsFiles",
        preserve_watch_output => b"preserveWatchOutput",
        pretty => b"pretty",
        version => b"version",
        watch => b"watch",
        show_config => b"showConfig",
        build => b"build",
        help => b"help",
        all => b"all",
        run_external_code => b"runExternalCode",
        pprof_dir => b"pprofDir",
        single_threaded => b"singleThreaded",
        quiet => b"quiet",
        checkers => b"checkers",
    }
}
