//! Byte-exact observable form of all public and internal CompilerOptions fields.
use crate::ConfigValue as V;
use ts_core::CompilerOptions;
use ts_jsstring::JsString;
pub fn compiler_options_value(options: &CompilerOptions) -> V {
    let mut values = Vec::new();
    macro_rules! field {
        ($field:ident,$key:literal,$value:expr) => {
            if options.$field != Default::default() {
                values.push((JsString::from_bytes($key.as_slice()), $value));
            }
        };
    }
    field!(allow_js, b"allowJs", V::Boolean(options.allow_js.is_true()));
    field!(
        allow_arbitrary_extensions,
        b"allowArbitraryExtensions",
        V::Boolean(options.allow_arbitrary_extensions.is_true())
    );
    field!(
        allow_importing_ts_extensions,
        b"allowImportingTsExtensions",
        V::Boolean(options.allow_importing_ts_extensions.is_true())
    );
    field!(
        allow_non_ts_extensions,
        b"allowNonTsExtensions",
        V::Boolean(options.allow_non_ts_extensions.is_true())
    );
    field!(
        allow_umd_global_access,
        b"allowUmdGlobalAccess",
        V::Boolean(options.allow_umd_global_access.is_true())
    );
    field!(
        allow_unreachable_code,
        b"allowUnreachableCode",
        V::Boolean(options.allow_unreachable_code.is_true())
    );
    field!(
        allow_unused_labels,
        b"allowUnusedLabels",
        V::Boolean(options.allow_unused_labels.is_true())
    );
    field!(
        assume_changes_only_affect_direct_dependencies,
        b"assumeChangesOnlyAffectDirectDependencies",
        V::Boolean(
            options
                .assume_changes_only_affect_direct_dependencies
                .is_true()
        )
    );
    field!(check_js, b"checkJs", V::Boolean(options.check_js.is_true()));
    field!(
        custom_conditions,
        b"customConditions",
        V::Array(
            options.custom_conditions.as_ref().map(|values| values
                .iter()
                .cloned()
                .map(V::String)
                .collect())
        )
    );
    field!(
        composite,
        b"composite",
        V::Boolean(options.composite.is_true())
    );
    field!(
        emit_declaration_only,
        b"emitDeclarationOnly",
        V::Boolean(options.emit_declaration_only.is_true())
    );
    field!(emit_bom, b"emitBOM", V::Boolean(options.emit_bom.is_true()));
    field!(
        emit_decorator_metadata,
        b"emitDecoratorMetadata",
        V::Boolean(options.emit_decorator_metadata.is_true())
    );
    field!(
        declaration,
        b"declaration",
        V::Boolean(options.declaration.is_true())
    );
    field!(
        declaration_dir,
        b"declarationDir",
        V::String(options.declaration_dir.clone())
    );
    field!(
        declaration_map,
        b"declarationMap",
        V::Boolean(options.declaration_map.is_true())
    );
    field!(
        deduplicate_packages,
        b"deduplicatePackages",
        V::Boolean(options.deduplicate_packages.is_true())
    );
    field!(
        disable_size_limit,
        b"disableSizeLimit",
        V::Boolean(options.disable_size_limit.is_true())
    );
    field!(
        disable_source_of_project_reference_redirect,
        b"disableSourceOfProjectReferenceRedirect",
        V::Boolean(
            options
                .disable_source_of_project_reference_redirect
                .is_true()
        )
    );
    field!(
        disable_solution_searching,
        b"disableSolutionSearching",
        V::Boolean(options.disable_solution_searching.is_true())
    );
    field!(
        disable_referenced_project_load,
        b"disableReferencedProjectLoad",
        V::Boolean(options.disable_referenced_project_load.is_true())
    );
    field!(
        erasable_syntax_only,
        b"erasableSyntaxOnly",
        V::Boolean(options.erasable_syntax_only.is_true())
    );
    field!(
        exact_optional_property_types,
        b"exactOptionalPropertyTypes",
        V::Boolean(options.exact_optional_property_types.is_true())
    );
    field!(
        experimental_decorators,
        b"experimentalDecorators",
        V::Boolean(options.experimental_decorators.is_true())
    );
    field!(
        force_consistent_casing_in_file_names,
        b"forceConsistentCasingInFileNames",
        V::Boolean(options.force_consistent_casing_in_file_names.is_true())
    );
    field!(
        isolated_modules,
        b"isolatedModules",
        V::Boolean(options.isolated_modules.is_true())
    );
    field!(
        isolated_declarations,
        b"isolatedDeclarations",
        V::Boolean(options.isolated_declarations.is_true())
    );
    field!(
        ignore_config,
        b"ignoreConfig",
        V::Boolean(options.ignore_config.is_true())
    );
    field!(
        ignore_deprecations,
        b"ignoreDeprecations",
        V::String(options.ignore_deprecations.clone())
    );
    field!(
        import_helpers,
        b"importHelpers",
        V::Boolean(options.import_helpers.is_true())
    );
    field!(
        inline_source_map,
        b"inlineSourceMap",
        V::Boolean(options.inline_source_map.is_true())
    );
    field!(
        inline_sources,
        b"inlineSources",
        V::Boolean(options.inline_sources.is_true())
    );
    field!(init, b"init", V::Boolean(options.init.is_true()));
    field!(
        incremental,
        b"incremental",
        V::Boolean(options.incremental.is_true())
    );
    field!(jsx, b"jsx", V::Integer(i64::from(options.jsx.0)));
    field!(
        jsx_factory,
        b"jsxFactory",
        V::String(options.jsx_factory.clone())
    );
    field!(
        jsx_fragment_factory,
        b"jsxFragmentFactory",
        V::String(options.jsx_fragment_factory.clone())
    );
    field!(
        jsx_import_source,
        b"jsxImportSource",
        V::String(options.jsx_import_source.clone())
    );
    field!(
        lib,
        b"lib",
        V::Array(
            options
                .lib
                .as_ref()
                .map(|values| values.iter().cloned().map(V::String).collect())
        )
    );
    field!(
        lib_replacement,
        b"libReplacement",
        V::Boolean(options.lib_replacement.is_true())
    );
    field!(locale, b"locale", V::String(options.locale.clone()));
    field!(map_root, b"mapRoot", V::String(options.map_root.clone()));
    field!(module, b"module", V::Integer(i64::from(options.module.0)));
    field!(
        module_resolution,
        b"moduleResolution",
        V::Integer(i64::from(options.module_resolution.0))
    );
    field!(
        module_suffixes,
        b"moduleSuffixes",
        V::Array(
            options.module_suffixes.as_ref().map(|values| values
                .iter()
                .cloned()
                .map(V::String)
                .collect())
        )
    );
    field!(
        module_detection,
        b"moduleDetection",
        V::Integer(i64::from(options.module_detection.0))
    );
    field!(
        new_line,
        b"newLine",
        V::Integer(i64::from(options.new_line.0))
    );
    field!(no_emit, b"noEmit", V::Boolean(options.no_emit.is_true()));
    field!(no_check, b"noCheck", V::Boolean(options.no_check.is_true()));
    field!(
        no_error_truncation,
        b"noErrorTruncation",
        V::Boolean(options.no_error_truncation.is_true())
    );
    field!(
        no_fallthrough_cases_in_switch,
        b"noFallthroughCasesInSwitch",
        V::Boolean(options.no_fallthrough_cases_in_switch.is_true())
    );
    field!(
        no_implicit_any,
        b"noImplicitAny",
        V::Boolean(options.no_implicit_any.is_true())
    );
    field!(
        no_implicit_this,
        b"noImplicitThis",
        V::Boolean(options.no_implicit_this.is_true())
    );
    field!(
        no_implicit_returns,
        b"noImplicitReturns",
        V::Boolean(options.no_implicit_returns.is_true())
    );
    field!(
        no_emit_helpers,
        b"noEmitHelpers",
        V::Boolean(options.no_emit_helpers.is_true())
    );
    field!(no_lib, b"noLib", V::Boolean(options.no_lib.is_true()));
    field!(
        no_property_access_from_index_signature,
        b"noPropertyAccessFromIndexSignature",
        V::Boolean(options.no_property_access_from_index_signature.is_true())
    );
    field!(
        no_unchecked_indexed_access,
        b"noUncheckedIndexedAccess",
        V::Boolean(options.no_unchecked_indexed_access.is_true())
    );
    field!(
        no_emit_on_error,
        b"noEmitOnError",
        V::Boolean(options.no_emit_on_error.is_true())
    );
    field!(
        no_unused_locals,
        b"noUnusedLocals",
        V::Boolean(options.no_unused_locals.is_true())
    );
    field!(
        no_unused_parameters,
        b"noUnusedParameters",
        V::Boolean(options.no_unused_parameters.is_true())
    );
    field!(
        no_resolve,
        b"noResolve",
        V::Boolean(options.no_resolve.is_true())
    );
    field!(
        no_implicit_override,
        b"noImplicitOverride",
        V::Boolean(options.no_implicit_override.is_true())
    );
    field!(
        no_unchecked_side_effect_imports,
        b"noUncheckedSideEffectImports",
        V::Boolean(options.no_unchecked_side_effect_imports.is_true())
    );
    field!(out_dir, b"outDir", V::String(options.out_dir.clone()));
    field!(
        paths,
        b"paths",
        V::Object(
            options
                .paths
                .as_ref()
                .expect("present paths")
                .iter()
                .map(|(key, values)| (
                    key.clone(),
                    V::Array(
                        values.as_ref().map(|values| values
                            .iter()
                            .cloned()
                            .map(V::String)
                            .collect())
                    )
                ))
                .collect()
        )
    );
    field!(
        preserve_const_enums,
        b"preserveConstEnums",
        V::Boolean(options.preserve_const_enums.is_true())
    );
    field!(
        preserve_symlinks,
        b"preserveSymlinks",
        V::Boolean(options.preserve_symlinks.is_true())
    );
    field!(project, b"project", V::String(options.project.clone()));
    field!(
        resolve_json_module,
        b"resolveJsonModule",
        V::Boolean(options.resolve_json_module.is_true())
    );
    field!(
        resolve_package_json_exports,
        b"resolvePackageJsonExports",
        V::Boolean(options.resolve_package_json_exports.is_true())
    );
    field!(
        resolve_package_json_imports,
        b"resolvePackageJsonImports",
        V::Boolean(options.resolve_package_json_imports.is_true())
    );
    field!(
        remove_comments,
        b"removeComments",
        V::Boolean(options.remove_comments.is_true())
    );
    field!(
        rewrite_relative_import_extensions,
        b"rewriteRelativeImportExtensions",
        V::Boolean(options.rewrite_relative_import_extensions.is_true())
    );
    field!(
        react_namespace,
        b"reactNamespace",
        V::String(options.react_namespace.clone())
    );
    field!(root_dir, b"rootDir", V::String(options.root_dir.clone()));
    field!(
        root_dirs,
        b"rootDirs",
        V::Array(
            options.root_dirs.as_ref().map(|values| values
                .iter()
                .cloned()
                .map(V::String)
                .collect())
        )
    );
    field!(
        skip_lib_check,
        b"skipLibCheck",
        V::Boolean(options.skip_lib_check.is_true())
    );
    field!(
        stable_type_ordering,
        b"stableTypeOrdering",
        V::Boolean(options.stable_type_ordering.is_true())
    );
    field!(strict, b"strict", V::Boolean(options.strict.is_true()));
    field!(
        strict_bind_call_apply,
        b"strictBindCallApply",
        V::Boolean(options.strict_bind_call_apply.is_true())
    );
    field!(
        strict_builtin_iterator_return,
        b"strictBuiltinIteratorReturn",
        V::Boolean(options.strict_builtin_iterator_return.is_true())
    );
    field!(
        strict_function_types,
        b"strictFunctionTypes",
        V::Boolean(options.strict_function_types.is_true())
    );
    field!(
        strict_null_checks,
        b"strictNullChecks",
        V::Boolean(options.strict_null_checks.is_true())
    );
    field!(
        strict_property_initialization,
        b"strictPropertyInitialization",
        V::Boolean(options.strict_property_initialization.is_true())
    );
    field!(
        strip_internal,
        b"stripInternal",
        V::Boolean(options.strip_internal.is_true())
    );
    field!(
        skip_default_lib_check,
        b"skipDefaultLibCheck",
        V::Boolean(options.skip_default_lib_check.is_true())
    );
    field!(
        source_map,
        b"sourceMap",
        V::Boolean(options.source_map.is_true())
    );
    field!(
        source_root,
        b"sourceRoot",
        V::String(options.source_root.clone())
    );
    field!(
        suppress_output_path_check,
        b"suppressOutputPathCheck",
        V::Boolean(options.suppress_output_path_check.is_true())
    );
    field!(target, b"target", V::Integer(i64::from(options.target.0)));
    field!(
        trace_resolution,
        b"traceResolution",
        V::Boolean(options.trace_resolution.is_true())
    );
    field!(
        ts_build_info_file,
        b"tsBuildInfoFile",
        V::String(options.ts_build_info_file.clone())
    );
    field!(
        type_roots,
        b"typeRoots",
        V::Array(
            options.type_roots.as_ref().map(|values| values
                .iter()
                .cloned()
                .map(V::String)
                .collect())
        )
    );
    field!(
        types,
        b"types",
        V::Array(
            options
                .types
                .as_ref()
                .map(|values| values.iter().cloned().map(V::String).collect())
        )
    );
    field!(
        use_define_for_class_fields,
        b"useDefineForClassFields",
        V::Boolean(options.use_define_for_class_fields.is_true())
    );
    field!(
        use_unknown_in_catch_variables,
        b"useUnknownInCatchVariables",
        V::Boolean(options.use_unknown_in_catch_variables.is_true())
    );
    field!(
        verbatim_module_syntax,
        b"verbatimModuleSyntax",
        V::Boolean(options.verbatim_module_syntax.is_true())
    );
    field!(
        max_node_module_js_depth,
        b"maxNodeModuleJsDepth",
        V::Integer(options.max_node_module_js_depth.expect("present number") as i64)
    );
    field!(
        allow_synthetic_default_imports,
        b"allowSyntheticDefaultImports",
        V::Boolean(options.allow_synthetic_default_imports.is_true())
    );
    field!(
        always_strict,
        b"alwaysStrict",
        V::Boolean(options.always_strict.is_true())
    );
    field!(base_url, b"baseUrl", V::String(options.base_url.clone()));
    field!(
        downlevel_iteration,
        b"downlevelIteration",
        V::Boolean(options.downlevel_iteration.is_true())
    );
    field!(
        es_module_interop,
        b"esModuleInterop",
        V::Boolean(options.es_module_interop.is_true())
    );
    field!(out_file, b"outFile", V::String(options.out_file.clone()));
    field!(
        config_file_path,
        b"configFilePath",
        V::String(options.config_file_path.clone())
    );
    field!(
        no_dts_resolution,
        b"noDtsResolution",
        V::Boolean(options.no_dts_resolution.is_true())
    );
    field!(
        paths_base_path,
        b"pathsBasePath",
        V::String(options.paths_base_path.clone())
    );
    field!(
        diagnostics,
        b"diagnostics",
        V::Boolean(options.diagnostics.is_true())
    );
    field!(
        extended_diagnostics,
        b"extendedDiagnostics",
        V::Boolean(options.extended_diagnostics.is_true())
    );
    field!(
        generate_cpu_profile,
        b"generateCpuProfile",
        V::String(options.generate_cpu_profile.clone())
    );
    field!(
        generate_trace,
        b"generateTrace",
        V::String(options.generate_trace.clone())
    );
    field!(
        list_emitted_files,
        b"listEmittedFiles",
        V::Boolean(options.list_emitted_files.is_true())
    );
    field!(
        list_files,
        b"listFiles",
        V::Boolean(options.list_files.is_true())
    );
    field!(
        explain_files,
        b"explainFiles",
        V::Boolean(options.explain_files.is_true())
    );
    field!(
        list_files_only,
        b"listFilesOnly",
        V::Boolean(options.list_files_only.is_true())
    );
    field!(
        no_emit_for_js_files,
        b"noEmitForJsFiles",
        V::Boolean(options.no_emit_for_js_files.is_true())
    );
    field!(
        preserve_watch_output,
        b"preserveWatchOutput",
        V::Boolean(options.preserve_watch_output.is_true())
    );
    field!(pretty, b"pretty", V::Boolean(options.pretty.is_true()));
    field!(version, b"version", V::Boolean(options.version.is_true()));
    field!(watch, b"watch", V::Boolean(options.watch.is_true()));
    field!(
        show_config,
        b"showConfig",
        V::Boolean(options.show_config.is_true())
    );
    field!(build, b"build", V::Boolean(options.build.is_true()));
    field!(help, b"help", V::Boolean(options.help.is_true()));
    field!(all, b"all", V::Boolean(options.all.is_true()));
    field!(
        run_external_code,
        b"runExternalCode",
        V::Boolean(options.run_external_code.is_true())
    );
    field!(pprof_dir, b"pprofDir", V::String(options.pprof_dir.clone()));
    field!(
        single_threaded,
        b"singleThreaded",
        V::Boolean(options.single_threaded.is_true())
    );
    field!(quiet, b"quiet", V::Boolean(options.quiet.is_true()));
    field!(
        checkers,
        b"checkers",
        V::Integer(options.checkers.expect("present number") as i64)
    );
    V::Object(values)
}
