[package]
name = "ts_vfs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ts_tspath = { version = "0.1.0", path = "../ts_tspath" }
ts_jsstring = { version = "0.1.0", path = "../ts_jsstring" }

[lints]
workspace = true
