// Generated by tools/s07/binder/generate_syntax.py; access-only observer.
use super::{hex, json, Graph, NodeDataRead, Value};
impl Graph<'_> {
    pub(super) fn syntax_fields(
        &mut self,
        node: &(impl ts_ast::NodeAccess + ?Sized),
    ) -> (&'static str, Vec<Value>) {
        match node.data() {
            NodeDataRead::Token(data) => {
                let _ = data;
                ("Token", vec![])
            }
            NodeDataRead::Identifier(data) => (
                "Identifier",
                vec![json!(["Text", "text", hex(data.text())])],
            ),
            NodeDataRead::PrivateIdentifier(data) => (
                "PrivateIdentifier",
                vec![json!(["Text", "text", hex(data.text())])],
            ),
            NodeDataRead::QualifiedName(data) => (
                "QualifiedName",
                vec![
                    json!(["Left", "node", self.node_ref(data.left())]),
                    json!(["Right", "node", self.node_ref(data.right())]),
                ],
            ),
            NodeDataRead::ComputedPropertyName(data) => (
                "ComputedPropertyName",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::Decorator(data) => (
                "Decorator",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::EmptyStatement(data) => {
                let _ = data;
                ("EmptyStatement", vec![])
            }
            NodeDataRead::IfStatement(data) => (
                "IfStatement",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!([
                        "ThenStatement",
                        "node",
                        self.node_ref(data.then_statement())
                    ]),
                    json!([
                        "ElseStatement",
                        "node",
                        self.node_ref(data.else_statement())
                    ]),
                ],
            ),
            NodeDataRead::DoStatement(data) => (
                "DoStatement",
                vec![
                    json!(["Statement", "node", self.node_ref(data.statement())]),
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                ],
            ),
            NodeDataRead::WhileStatement(data) => (
                "WhileStatement",
                vec![
                    json!(["Statement", "node", self.node_ref(data.statement())]),
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                ],
            ),
            NodeDataRead::ForStatement(data) => (
                "ForStatement",
                vec![
                    json!(["Statement", "node", self.node_ref(data.statement())]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                    json!(["Condition", "node", self.node_ref(data.condition())]),
                    json!(["Incrementor", "node", self.node_ref(data.incrementor())]),
                ],
            ),
            NodeDataRead::ForInOrOfStatement(data) => (
                "ForInOrOfStatement",
                vec![
                    json!([
                        "AwaitModifier",
                        "node",
                        self.node_ref(data.await_modifier())
                    ]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!(["Statement", "node", self.node_ref(data.statement())]),
                ],
            ),
            NodeDataRead::BreakStatement(data) => (
                "BreakStatement",
                vec![json!(["Label", "node", self.node_ref(data.label())])],
            ),
            NodeDataRead::ContinueStatement(data) => (
                "ContinueStatement",
                vec![json!(["Label", "node", self.node_ref(data.label())])],
            ),
            NodeDataRead::ReturnStatement(data) => (
                "ReturnStatement",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::WithStatement(data) => (
                "WithStatement",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!(["Statement", "node", self.node_ref(data.statement())]),
                ],
            ),
            NodeDataRead::SwitchStatement(data) => (
                "SwitchStatement",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!(["CaseBlock", "node", self.node_ref(data.case_block())]),
                ],
            ),
            NodeDataRead::CaseBlock(data) => (
                "CaseBlock",
                vec![json!([
                    "Clauses",
                    "list",
                    self.list_ref(data.clauses(), false)
                ])],
            ),
            NodeDataRead::CaseOrDefaultClause(data) => (
                "CaseOrDefaultClause",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!([
                        "Statements",
                        "list",
                        self.list_ref(data.statements(), false)
                    ]),
                ],
            ),
            NodeDataRead::ThrowStatement(data) => (
                "ThrowStatement",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::TryStatement(data) => (
                "TryStatement",
                vec![
                    json!(["TryBlock", "node", self.node_ref(data.try_block())]),
                    json!(["CatchClause", "node", self.node_ref(data.catch_clause())]),
                    json!(["FinallyBlock", "node", self.node_ref(data.finally_block())]),
                ],
            ),
            NodeDataRead::CatchClause(data) => (
                "CatchClause",
                vec![
                    json!([
                        "VariableDeclaration",
                        "node",
                        self.node_ref(data.variable_declaration())
                    ]),
                    json!(["Block", "node", self.node_ref(data.block())]),
                ],
            ),
            NodeDataRead::DebuggerStatement(data) => {
                let _ = data;
                ("DebuggerStatement", vec![])
            }
            NodeDataRead::LabeledStatement(data) => (
                "LabeledStatement",
                vec![
                    json!(["Label", "node", self.node_ref(data.label())]),
                    json!(["Statement", "node", self.node_ref(data.statement())]),
                ],
            ),
            NodeDataRead::ExpressionStatement(data) => (
                "ExpressionStatement",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::Block(data) => (
                "Block",
                vec![
                    json!([
                        "Statements",
                        "list",
                        self.list_ref(data.statements(), false)
                    ]),
                    json!(["MultiLine", "bool", data.multi_line()]),
                ],
            ),
            NodeDataRead::VariableStatement(data) => (
                "VariableStatement",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "DeclarationList",
                        "node",
                        self.node_ref(data.declaration_list())
                    ]),
                ],
            ),
            NodeDataRead::VariableDeclaration(data) => (
                "VariableDeclaration",
                vec![
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!([
                        "ExclamationToken",
                        "node",
                        self.node_ref(data.exclamation_token())
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                ],
            ),
            NodeDataRead::VariableDeclarationList(data) => (
                "VariableDeclarationList",
                vec![json!([
                    "Declarations",
                    "list",
                    self.list_ref(data.declarations(), false)
                ])],
            ),
            NodeDataRead::BindingPattern(data) => (
                "BindingPattern",
                vec![json!([
                    "Elements",
                    "list",
                    self.list_ref(data.elements(), false)
                ])],
            ),
            NodeDataRead::ParameterDeclaration(data) => (
                "ParameterDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "DotDotDotToken",
                        "node",
                        self.node_ref(data.dot_dot_dot_token())
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!([
                        "QuestionToken",
                        "node",
                        self.node_ref(data.question_token())
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                ],
            ),
            NodeDataRead::BindingElement(data) => (
                "BindingElement",
                vec![
                    json!([
                        "DotDotDotToken",
                        "node",
                        self.node_ref(data.dot_dot_dot_token())
                    ]),
                    json!(["PropertyName", "node", self.node_ref(data.property_name())]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                ],
            ),
            NodeDataRead::MissingDeclaration(data) => (
                "MissingDeclaration",
                vec![json!([
                    "modifiers",
                    "modifiers",
                    self.list_ref(data.modifiers(), true)
                ])],
            ),
            NodeDataRead::FunctionDeclaration(data) => (
                "FunctionDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                    json!([
                        "AsteriskToken",
                        "node",
                        self.node_ref(data.asterisk_token())
                    ]),
                    json!(["Body", "node", self.node_ref(data.body())]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::ClassDeclaration(data) => (
                "ClassDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "HeritageClauses",
                        "list",
                        self.list_ref(data.heritage_clauses(), false)
                    ]),
                    json!(["Members", "list", self.list_ref(data.members(), false)]),
                ],
            ),
            NodeDataRead::ClassExpression(data) => (
                "ClassExpression",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "HeritageClauses",
                        "list",
                        self.list_ref(data.heritage_clauses(), false)
                    ]),
                    json!(["Members", "list", self.list_ref(data.members(), false)]),
                ],
            ),
            NodeDataRead::HeritageClause(data) => (
                "HeritageClause",
                vec![
                    json!(["Token", "kind", data.token().raw()]),
                    json!(["Types", "list", self.list_ref(data.types(), false)]),
                ],
            ),
            NodeDataRead::InterfaceDeclaration(data) => (
                "InterfaceDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "HeritageClauses",
                        "list",
                        self.list_ref(data.heritage_clauses(), false)
                    ]),
                    json!(["Members", "list", self.list_ref(data.members(), false)]),
                ],
            ),
            NodeDataRead::TypeAliasDeclaration(data) => (
                "TypeAliasDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                ],
            ),
            NodeDataRead::EnumMember(data) => (
                "EnumMember",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token())]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                ],
            ),
            NodeDataRead::EnumDeclaration(data) => (
                "EnumDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["Members", "list", self.list_ref(data.members(), false)]),
                ],
            ),
            NodeDataRead::ModuleBlock(data) => (
                "ModuleBlock",
                vec![json!([
                    "Statements",
                    "list",
                    self.list_ref(data.statements(), false)
                ])],
            ),
            NodeDataRead::NotEmittedStatement(data) => {
                let _ = data;
                ("NotEmittedStatement", vec![])
            }
            NodeDataRead::NotEmittedTypeElement(data) => {
                let _ = data;
                ("NotEmittedTypeElement", vec![])
            }
            NodeDataRead::ImportDeclaration(data) => (
                "ImportDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["ImportClause", "node", self.node_ref(data.import_clause())]),
                    json!([
                        "ModuleSpecifier",
                        "node",
                        self.node_ref(data.module_specifier())
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes())]),
                ],
            ),
            NodeDataRead::ExternalModuleReference(data) => (
                "ExternalModuleReference",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::NamespaceImport(data) => (
                "NamespaceImport",
                vec![json!(["name", "node", self.node_ref(data.name())])],
            ),
            NodeDataRead::NamedImports(data) => (
                "NamedImports",
                vec![json!([
                    "Elements",
                    "list",
                    self.list_ref(data.elements(), false)
                ])],
            ),
            NodeDataRead::ExportAssignment(data) => (
                "ExportAssignment",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["IsExportEquals", "bool", data.is_export_equals()]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                ],
            ),
            NodeDataRead::NamespaceExportDeclaration(data) => (
                "NamespaceExportDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::NamespaceExport(data) => (
                "NamespaceExport",
                vec![json!(["name", "node", self.node_ref(data.name())])],
            ),
            NodeDataRead::NamedExports(data) => (
                "NamedExports",
                vec![json!([
                    "Elements",
                    "list",
                    self.list_ref(data.elements(), false)
                ])],
            ),
            NodeDataRead::ExportSpecifier(data) => (
                "ExportSpecifier",
                vec![
                    json!(["IsTypeOnly", "bool", data.is_type_only()]),
                    json!(["PropertyName", "node", self.node_ref(data.property_name())]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::CallSignatureDeclaration(data) => (
                "CallSignatureDeclaration",
                vec![
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                ],
            ),
            NodeDataRead::ConstructSignatureDeclaration(data) => (
                "ConstructSignatureDeclaration",
                vec![
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                ],
            ),
            NodeDataRead::ConstructorDeclaration(data) => (
                "ConstructorDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                    json!([
                        "AsteriskToken",
                        "node",
                        self.node_ref(data.asterisk_token())
                    ]),
                    json!(["Body", "node", self.node_ref(data.body())]),
                ],
            ),
            NodeDataRead::GetAccessorDeclaration(data) => (
                "GetAccessorDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token())]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                    json!([
                        "AsteriskToken",
                        "node",
                        self.node_ref(data.asterisk_token())
                    ]),
                    json!(["Body", "node", self.node_ref(data.body())]),
                ],
            ),
            NodeDataRead::SetAccessorDeclaration(data) => (
                "SetAccessorDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token())]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                    json!([
                        "AsteriskToken",
                        "node",
                        self.node_ref(data.asterisk_token())
                    ]),
                    json!(["Body", "node", self.node_ref(data.body())]),
                ],
            ),
            NodeDataRead::IndexSignatureDeclaration(data) => (
                "IndexSignatureDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                ],
            ),
            NodeDataRead::MethodSignatureDeclaration(data) => (
                "MethodSignatureDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token())]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                ],
            ),
            NodeDataRead::MethodDeclaration(data) => (
                "MethodDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token())]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                    json!([
                        "AsteriskToken",
                        "node",
                        self.node_ref(data.asterisk_token())
                    ]),
                    json!(["Body", "node", self.node_ref(data.body())]),
                ],
            ),
            NodeDataRead::PropertySignatureDeclaration(data) => (
                "PropertySignatureDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token())]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                ],
            ),
            NodeDataRead::PropertyDeclaration(data) => (
                "PropertyDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token())]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                ],
            ),
            NodeDataRead::SemicolonClassElement(data) => {
                let _ = data;
                ("SemicolonClassElement", vec![])
            }
            NodeDataRead::ClassStaticBlockDeclaration(data) => (
                "ClassStaticBlockDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["Body", "node", self.node_ref(data.body())]),
                ],
            ),
            NodeDataRead::OmittedExpression(data) => {
                let _ = data;
                ("OmittedExpression", vec![])
            }
            NodeDataRead::KeywordExpression(data) => {
                let _ = data;
                ("KeywordExpression", vec![])
            }
            NodeDataRead::StringLiteral(data) => (
                "StringLiteral",
                vec![
                    json!(["Text", "text", hex(data.text())]),
                    json!(["TokenFlags", "number", data.token_flags()]),
                ],
            ),
            NodeDataRead::NumericLiteral(data) => (
                "NumericLiteral",
                vec![
                    json!(["Text", "text", hex(data.text())]),
                    json!(["TokenFlags", "number", data.token_flags()]),
                ],
            ),
            NodeDataRead::BigIntLiteral(data) => (
                "BigIntLiteral",
                vec![
                    json!(["Text", "text", hex(data.text())]),
                    json!(["TokenFlags", "number", data.token_flags()]),
                ],
            ),
            NodeDataRead::RegularExpressionLiteral(data) => (
                "RegularExpressionLiteral",
                vec![
                    json!(["Text", "text", hex(data.text())]),
                    json!(["TokenFlags", "number", data.token_flags()]),
                ],
            ),
            NodeDataRead::NoSubstitutionTemplateLiteral(data) => (
                "NoSubstitutionTemplateLiteral",
                vec![
                    json!(["Text", "text", hex(data.text())]),
                    json!(["TokenFlags", "number", data.token_flags()]),
                    json!(["RawText", "text", hex(data.raw_text())]),
                    json!(["TemplateFlags", "number", data.template_flags()]),
                ],
            ),
            NodeDataRead::BinaryExpression(data) => (
                "BinaryExpression",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["Left", "node", self.node_ref(data.left())]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "OperatorToken",
                        "node",
                        self.node_ref(data.operator_token())
                    ]),
                    json!(["Right", "node", self.node_ref(data.right())]),
                ],
            ),
            NodeDataRead::PrefixUnaryExpression(data) => (
                "PrefixUnaryExpression",
                vec![
                    json!(["Operator", "kind", data.operator().raw()]),
                    json!(["Operand", "node", self.node_ref(data.operand())]),
                ],
            ),
            NodeDataRead::PostfixUnaryExpression(data) => (
                "PostfixUnaryExpression",
                vec![
                    json!(["Operand", "node", self.node_ref(data.operand())]),
                    json!(["Operator", "kind", data.operator().raw()]),
                ],
            ),
            NodeDataRead::YieldExpression(data) => (
                "YieldExpression",
                vec![
                    json!([
                        "AsteriskToken",
                        "node",
                        self.node_ref(data.asterisk_token())
                    ]),
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                ],
            ),
            NodeDataRead::ArrowFunction(data) => (
                "ArrowFunction",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                    json!([
                        "AsteriskToken",
                        "node",
                        self.node_ref(data.asterisk_token())
                    ]),
                    json!(["Body", "node", self.node_ref(data.body())]),
                    json!([
                        "EqualsGreaterThanToken",
                        "node",
                        self.node_ref(data.equals_greater_than_token())
                    ]),
                ],
            ),
            NodeDataRead::FunctionExpression(data) => (
                "FunctionExpression",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                    json!([
                        "AsteriskToken",
                        "node",
                        self.node_ref(data.asterisk_token())
                    ]),
                    json!(["Body", "node", self.node_ref(data.body())]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::AsExpression(data) => (
                "AsExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                ],
            ),
            NodeDataRead::SatisfiesExpression(data) => (
                "SatisfiesExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                ],
            ),
            NodeDataRead::ConditionalExpression(data) => (
                "ConditionalExpression",
                vec![
                    json!(["Condition", "node", self.node_ref(data.condition())]),
                    json!([
                        "QuestionToken",
                        "node",
                        self.node_ref(data.question_token())
                    ]),
                    json!(["WhenTrue", "node", self.node_ref(data.when_true())]),
                    json!(["ColonToken", "node", self.node_ref(data.colon_token())]),
                    json!(["WhenFalse", "node", self.node_ref(data.when_false())]),
                ],
            ),
            NodeDataRead::PropertyAccessExpression(data) => (
                "PropertyAccessExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!([
                        "QuestionDotToken",
                        "node",
                        self.node_ref(data.question_dot_token())
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::ElementAccessExpression(data) => (
                "ElementAccessExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!([
                        "QuestionDotToken",
                        "node",
                        self.node_ref(data.question_dot_token())
                    ]),
                    json!([
                        "ArgumentExpression",
                        "node",
                        self.node_ref(data.argument_expression())
                    ]),
                ],
            ),
            NodeDataRead::CallExpression(data) => (
                "CallExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!([
                        "QuestionDotToken",
                        "node",
                        self.node_ref(data.question_dot_token())
                    ]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments(), false)
                    ]),
                    json!(["Arguments", "list", self.list_ref(data.arguments(), false)]),
                ],
            ),
            NodeDataRead::NewExpression(data) => (
                "NewExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments(), false)
                    ]),
                    json!(["Arguments", "list", self.list_ref(data.arguments(), false)]),
                ],
            ),
            NodeDataRead::MetaProperty(data) => (
                "MetaProperty",
                vec![
                    json!(["KeywordToken", "kind", data.keyword_token().raw()]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::NonNullExpression(data) => (
                "NonNullExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::SpreadElement(data) => (
                "SpreadElement",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::TemplateExpression(data) => (
                "TemplateExpression",
                vec![
                    json!(["Head", "node", self.node_ref(data.head())]),
                    json!([
                        "TemplateSpans",
                        "list",
                        self.list_ref(data.template_spans(), false)
                    ]),
                ],
            ),
            NodeDataRead::TemplateSpan(data) => (
                "TemplateSpan",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!(["Literal", "node", self.node_ref(data.literal())]),
                ],
            ),
            NodeDataRead::TaggedTemplateExpression(data) => (
                "TaggedTemplateExpression",
                vec![
                    json!(["Tag", "node", self.node_ref(data.tag())]),
                    json!([
                        "QuestionDotToken",
                        "node",
                        self.node_ref(data.question_dot_token())
                    ]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments(), false)
                    ]),
                    json!(["Template", "node", self.node_ref(data.template())]),
                ],
            ),
            NodeDataRead::ParenthesizedExpression(data) => (
                "ParenthesizedExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::ArrayLiteralExpression(data) => (
                "ArrayLiteralExpression",
                vec![
                    json!(["Elements", "list", self.list_ref(data.elements(), false)]),
                    json!(["MultiLine", "bool", data.multi_line()]),
                ],
            ),
            NodeDataRead::ObjectLiteralExpression(data) => (
                "ObjectLiteralExpression",
                vec![
                    json!([
                        "Properties",
                        "list",
                        self.list_ref(data.properties(), false)
                    ]),
                    json!(["MultiLine", "bool", data.multi_line()]),
                ],
            ),
            NodeDataRead::SpreadAssignment(data) => (
                "SpreadAssignment",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::PropertyAssignment(data) => (
                "PropertyAssignment",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token())]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                ],
            ),
            NodeDataRead::ShorthandPropertyAssignment(data) => (
                "ShorthandPropertyAssignment",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token())]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["EqualsToken", "node", self.node_ref(data.equals_token())]),
                    json!([
                        "ObjectAssignmentInitializer",
                        "node",
                        self.node_ref(data.object_assignment_initializer())
                    ]),
                ],
            ),
            NodeDataRead::DeleteExpression(data) => (
                "DeleteExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::TypeOfExpression(data) => (
                "TypeOfExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::VoidExpression(data) => (
                "VoidExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::AwaitExpression(data) => (
                "AwaitExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::TypeAssertion(data) => (
                "TypeAssertion",
                vec![
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                ],
            ),
            NodeDataRead::KeywordTypeNode(data) => {
                let _ = data;
                ("KeywordTypeNode", vec![])
            }
            NodeDataRead::UnionTypeNode(data) => (
                "UnionTypeNode",
                vec![json!(["Types", "list", self.list_ref(data.types(), false)])],
            ),
            NodeDataRead::IntersectionTypeNode(data) => (
                "IntersectionTypeNode",
                vec![json!(["Types", "list", self.list_ref(data.types(), false)])],
            ),
            NodeDataRead::ConditionalTypeNode(data) => (
                "ConditionalTypeNode",
                vec![
                    json!(["CheckType", "node", self.node_ref(data.check_type())]),
                    json!(["ExtendsType", "node", self.node_ref(data.extends_type())]),
                    json!(["TrueType", "node", self.node_ref(data.true_type())]),
                    json!(["FalseType", "node", self.node_ref(data.false_type())]),
                ],
            ),
            NodeDataRead::TypeOperatorNode(data) => (
                "TypeOperatorNode",
                vec![
                    json!(["Operator", "kind", data.operator().raw()]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                ],
            ),
            NodeDataRead::InferTypeNode(data) => (
                "InferTypeNode",
                vec![json!([
                    "TypeParameter",
                    "node",
                    self.node_ref(data.type_parameter())
                ])],
            ),
            NodeDataRead::ArrayTypeNode(data) => (
                "ArrayTypeNode",
                vec![json!([
                    "ElementType",
                    "node",
                    self.node_ref(data.element_type())
                ])],
            ),
            NodeDataRead::IndexedAccessTypeNode(data) => (
                "IndexedAccessTypeNode",
                vec![
                    json!(["ObjectType", "node", self.node_ref(data.object_type())]),
                    json!(["IndexType", "node", self.node_ref(data.index_type())]),
                ],
            ),
            NodeDataRead::TypeReferenceNode(data) => (
                "TypeReferenceNode",
                vec![
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments(), false)
                    ]),
                    json!(["TypeName", "node", self.node_ref(data.type_name())]),
                ],
            ),
            NodeDataRead::ExpressionWithTypeArguments(data) => (
                "ExpressionWithTypeArguments",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments(), false)
                    ]),
                ],
            ),
            NodeDataRead::LiteralTypeNode(data) => (
                "LiteralTypeNode",
                vec![json!(["Literal", "node", self.node_ref(data.literal())])],
            ),
            NodeDataRead::ThisTypeNode(data) => {
                let _ = data;
                ("ThisTypeNode", vec![])
            }
            NodeDataRead::TypePredicateNode(data) => (
                "TypePredicateNode",
                vec![
                    json!([
                        "AssertsModifier",
                        "node",
                        self.node_ref(data.asserts_modifier())
                    ]),
                    json!([
                        "ParameterName",
                        "node",
                        self.node_ref(data.parameter_name())
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                ],
            ),
            NodeDataRead::ImportAttribute(data) => (
                "ImportAttribute",
                vec![
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["Value", "node", self.node_ref(data.value())]),
                ],
            ),
            NodeDataRead::ImportAttributes(data) => (
                "ImportAttributes",
                vec![
                    json!(["Token", "kind", data.token().raw()]),
                    json!([
                        "Attributes",
                        "list",
                        self.list_ref(data.attributes(), false)
                    ]),
                    json!(["MultiLine", "bool", data.multi_line()]),
                ],
            ),
            NodeDataRead::TypeQueryNode(data) => (
                "TypeQueryNode",
                vec![
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments(), false)
                    ]),
                    json!(["ExprName", "node", self.node_ref(data.expr_name())]),
                ],
            ),
            NodeDataRead::MappedTypeNode(data) => (
                "MappedTypeNode",
                vec![
                    json!([
                        "ReadonlyToken",
                        "node",
                        self.node_ref(data.readonly_token())
                    ]),
                    json!([
                        "TypeParameter",
                        "node",
                        self.node_ref(data.type_parameter())
                    ]),
                    json!(["NameType", "node", self.node_ref(data.name_type())]),
                    json!([
                        "QuestionToken",
                        "node",
                        self.node_ref(data.question_token())
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["Members", "list", self.list_ref(data.members(), false)]),
                ],
            ),
            NodeDataRead::TypeLiteralNode(data) => (
                "TypeLiteralNode",
                vec![json!([
                    "Members",
                    "list",
                    self.list_ref(data.members(), false)
                ])],
            ),
            NodeDataRead::TupleTypeNode(data) => (
                "TupleTypeNode",
                vec![json!([
                    "Elements",
                    "list",
                    self.list_ref(data.elements(), false)
                ])],
            ),
            NodeDataRead::NamedTupleMember(data) => (
                "NamedTupleMember",
                vec![
                    json!([
                        "DotDotDotToken",
                        "node",
                        self.node_ref(data.dot_dot_dot_token())
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!([
                        "QuestionToken",
                        "node",
                        self.node_ref(data.question_token())
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                ],
            ),
            NodeDataRead::OptionalTypeNode(data) => (
                "OptionalTypeNode",
                vec![json!(["Type", "node", self.node_ref(data.r#type())])],
            ),
            NodeDataRead::RestTypeNode(data) => (
                "RestTypeNode",
                vec![json!(["Type", "node", self.node_ref(data.r#type())])],
            ),
            NodeDataRead::ParenthesizedTypeNode(data) => (
                "ParenthesizedTypeNode",
                vec![json!(["Type", "node", self.node_ref(data.r#type())])],
            ),
            NodeDataRead::FunctionTypeNode(data) => (
                "FunctionTypeNode",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                ],
            ),
            NodeDataRead::ConstructorTypeNode(data) => (
                "ConstructorTypeNode",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                ],
            ),
            NodeDataRead::TemplateHead(data) => (
                "TemplateHead",
                vec![
                    json!(["Text", "text", hex(data.text())]),
                    json!(["TokenFlags", "number", data.token_flags()]),
                    json!(["RawText", "text", hex(data.raw_text())]),
                    json!(["TemplateFlags", "number", data.template_flags()]),
                ],
            ),
            NodeDataRead::TemplateMiddle(data) => (
                "TemplateMiddle",
                vec![
                    json!(["Text", "text", hex(data.text())]),
                    json!(["TokenFlags", "number", data.token_flags()]),
                    json!(["RawText", "text", hex(data.raw_text())]),
                    json!(["TemplateFlags", "number", data.template_flags()]),
                ],
            ),
            NodeDataRead::TemplateTail(data) => (
                "TemplateTail",
                vec![
                    json!(["Text", "text", hex(data.text())]),
                    json!(["TokenFlags", "number", data.token_flags()]),
                    json!(["RawText", "text", hex(data.raw_text())]),
                    json!(["TemplateFlags", "number", data.template_flags()]),
                ],
            ),
            NodeDataRead::TemplateLiteralTypeNode(data) => (
                "TemplateLiteralTypeNode",
                vec![
                    json!(["Head", "node", self.node_ref(data.head())]),
                    json!([
                        "TemplateSpans",
                        "list",
                        self.list_ref(data.template_spans(), false)
                    ]),
                ],
            ),
            NodeDataRead::TemplateLiteralTypeSpan(data) => (
                "TemplateLiteralTypeSpan",
                vec![
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!(["Literal", "node", self.node_ref(data.literal())]),
                ],
            ),
            NodeDataRead::SyntheticExpression(data) => (
                "SyntheticExpression",
                vec![
                    json!(["Type", "opaque", Value::Null]),
                    json!(["IsSpread", "bool", data.is_spread()]),
                    json!([
                        "TupleNameSource",
                        "node",
                        self.node_ref(data.tuple_name_source())
                    ]),
                ],
            ),
            NodeDataRead::PartiallyEmittedExpression(data) => (
                "PartiallyEmittedExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::JsxElement(data) => (
                "JsxElement",
                vec![
                    json!([
                        "OpeningElement",
                        "node",
                        self.node_ref(data.opening_element())
                    ]),
                    json!(["Children", "list", self.list_ref(data.children(), false)]),
                    json!([
                        "ClosingElement",
                        "node",
                        self.node_ref(data.closing_element())
                    ]),
                ],
            ),
            NodeDataRead::JsxAttributes(data) => (
                "JsxAttributes",
                vec![json!([
                    "Properties",
                    "list",
                    self.list_ref(data.properties(), false)
                ])],
            ),
            NodeDataRead::JsxNamespacedName(data) => (
                "JsxNamespacedName",
                vec![
                    json!(["Namespace", "node", self.node_ref(data.namespace())]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::JsxOpeningElement(data) => (
                "JsxOpeningElement",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments(), false)
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes())]),
                ],
            ),
            NodeDataRead::JsxSelfClosingElement(data) => (
                "JsxSelfClosingElement",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments(), false)
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes())]),
                ],
            ),
            NodeDataRead::JsxFragment(data) => (
                "JsxFragment",
                vec![
                    json!([
                        "OpeningFragment",
                        "node",
                        self.node_ref(data.opening_fragment())
                    ]),
                    json!(["Children", "list", self.list_ref(data.children(), false)]),
                    json!([
                        "ClosingFragment",
                        "node",
                        self.node_ref(data.closing_fragment())
                    ]),
                ],
            ),
            NodeDataRead::JsxOpeningFragment(data) => {
                let _ = data;
                ("JsxOpeningFragment", vec![])
            }
            NodeDataRead::JsxClosingFragment(data) => {
                let _ = data;
                ("JsxClosingFragment", vec![])
            }
            NodeDataRead::JsxAttribute(data) => (
                "JsxAttribute",
                vec![
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["Initializer", "node", self.node_ref(data.initializer())]),
                ],
            ),
            NodeDataRead::JsxSpreadAttribute(data) => (
                "JsxSpreadAttribute",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression())
                ])],
            ),
            NodeDataRead::JsxClosingElement(data) => (
                "JsxClosingElement",
                vec![json!(["TagName", "node", self.node_ref(data.tag_name())])],
            ),
            NodeDataRead::JsxExpression(data) => (
                "JsxExpression",
                vec![
                    json!([
                        "DotDotDotToken",
                        "node",
                        self.node_ref(data.dot_dot_dot_token())
                    ]),
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                ],
            ),
            NodeDataRead::JsxText(data) => (
                "JsxText",
                vec![
                    json!(["Text", "text", hex(data.text())]),
                    json!(["TokenFlags", "number", data.token_flags()]),
                    json!([
                        "ContainsOnlyTriviaWhiteSpaces",
                        "bool",
                        data.contains_only_trivia_white_spaces()
                    ]),
                ],
            ),
            NodeDataRead::SyntaxList(data) => (
                "SyntaxList",
                vec![json!([
                    "Children",
                    "nodes",
                    self.node_slice_ref(data.children())
                ])],
            ),
            NodeDataRead::JSDoc(data) => (
                "JSDoc",
                vec![
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!(["Tags", "list", self.list_ref(data.tags(), false)]),
                ],
            ),
            NodeDataRead::JSDocTypeExpression(data) => (
                "JSDocTypeExpression",
                vec![json!(["Type", "node", self.node_ref(data.r#type())])],
            ),
            NodeDataRead::JSDocNonNullableType(data) => (
                "JSDocNonNullableType",
                vec![json!(["Type", "node", self.node_ref(data.r#type())])],
            ),
            NodeDataRead::JSDocNullableType(data) => (
                "JSDocNullableType",
                vec![json!(["Type", "node", self.node_ref(data.r#type())])],
            ),
            NodeDataRead::JSDocAllType(data) => {
                let _ = data;
                ("JSDocAllType", vec![])
            }
            NodeDataRead::JSDocVariadicType(data) => (
                "JSDocVariadicType",
                vec![json!(["Type", "node", self.node_ref(data.r#type())])],
            ),
            NodeDataRead::JSDocOptionalType(data) => (
                "JSDocOptionalType",
                vec![json!(["Type", "node", self.node_ref(data.r#type())])],
            ),
            NodeDataRead::JSDocTypeTag(data) => (
                "JSDocTypeTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression())
                    ]),
                ],
            ),
            NodeDataRead::JSDocUnknownTag(data) => (
                "JSDocUnknownTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                ],
            ),
            NodeDataRead::JSDocTemplateTag(data) => (
                "JSDocTemplateTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!(["Constraint", "node", self.node_ref(data.constraint())]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                ],
            ),
            NodeDataRead::JSDocReturnTag(data) => (
                "JSDocReturnTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression())
                    ]),
                ],
            ),
            NodeDataRead::JSDocPublicTag(data) => (
                "JSDocPublicTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                ],
            ),
            NodeDataRead::JSDocPrivateTag(data) => (
                "JSDocPrivateTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                ],
            ),
            NodeDataRead::JSDocProtectedTag(data) => (
                "JSDocProtectedTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                ],
            ),
            NodeDataRead::JSDocReadonlyTag(data) => (
                "JSDocReadonlyTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                ],
            ),
            NodeDataRead::JSDocOverrideTag(data) => (
                "JSDocOverrideTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                ],
            ),
            NodeDataRead::JSDocDeprecatedTag(data) => (
                "JSDocDeprecatedTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                ],
            ),
            NodeDataRead::JSDocSeeTag(data) => (
                "JSDocSeeTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!([
                        "NameExpression",
                        "node",
                        self.node_ref(data.name_expression())
                    ]),
                ],
            ),
            NodeDataRead::JSDocImplementsTag(data) => (
                "JSDocImplementsTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!(["ClassName", "node", self.node_ref(data.class_name())]),
                ],
            ),
            NodeDataRead::JSDocAugmentsTag(data) => (
                "JSDocAugmentsTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!(["ClassName", "node", self.node_ref(data.class_name())]),
                ],
            ),
            NodeDataRead::JSDocSatisfiesTag(data) => (
                "JSDocSatisfiesTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression())
                    ]),
                ],
            ),
            NodeDataRead::JSDocThrowsTag(data) => (
                "JSDocThrowsTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression())
                    ]),
                ],
            ),
            NodeDataRead::JSDocThisTag(data) => (
                "JSDocThisTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression())
                    ]),
                ],
            ),
            NodeDataRead::JSDocImportTag(data) => (
                "JSDocImportTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!(["ImportClause", "node", self.node_ref(data.import_clause())]),
                    json!([
                        "ModuleSpecifier",
                        "node",
                        self.node_ref(data.module_specifier())
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes())]),
                ],
            ),
            NodeDataRead::JSDocCallbackTag(data) => (
                "JSDocCallbackTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression())
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::JSDocOverloadTag(data) => (
                "JSDocOverloadTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression())
                    ]),
                ],
            ),
            NodeDataRead::JSDocTypedefTag(data) => (
                "JSDocTypedefTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression())
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::JSDocSignature(data) => (
                "JSDocSignature",
                vec![
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters(), false)
                    ]),
                    json!([
                        "Parameters",
                        "list",
                        self.list_ref(data.parameters(), false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type())]),
                    json!([
                        "FullSignature",
                        "node",
                        self.node_ref(data.full_signature())
                    ]),
                ],
            ),
            NodeDataRead::JSDocNameReference(data) => (
                "JSDocNameReference",
                vec![json!(["name", "node", self.node_ref(data.name())])],
            ),
            NodeDataRead::SourceFile(data) => (
                "SourceFile",
                vec![
                    json!([
                        "Statements",
                        "list",
                        self.list_ref(data.statements(), false)
                    ]),
                    json!([
                        "EndOfFileToken",
                        "node",
                        self.node_ref(data.end_of_file_token())
                    ]),
                ],
            ),
            NodeDataRead::ModuleDeclaration(data) => (
                "ModuleDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!([
                        "AsteriskToken",
                        "node",
                        self.node_ref(data.asterisk_token())
                    ]),
                    json!(["Body", "node", self.node_ref(data.body())]),
                    json!(["Keyword", "kind", data.keyword().raw()]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["Attributes", "node", self.node_ref(data.attributes())]),
                ],
            ),
            NodeDataRead::ImportEqualsDeclaration(data) => (
                "ImportEqualsDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["IsTypeOnly", "bool", data.is_type_only()]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!([
                        "ModuleReference",
                        "node",
                        self.node_ref(data.module_reference())
                    ]),
                ],
            ),
            NodeDataRead::ExportDeclaration(data) => (
                "ExportDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["IsTypeOnly", "bool", data.is_type_only()]),
                    json!(["ExportClause", "node", self.node_ref(data.export_clause())]),
                    json!([
                        "ModuleSpecifier",
                        "node",
                        self.node_ref(data.module_specifier())
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes())]),
                ],
            ),
            NodeDataRead::ImportTypeNode(data) => (
                "ImportTypeNode",
                vec![
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments(), false)
                    ]),
                    json!(["IsTypeOf", "bool", data.is_type_of()]),
                    json!(["Argument", "node", self.node_ref(data.argument())]),
                    json!(["Attributes", "node", self.node_ref(data.attributes())]),
                    json!(["Qualifier", "node", self.node_ref(data.qualifier())]),
                ],
            ),
            NodeDataRead::ImportClause(data) => (
                "ImportClause",
                vec![
                    json!(["PhaseModifier", "kind", data.phase_modifier().raw()]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!([
                        "NamedBindings",
                        "node",
                        self.node_ref(data.named_bindings())
                    ]),
                ],
            ),
            NodeDataRead::ImportSpecifier(data) => (
                "ImportSpecifier",
                vec![
                    json!(["IsTypeOnly", "bool", data.is_type_only()]),
                    json!(["PropertyName", "node", self.node_ref(data.property_name())]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::JSDocText(data) => (
                "JSDocText",
                vec![json!(["text", "strings", self.text_slice_ref(data.text())])],
            ),
            NodeDataRead::JSDocLink(data) => (
                "JSDocLink",
                vec![
                    json!(["text", "strings", self.text_slice_ref(data.text())]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::JSDocLinkPlain(data) => (
                "JSDocLinkPlain",
                vec![
                    json!(["text", "strings", self.text_slice_ref(data.text())]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::JSDocLinkCode(data) => (
                "JSDocLinkCode",
                vec![
                    json!(["text", "strings", self.text_slice_ref(data.text())]),
                    json!(["name", "node", self.node_ref(data.name())]),
                ],
            ),
            NodeDataRead::TypeParameterDeclaration(data) => (
                "TypeParameterDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers(), true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["Constraint", "node", self.node_ref(data.constraint())]),
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!(["DefaultType", "node", self.node_ref(data.default_type())]),
                ],
            ),
            NodeDataRead::SyntheticReferenceExpression(data) => (
                "SyntheticReferenceExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression())]),
                    json!(["ThisArg", "node", self.node_ref(data.this_arg())]),
                ],
            ),
            NodeDataRead::JSDocTypeLiteral(data) => (
                "JSDocTypeLiteral",
                vec![
                    json!([
                        "JSDocPropertyTags",
                        "nodes",
                        self.node_slice_ref(data.js_doc_property_tags())
                    ]),
                    json!(["IsArrayType", "bool", data.is_array_type()]),
                ],
            ),
            NodeDataRead::JSDocParameterOrPropertyTag(data) => (
                "JSDocParameterOrPropertyTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name())]),
                    json!(["Comment", "list", self.list_ref(data.comment(), false)]),
                    json!(["name", "node", self.node_ref(data.name())]),
                    json!(["IsBracketed", "bool", data.is_bracketed()]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression())
                    ]),
                    json!(["IsNameFirst", "bool", data.is_name_first()]),
                ],
            ),
        }
    }
}
