// Generated by tools/s07/binder/generate_syntax.py; access-only observer.
use super::{hex, json, Graph, NodeData, Value};
impl Graph<'_> {
    pub(super) fn syntax_fields(&mut self, node: &ts_ast::Node) -> (&'static str, Vec<Value>) {
        match node.data() {
            NodeData::Token(data) => {
                let _ = data;
                ("Token", vec![])
            }
            NodeData::Identifier(data) => (
                "Identifier",
                vec![json!(["Text", "text", hex(data.text.as_bytes())])],
            ),
            NodeData::PrivateIdentifier(data) => (
                "PrivateIdentifier",
                vec![json!(["Text", "text", hex(data.text.as_bytes())])],
            ),
            NodeData::QualifiedName(data) => (
                "QualifiedName",
                vec![
                    json!(["Left", "node", self.node_ref(data.left)]),
                    json!(["Right", "node", self.node_ref(data.right)]),
                ],
            ),
            NodeData::ComputedPropertyName(data) => (
                "ComputedPropertyName",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::Decorator(data) => (
                "Decorator",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::EmptyStatement(data) => {
                let _ = data;
                ("EmptyStatement", vec![])
            }
            NodeData::IfStatement(data) => (
                "IfStatement",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["ThenStatement", "node", self.node_ref(data.then_statement)]),
                    json!(["ElseStatement", "node", self.node_ref(data.else_statement)]),
                ],
            ),
            NodeData::DoStatement(data) => (
                "DoStatement",
                vec![
                    json!(["Statement", "node", self.node_ref(data.statement)]),
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                ],
            ),
            NodeData::WhileStatement(data) => (
                "WhileStatement",
                vec![
                    json!(["Statement", "node", self.node_ref(data.statement)]),
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                ],
            ),
            NodeData::ForStatement(data) => (
                "ForStatement",
                vec![
                    json!(["Statement", "node", self.node_ref(data.statement)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                    json!(["Condition", "node", self.node_ref(data.condition)]),
                    json!(["Incrementor", "node", self.node_ref(data.incrementor)]),
                ],
            ),
            NodeData::ForInOrOfStatement(data) => (
                "ForInOrOfStatement",
                vec![
                    json!(["AwaitModifier", "node", self.node_ref(data.await_modifier)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["Statement", "node", self.node_ref(data.statement)]),
                ],
            ),
            NodeData::BreakStatement(data) => (
                "BreakStatement",
                vec![json!(["Label", "node", self.node_ref(data.label)])],
            ),
            NodeData::ContinueStatement(data) => (
                "ContinueStatement",
                vec![json!(["Label", "node", self.node_ref(data.label)])],
            ),
            NodeData::ReturnStatement(data) => (
                "ReturnStatement",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::WithStatement(data) => (
                "WithStatement",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["Statement", "node", self.node_ref(data.statement)]),
                ],
            ),
            NodeData::SwitchStatement(data) => (
                "SwitchStatement",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["CaseBlock", "node", self.node_ref(data.case_block)]),
                ],
            ),
            NodeData::CaseBlock(data) => (
                "CaseBlock",
                vec![json!([
                    "Clauses",
                    "list",
                    self.list_ref(data.clauses, false)
                ])],
            ),
            NodeData::CaseOrDefaultClause(data) => (
                "CaseOrDefaultClause",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["Statements", "list", self.list_ref(data.statements, false)]),
                ],
            ),
            NodeData::ThrowStatement(data) => (
                "ThrowStatement",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::TryStatement(data) => (
                "TryStatement",
                vec![
                    json!(["TryBlock", "node", self.node_ref(data.try_block)]),
                    json!(["CatchClause", "node", self.node_ref(data.catch_clause)]),
                    json!(["FinallyBlock", "node", self.node_ref(data.finally_block)]),
                ],
            ),
            NodeData::CatchClause(data) => (
                "CatchClause",
                vec![
                    json!([
                        "VariableDeclaration",
                        "node",
                        self.node_ref(data.variable_declaration)
                    ]),
                    json!(["Block", "node", self.node_ref(data.block)]),
                ],
            ),
            NodeData::DebuggerStatement(data) => {
                let _ = data;
                ("DebuggerStatement", vec![])
            }
            NodeData::LabeledStatement(data) => (
                "LabeledStatement",
                vec![
                    json!(["Label", "node", self.node_ref(data.label)]),
                    json!(["Statement", "node", self.node_ref(data.statement)]),
                ],
            ),
            NodeData::ExpressionStatement(data) => (
                "ExpressionStatement",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::Block(data) => (
                "Block",
                vec![
                    json!(["Statements", "list", self.list_ref(data.statements, false)]),
                    json!(["MultiLine", "bool", data.multi_line]),
                ],
            ),
            NodeData::VariableStatement(data) => (
                "VariableStatement",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!([
                        "DeclarationList",
                        "node",
                        self.node_ref(data.declaration_list)
                    ]),
                ],
            ),
            NodeData::VariableDeclaration(data) => (
                "VariableDeclaration",
                vec![
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!([
                        "ExclamationToken",
                        "node",
                        self.node_ref(data.exclamation_token)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                ],
            ),
            NodeData::VariableDeclarationList(data) => (
                "VariableDeclarationList",
                vec![json!([
                    "Declarations",
                    "list",
                    self.list_ref(data.declarations, false)
                ])],
            ),
            NodeData::BindingPattern(data) => (
                "BindingPattern",
                vec![json!([
                    "Elements",
                    "list",
                    self.list_ref(data.elements, false)
                ])],
            ),
            NodeData::ParameterDeclaration(data) => (
                "ParameterDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!([
                        "DotDotDotToken",
                        "node",
                        self.node_ref(data.dot_dot_dot_token)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["QuestionToken", "node", self.node_ref(data.question_token)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                ],
            ),
            NodeData::BindingElement(data) => (
                "BindingElement",
                vec![
                    json!([
                        "DotDotDotToken",
                        "node",
                        self.node_ref(data.dot_dot_dot_token)
                    ]),
                    json!(["PropertyName", "node", self.node_ref(data.property_name)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                ],
            ),
            NodeData::MissingDeclaration(data) => (
                "MissingDeclaration",
                vec![json!([
                    "modifiers",
                    "modifiers",
                    self.list_ref(data.modifiers, true)
                ])],
            ),
            NodeData::FunctionDeclaration(data) => (
                "FunctionDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                    json!(["AsteriskToken", "node", self.node_ref(data.asterisk_token)]),
                    json!(["Body", "node", self.node_ref(data.body)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::ClassDeclaration(data) => (
                "ClassDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!([
                        "HeritageClauses",
                        "list",
                        self.list_ref(data.heritage_clauses, false)
                    ]),
                    json!(["Members", "list", self.list_ref(data.members, false)]),
                ],
            ),
            NodeData::ClassExpression(data) => (
                "ClassExpression",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!([
                        "HeritageClauses",
                        "list",
                        self.list_ref(data.heritage_clauses, false)
                    ]),
                    json!(["Members", "list", self.list_ref(data.members, false)]),
                ],
            ),
            NodeData::HeritageClause(data) => (
                "HeritageClause",
                vec![
                    json!(["Token", "kind", data.token.raw()]),
                    json!(["Types", "list", self.list_ref(data.types, false)]),
                ],
            ),
            NodeData::InterfaceDeclaration(data) => (
                "InterfaceDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!([
                        "HeritageClauses",
                        "list",
                        self.list_ref(data.heritage_clauses, false)
                    ]),
                    json!(["Members", "list", self.list_ref(data.members, false)]),
                ],
            ),
            NodeData::TypeAliasDeclaration(data) => (
                "TypeAliasDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                ],
            ),
            NodeData::EnumMember(data) => (
                "EnumMember",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                ],
            ),
            NodeData::EnumDeclaration(data) => (
                "EnumDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["Members", "list", self.list_ref(data.members, false)]),
                ],
            ),
            NodeData::ModuleBlock(data) => (
                "ModuleBlock",
                vec![json!([
                    "Statements",
                    "list",
                    self.list_ref(data.statements, false)
                ])],
            ),
            NodeData::NotEmittedStatement(data) => {
                let _ = data;
                ("NotEmittedStatement", vec![])
            }
            NodeData::NotEmittedTypeElement(data) => {
                let _ = data;
                ("NotEmittedTypeElement", vec![])
            }
            NodeData::ImportDeclaration(data) => (
                "ImportDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["ImportClause", "node", self.node_ref(data.import_clause)]),
                    json!([
                        "ModuleSpecifier",
                        "node",
                        self.node_ref(data.module_specifier)
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes)]),
                ],
            ),
            NodeData::ExternalModuleReference(data) => (
                "ExternalModuleReference",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::NamespaceImport(data) => (
                "NamespaceImport",
                vec![json!(["name", "node", self.node_ref(data.name)])],
            ),
            NodeData::NamedImports(data) => (
                "NamedImports",
                vec![json!([
                    "Elements",
                    "list",
                    self.list_ref(data.elements, false)
                ])],
            ),
            NodeData::ExportAssignment(data) => (
                "ExportAssignment",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["IsExportEquals", "bool", data.is_export_equals]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                ],
            ),
            NodeData::NamespaceExportDeclaration(data) => (
                "NamespaceExportDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::NamespaceExport(data) => (
                "NamespaceExport",
                vec![json!(["name", "node", self.node_ref(data.name)])],
            ),
            NodeData::NamedExports(data) => (
                "NamedExports",
                vec![json!([
                    "Elements",
                    "list",
                    self.list_ref(data.elements, false)
                ])],
            ),
            NodeData::ExportSpecifier(data) => (
                "ExportSpecifier",
                vec![
                    json!(["IsTypeOnly", "bool", data.is_type_only]),
                    json!(["PropertyName", "node", self.node_ref(data.property_name)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::CallSignatureDeclaration(data) => (
                "CallSignatureDeclaration",
                vec![
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                ],
            ),
            NodeData::ConstructSignatureDeclaration(data) => (
                "ConstructSignatureDeclaration",
                vec![
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                ],
            ),
            NodeData::ConstructorDeclaration(data) => (
                "ConstructorDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                    json!(["AsteriskToken", "node", self.node_ref(data.asterisk_token)]),
                    json!(["Body", "node", self.node_ref(data.body)]),
                ],
            ),
            NodeData::GetAccessorDeclaration(data) => (
                "GetAccessorDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token)]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                    json!(["AsteriskToken", "node", self.node_ref(data.asterisk_token)]),
                    json!(["Body", "node", self.node_ref(data.body)]),
                ],
            ),
            NodeData::SetAccessorDeclaration(data) => (
                "SetAccessorDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token)]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                    json!(["AsteriskToken", "node", self.node_ref(data.asterisk_token)]),
                    json!(["Body", "node", self.node_ref(data.body)]),
                ],
            ),
            NodeData::IndexSignatureDeclaration(data) => (
                "IndexSignatureDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                ],
            ),
            NodeData::MethodSignatureDeclaration(data) => (
                "MethodSignatureDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token)]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                ],
            ),
            NodeData::MethodDeclaration(data) => (
                "MethodDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token)]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                    json!(["AsteriskToken", "node", self.node_ref(data.asterisk_token)]),
                    json!(["Body", "node", self.node_ref(data.body)]),
                ],
            ),
            NodeData::PropertySignatureDeclaration(data) => (
                "PropertySignatureDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                ],
            ),
            NodeData::PropertyDeclaration(data) => (
                "PropertyDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                ],
            ),
            NodeData::SemicolonClassElement(data) => {
                let _ = data;
                ("SemicolonClassElement", vec![])
            }
            NodeData::ClassStaticBlockDeclaration(data) => (
                "ClassStaticBlockDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["Body", "node", self.node_ref(data.body)]),
                ],
            ),
            NodeData::OmittedExpression(data) => {
                let _ = data;
                ("OmittedExpression", vec![])
            }
            NodeData::KeywordExpression(data) => {
                let _ = data;
                ("KeywordExpression", vec![])
            }
            NodeData::StringLiteral(data) => (
                "StringLiteral",
                vec![
                    json!(["Text", "text", hex(data.text.as_bytes())]),
                    json!(["TokenFlags", "number", data.token_flags]),
                ],
            ),
            NodeData::NumericLiteral(data) => (
                "NumericLiteral",
                vec![
                    json!(["Text", "text", hex(data.text.as_bytes())]),
                    json!(["TokenFlags", "number", data.token_flags]),
                ],
            ),
            NodeData::BigIntLiteral(data) => (
                "BigIntLiteral",
                vec![
                    json!(["Text", "text", hex(data.text.as_bytes())]),
                    json!(["TokenFlags", "number", data.token_flags]),
                ],
            ),
            NodeData::RegularExpressionLiteral(data) => (
                "RegularExpressionLiteral",
                vec![
                    json!(["Text", "text", hex(data.text.as_bytes())]),
                    json!(["TokenFlags", "number", data.token_flags]),
                ],
            ),
            NodeData::NoSubstitutionTemplateLiteral(data) => (
                "NoSubstitutionTemplateLiteral",
                vec![
                    json!(["Text", "text", hex(data.text.as_bytes())]),
                    json!(["TokenFlags", "number", data.token_flags]),
                    json!(["RawText", "text", hex(data.raw_text.as_bytes())]),
                    json!(["TemplateFlags", "number", data.template_flags]),
                ],
            ),
            NodeData::BinaryExpression(data) => (
                "BinaryExpression",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["Left", "node", self.node_ref(data.left)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["OperatorToken", "node", self.node_ref(data.operator_token)]),
                    json!(["Right", "node", self.node_ref(data.right)]),
                ],
            ),
            NodeData::PrefixUnaryExpression(data) => (
                "PrefixUnaryExpression",
                vec![
                    json!(["Operator", "kind", data.operator.raw()]),
                    json!(["Operand", "node", self.node_ref(data.operand)]),
                ],
            ),
            NodeData::PostfixUnaryExpression(data) => (
                "PostfixUnaryExpression",
                vec![
                    json!(["Operand", "node", self.node_ref(data.operand)]),
                    json!(["Operator", "kind", data.operator.raw()]),
                ],
            ),
            NodeData::YieldExpression(data) => (
                "YieldExpression",
                vec![
                    json!(["AsteriskToken", "node", self.node_ref(data.asterisk_token)]),
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                ],
            ),
            NodeData::ArrowFunction(data) => (
                "ArrowFunction",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                    json!(["AsteriskToken", "node", self.node_ref(data.asterisk_token)]),
                    json!(["Body", "node", self.node_ref(data.body)]),
                    json!([
                        "EqualsGreaterThanToken",
                        "node",
                        self.node_ref(data.equals_greater_than_token)
                    ]),
                ],
            ),
            NodeData::FunctionExpression(data) => (
                "FunctionExpression",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                    json!(["AsteriskToken", "node", self.node_ref(data.asterisk_token)]),
                    json!(["Body", "node", self.node_ref(data.body)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::AsExpression(data) => (
                "AsExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                ],
            ),
            NodeData::SatisfiesExpression(data) => (
                "SatisfiesExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                ],
            ),
            NodeData::ConditionalExpression(data) => (
                "ConditionalExpression",
                vec![
                    json!(["Condition", "node", self.node_ref(data.condition)]),
                    json!(["QuestionToken", "node", self.node_ref(data.question_token)]),
                    json!(["WhenTrue", "node", self.node_ref(data.when_true)]),
                    json!(["ColonToken", "node", self.node_ref(data.colon_token)]),
                    json!(["WhenFalse", "node", self.node_ref(data.when_false)]),
                ],
            ),
            NodeData::PropertyAccessExpression(data) => (
                "PropertyAccessExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!([
                        "QuestionDotToken",
                        "node",
                        self.node_ref(data.question_dot_token)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::ElementAccessExpression(data) => (
                "ElementAccessExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!([
                        "QuestionDotToken",
                        "node",
                        self.node_ref(data.question_dot_token)
                    ]),
                    json!([
                        "ArgumentExpression",
                        "node",
                        self.node_ref(data.argument_expression)
                    ]),
                ],
            ),
            NodeData::CallExpression(data) => (
                "CallExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!([
                        "QuestionDotToken",
                        "node",
                        self.node_ref(data.question_dot_token)
                    ]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments, false)
                    ]),
                    json!(["Arguments", "list", self.list_ref(data.arguments, false)]),
                ],
            ),
            NodeData::NewExpression(data) => (
                "NewExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments, false)
                    ]),
                    json!(["Arguments", "list", self.list_ref(data.arguments, false)]),
                ],
            ),
            NodeData::MetaProperty(data) => (
                "MetaProperty",
                vec![
                    json!(["KeywordToken", "kind", data.keyword_token.raw()]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::NonNullExpression(data) => (
                "NonNullExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::SpreadElement(data) => (
                "SpreadElement",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::TemplateExpression(data) => (
                "TemplateExpression",
                vec![
                    json!(["Head", "node", self.node_ref(data.head)]),
                    json!([
                        "TemplateSpans",
                        "list",
                        self.list_ref(data.template_spans, false)
                    ]),
                ],
            ),
            NodeData::TemplateSpan(data) => (
                "TemplateSpan",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["Literal", "node", self.node_ref(data.literal)]),
                ],
            ),
            NodeData::TaggedTemplateExpression(data) => (
                "TaggedTemplateExpression",
                vec![
                    json!(["Tag", "node", self.node_ref(data.tag)]),
                    json!([
                        "QuestionDotToken",
                        "node",
                        self.node_ref(data.question_dot_token)
                    ]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments, false)
                    ]),
                    json!(["Template", "node", self.node_ref(data.template)]),
                ],
            ),
            NodeData::ParenthesizedExpression(data) => (
                "ParenthesizedExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::ArrayLiteralExpression(data) => (
                "ArrayLiteralExpression",
                vec![
                    json!(["Elements", "list", self.list_ref(data.elements, false)]),
                    json!(["MultiLine", "bool", data.multi_line]),
                ],
            ),
            NodeData::ObjectLiteralExpression(data) => (
                "ObjectLiteralExpression",
                vec![
                    json!(["Properties", "list", self.list_ref(data.properties, false)]),
                    json!(["MultiLine", "bool", data.multi_line]),
                ],
            ),
            NodeData::SpreadAssignment(data) => (
                "SpreadAssignment",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::PropertyAssignment(data) => (
                "PropertyAssignment",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                ],
            ),
            NodeData::ShorthandPropertyAssignment(data) => (
                "ShorthandPropertyAssignment",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["PostfixToken", "node", self.node_ref(data.postfix_token)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["EqualsToken", "node", self.node_ref(data.equals_token)]),
                    json!([
                        "ObjectAssignmentInitializer",
                        "node",
                        self.node_ref(data.object_assignment_initializer)
                    ]),
                ],
            ),
            NodeData::DeleteExpression(data) => (
                "DeleteExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::TypeOfExpression(data) => (
                "TypeOfExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::VoidExpression(data) => (
                "VoidExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::AwaitExpression(data) => (
                "AwaitExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::TypeAssertion(data) => (
                "TypeAssertion",
                vec![
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                ],
            ),
            NodeData::KeywordTypeNode(data) => {
                let _ = data;
                ("KeywordTypeNode", vec![])
            }
            NodeData::UnionTypeNode(data) => (
                "UnionTypeNode",
                vec![json!(["Types", "list", self.list_ref(data.types, false)])],
            ),
            NodeData::IntersectionTypeNode(data) => (
                "IntersectionTypeNode",
                vec![json!(["Types", "list", self.list_ref(data.types, false)])],
            ),
            NodeData::ConditionalTypeNode(data) => (
                "ConditionalTypeNode",
                vec![
                    json!(["CheckType", "node", self.node_ref(data.check_type)]),
                    json!(["ExtendsType", "node", self.node_ref(data.extends_type)]),
                    json!(["TrueType", "node", self.node_ref(data.true_type)]),
                    json!(["FalseType", "node", self.node_ref(data.false_type)]),
                ],
            ),
            NodeData::TypeOperatorNode(data) => (
                "TypeOperatorNode",
                vec![
                    json!(["Operator", "kind", data.operator.raw()]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                ],
            ),
            NodeData::InferTypeNode(data) => (
                "InferTypeNode",
                vec![json!([
                    "TypeParameter",
                    "node",
                    self.node_ref(data.type_parameter)
                ])],
            ),
            NodeData::ArrayTypeNode(data) => (
                "ArrayTypeNode",
                vec![json!([
                    "ElementType",
                    "node",
                    self.node_ref(data.element_type)
                ])],
            ),
            NodeData::IndexedAccessTypeNode(data) => (
                "IndexedAccessTypeNode",
                vec![
                    json!(["ObjectType", "node", self.node_ref(data.object_type)]),
                    json!(["IndexType", "node", self.node_ref(data.index_type)]),
                ],
            ),
            NodeData::TypeReferenceNode(data) => (
                "TypeReferenceNode",
                vec![
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments, false)
                    ]),
                    json!(["TypeName", "node", self.node_ref(data.type_name)]),
                ],
            ),
            NodeData::ExpressionWithTypeArguments(data) => (
                "ExpressionWithTypeArguments",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments, false)
                    ]),
                ],
            ),
            NodeData::LiteralTypeNode(data) => (
                "LiteralTypeNode",
                vec![json!(["Literal", "node", self.node_ref(data.literal)])],
            ),
            NodeData::ThisTypeNode(data) => {
                let _ = data;
                ("ThisTypeNode", vec![])
            }
            NodeData::TypePredicateNode(data) => (
                "TypePredicateNode",
                vec![
                    json!([
                        "AssertsModifier",
                        "node",
                        self.node_ref(data.asserts_modifier)
                    ]),
                    json!(["ParameterName", "node", self.node_ref(data.parameter_name)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                ],
            ),
            NodeData::ImportAttribute(data) => (
                "ImportAttribute",
                vec![
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["Value", "node", self.node_ref(data.value)]),
                ],
            ),
            NodeData::ImportAttributes(data) => (
                "ImportAttributes",
                vec![
                    json!(["Token", "kind", data.token.raw()]),
                    json!(["Attributes", "list", self.list_ref(data.attributes, false)]),
                    json!(["MultiLine", "bool", data.multi_line]),
                ],
            ),
            NodeData::TypeQueryNode(data) => (
                "TypeQueryNode",
                vec![
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments, false)
                    ]),
                    json!(["ExprName", "node", self.node_ref(data.expr_name)]),
                ],
            ),
            NodeData::MappedTypeNode(data) => (
                "MappedTypeNode",
                vec![
                    json!(["ReadonlyToken", "node", self.node_ref(data.readonly_token)]),
                    json!(["TypeParameter", "node", self.node_ref(data.type_parameter)]),
                    json!(["NameType", "node", self.node_ref(data.name_type)]),
                    json!(["QuestionToken", "node", self.node_ref(data.question_token)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["Members", "list", self.list_ref(data.members, false)]),
                ],
            ),
            NodeData::TypeLiteralNode(data) => (
                "TypeLiteralNode",
                vec![json!([
                    "Members",
                    "list",
                    self.list_ref(data.members, false)
                ])],
            ),
            NodeData::TupleTypeNode(data) => (
                "TupleTypeNode",
                vec![json!([
                    "Elements",
                    "list",
                    self.list_ref(data.elements, false)
                ])],
            ),
            NodeData::NamedTupleMember(data) => (
                "NamedTupleMember",
                vec![
                    json!([
                        "DotDotDotToken",
                        "node",
                        self.node_ref(data.dot_dot_dot_token)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["QuestionToken", "node", self.node_ref(data.question_token)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                ],
            ),
            NodeData::OptionalTypeNode(data) => (
                "OptionalTypeNode",
                vec![json!(["Type", "node", self.node_ref(data.r#type)])],
            ),
            NodeData::RestTypeNode(data) => (
                "RestTypeNode",
                vec![json!(["Type", "node", self.node_ref(data.r#type)])],
            ),
            NodeData::ParenthesizedTypeNode(data) => (
                "ParenthesizedTypeNode",
                vec![json!(["Type", "node", self.node_ref(data.r#type)])],
            ),
            NodeData::FunctionTypeNode(data) => (
                "FunctionTypeNode",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                ],
            ),
            NodeData::ConstructorTypeNode(data) => (
                "ConstructorTypeNode",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                ],
            ),
            NodeData::TemplateHead(data) => (
                "TemplateHead",
                vec![
                    json!(["Text", "text", hex(data.text.as_bytes())]),
                    json!(["TokenFlags", "number", data.token_flags]),
                    json!(["RawText", "text", hex(data.raw_text.as_bytes())]),
                    json!(["TemplateFlags", "number", data.template_flags]),
                ],
            ),
            NodeData::TemplateMiddle(data) => (
                "TemplateMiddle",
                vec![
                    json!(["Text", "text", hex(data.text.as_bytes())]),
                    json!(["TokenFlags", "number", data.token_flags]),
                    json!(["RawText", "text", hex(data.raw_text.as_bytes())]),
                    json!(["TemplateFlags", "number", data.template_flags]),
                ],
            ),
            NodeData::TemplateTail(data) => (
                "TemplateTail",
                vec![
                    json!(["Text", "text", hex(data.text.as_bytes())]),
                    json!(["TokenFlags", "number", data.token_flags]),
                    json!(["RawText", "text", hex(data.raw_text.as_bytes())]),
                    json!(["TemplateFlags", "number", data.template_flags]),
                ],
            ),
            NodeData::TemplateLiteralTypeNode(data) => (
                "TemplateLiteralTypeNode",
                vec![
                    json!(["Head", "node", self.node_ref(data.head)]),
                    json!([
                        "TemplateSpans",
                        "list",
                        self.list_ref(data.template_spans, false)
                    ]),
                ],
            ),
            NodeData::TemplateLiteralTypeSpan(data) => (
                "TemplateLiteralTypeSpan",
                vec![
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["Literal", "node", self.node_ref(data.literal)]),
                ],
            ),
            NodeData::SyntheticExpression(data) => (
                "SyntheticExpression",
                vec![
                    json!(["Type", "opaque", Value::Null]),
                    json!(["IsSpread", "bool", data.is_spread]),
                    json!([
                        "TupleNameSource",
                        "node",
                        self.node_ref(data.tuple_name_source)
                    ]),
                ],
            ),
            NodeData::PartiallyEmittedExpression(data) => (
                "PartiallyEmittedExpression",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::JsxElement(data) => (
                "JsxElement",
                vec![
                    json!([
                        "OpeningElement",
                        "node",
                        self.node_ref(data.opening_element)
                    ]),
                    json!(["Children", "list", self.list_ref(data.children, false)]),
                    json!([
                        "ClosingElement",
                        "node",
                        self.node_ref(data.closing_element)
                    ]),
                ],
            ),
            NodeData::JsxAttributes(data) => (
                "JsxAttributes",
                vec![json!([
                    "Properties",
                    "list",
                    self.list_ref(data.properties, false)
                ])],
            ),
            NodeData::JsxNamespacedName(data) => (
                "JsxNamespacedName",
                vec![
                    json!(["Namespace", "node", self.node_ref(data.namespace)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::JsxOpeningElement(data) => (
                "JsxOpeningElement",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments, false)
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes)]),
                ],
            ),
            NodeData::JsxSelfClosingElement(data) => (
                "JsxSelfClosingElement",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments, false)
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes)]),
                ],
            ),
            NodeData::JsxFragment(data) => (
                "JsxFragment",
                vec![
                    json!([
                        "OpeningFragment",
                        "node",
                        self.node_ref(data.opening_fragment)
                    ]),
                    json!(["Children", "list", self.list_ref(data.children, false)]),
                    json!([
                        "ClosingFragment",
                        "node",
                        self.node_ref(data.closing_fragment)
                    ]),
                ],
            ),
            NodeData::JsxOpeningFragment(data) => {
                let _ = data;
                ("JsxOpeningFragment", vec![])
            }
            NodeData::JsxClosingFragment(data) => {
                let _ = data;
                ("JsxClosingFragment", vec![])
            }
            NodeData::JsxAttribute(data) => (
                "JsxAttribute",
                vec![
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["Initializer", "node", self.node_ref(data.initializer)]),
                ],
            ),
            NodeData::JsxSpreadAttribute(data) => (
                "JsxSpreadAttribute",
                vec![json!([
                    "Expression",
                    "node",
                    self.node_ref(data.expression)
                ])],
            ),
            NodeData::JsxClosingElement(data) => (
                "JsxClosingElement",
                vec![json!(["TagName", "node", self.node_ref(data.tag_name)])],
            ),
            NodeData::JsxExpression(data) => (
                "JsxExpression",
                vec![
                    json!([
                        "DotDotDotToken",
                        "node",
                        self.node_ref(data.dot_dot_dot_token)
                    ]),
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                ],
            ),
            NodeData::JsxText(data) => (
                "JsxText",
                vec![
                    json!(["Text", "text", hex(data.text.as_bytes())]),
                    json!(["TokenFlags", "number", data.token_flags]),
                    json!([
                        "ContainsOnlyTriviaWhiteSpaces",
                        "bool",
                        data.contains_only_trivia_white_spaces
                    ]),
                ],
            ),
            NodeData::SyntaxList(data) => (
                "SyntaxList",
                vec![json!([
                    "Children",
                    "nodes",
                    self.node_slice_ref(data.children)
                ])],
            ),
            NodeData::JSDoc(data) => (
                "JSDoc",
                vec![
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!(["Tags", "list", self.list_ref(data.tags, false)]),
                ],
            ),
            NodeData::JSDocTypeExpression(data) => (
                "JSDocTypeExpression",
                vec![json!(["Type", "node", self.node_ref(data.r#type)])],
            ),
            NodeData::JSDocNonNullableType(data) => (
                "JSDocNonNullableType",
                vec![json!(["Type", "node", self.node_ref(data.r#type)])],
            ),
            NodeData::JSDocNullableType(data) => (
                "JSDocNullableType",
                vec![json!(["Type", "node", self.node_ref(data.r#type)])],
            ),
            NodeData::JSDocAllType(data) => {
                let _ = data;
                ("JSDocAllType", vec![])
            }
            NodeData::JSDocVariadicType(data) => (
                "JSDocVariadicType",
                vec![json!(["Type", "node", self.node_ref(data.r#type)])],
            ),
            NodeData::JSDocOptionalType(data) => (
                "JSDocOptionalType",
                vec![json!(["Type", "node", self.node_ref(data.r#type)])],
            ),
            NodeData::JSDocTypeTag(data) => (
                "JSDocTypeTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression)
                    ]),
                ],
            ),
            NodeData::JSDocUnknownTag(data) => (
                "JSDocUnknownTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                ],
            ),
            NodeData::JSDocTemplateTag(data) => (
                "JSDocTemplateTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!(["Constraint", "node", self.node_ref(data.constraint)]),
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                ],
            ),
            NodeData::JSDocReturnTag(data) => (
                "JSDocReturnTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression)
                    ]),
                ],
            ),
            NodeData::JSDocPublicTag(data) => (
                "JSDocPublicTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                ],
            ),
            NodeData::JSDocPrivateTag(data) => (
                "JSDocPrivateTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                ],
            ),
            NodeData::JSDocProtectedTag(data) => (
                "JSDocProtectedTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                ],
            ),
            NodeData::JSDocReadonlyTag(data) => (
                "JSDocReadonlyTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                ],
            ),
            NodeData::JSDocOverrideTag(data) => (
                "JSDocOverrideTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                ],
            ),
            NodeData::JSDocDeprecatedTag(data) => (
                "JSDocDeprecatedTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                ],
            ),
            NodeData::JSDocSeeTag(data) => (
                "JSDocSeeTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!([
                        "NameExpression",
                        "node",
                        self.node_ref(data.name_expression)
                    ]),
                ],
            ),
            NodeData::JSDocImplementsTag(data) => (
                "JSDocImplementsTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!(["ClassName", "node", self.node_ref(data.class_name)]),
                ],
            ),
            NodeData::JSDocAugmentsTag(data) => (
                "JSDocAugmentsTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!(["ClassName", "node", self.node_ref(data.class_name)]),
                ],
            ),
            NodeData::JSDocSatisfiesTag(data) => (
                "JSDocSatisfiesTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression)
                    ]),
                ],
            ),
            NodeData::JSDocThrowsTag(data) => (
                "JSDocThrowsTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression)
                    ]),
                ],
            ),
            NodeData::JSDocThisTag(data) => (
                "JSDocThisTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression)
                    ]),
                ],
            ),
            NodeData::JSDocImportTag(data) => (
                "JSDocImportTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!(["ImportClause", "node", self.node_ref(data.import_clause)]),
                    json!([
                        "ModuleSpecifier",
                        "node",
                        self.node_ref(data.module_specifier)
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes)]),
                ],
            ),
            NodeData::JSDocCallbackTag(data) => (
                "JSDocCallbackTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::JSDocOverloadTag(data) => (
                "JSDocOverloadTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression)
                    ]),
                ],
            ),
            NodeData::JSDocTypedefTag(data) => (
                "JSDocTypedefTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::JSDocSignature(data) => (
                "JSDocSignature",
                vec![
                    json!([
                        "TypeParameters",
                        "list",
                        self.list_ref(data.type_parameters, false)
                    ]),
                    json!(["Parameters", "list", self.list_ref(data.parameters, false)]),
                    json!(["Type", "node", self.node_ref(data.r#type)]),
                    json!(["FullSignature", "node", self.node_ref(data.full_signature)]),
                ],
            ),
            NodeData::JSDocNameReference(data) => (
                "JSDocNameReference",
                vec![json!(["name", "node", self.node_ref(data.name)])],
            ),
            NodeData::SourceFile(data) => (
                "SourceFile",
                vec![
                    json!(["Statements", "list", self.list_ref(data.statements, false)]),
                    json!([
                        "EndOfFileToken",
                        "node",
                        self.node_ref(data.end_of_file_token)
                    ]),
                ],
            ),
            NodeData::ModuleDeclaration(data) => (
                "ModuleDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["AsteriskToken", "node", self.node_ref(data.asterisk_token)]),
                    json!(["Body", "node", self.node_ref(data.body)]),
                    json!(["Keyword", "kind", data.keyword.raw()]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["Attributes", "node", self.node_ref(data.attributes)]),
                ],
            ),
            NodeData::ImportEqualsDeclaration(data) => (
                "ImportEqualsDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["IsTypeOnly", "bool", data.is_type_only]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!([
                        "ModuleReference",
                        "node",
                        self.node_ref(data.module_reference)
                    ]),
                ],
            ),
            NodeData::ExportDeclaration(data) => (
                "ExportDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["IsTypeOnly", "bool", data.is_type_only]),
                    json!(["ExportClause", "node", self.node_ref(data.export_clause)]),
                    json!([
                        "ModuleSpecifier",
                        "node",
                        self.node_ref(data.module_specifier)
                    ]),
                    json!(["Attributes", "node", self.node_ref(data.attributes)]),
                ],
            ),
            NodeData::ImportTypeNode(data) => (
                "ImportTypeNode",
                vec![
                    json!([
                        "TypeArguments",
                        "list",
                        self.list_ref(data.type_arguments, false)
                    ]),
                    json!(["IsTypeOf", "bool", data.is_type_of]),
                    json!(["Argument", "node", self.node_ref(data.argument)]),
                    json!(["Attributes", "node", self.node_ref(data.attributes)]),
                    json!(["Qualifier", "node", self.node_ref(data.qualifier)]),
                ],
            ),
            NodeData::ImportClause(data) => (
                "ImportClause",
                vec![
                    json!(["PhaseModifier", "kind", data.phase_modifier.raw()]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["NamedBindings", "node", self.node_ref(data.named_bindings)]),
                ],
            ),
            NodeData::ImportSpecifier(data) => (
                "ImportSpecifier",
                vec![
                    json!(["IsTypeOnly", "bool", data.is_type_only]),
                    json!(["PropertyName", "node", self.node_ref(data.property_name)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::JSDocText(data) => (
                "JSDocText",
                vec![json!(["text", "strings", self.text_slice_ref(data.text)])],
            ),
            NodeData::JSDocLink(data) => (
                "JSDocLink",
                vec![
                    json!(["text", "strings", self.text_slice_ref(data.text)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::JSDocLinkPlain(data) => (
                "JSDocLinkPlain",
                vec![
                    json!(["text", "strings", self.text_slice_ref(data.text)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::JSDocLinkCode(data) => (
                "JSDocLinkCode",
                vec![
                    json!(["text", "strings", self.text_slice_ref(data.text)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                ],
            ),
            NodeData::TypeParameterDeclaration(data) => (
                "TypeParameterDeclaration",
                vec![
                    json!([
                        "modifiers",
                        "modifiers",
                        self.list_ref(data.modifiers, true)
                    ]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["Constraint", "node", self.node_ref(data.constraint)]),
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["DefaultType", "node", self.node_ref(data.default_type)]),
                ],
            ),
            NodeData::SyntheticReferenceExpression(data) => (
                "SyntheticReferenceExpression",
                vec![
                    json!(["Expression", "node", self.node_ref(data.expression)]),
                    json!(["ThisArg", "node", self.node_ref(data.this_arg)]),
                ],
            ),
            NodeData::JSDocTypeLiteral(data) => (
                "JSDocTypeLiteral",
                vec![
                    json!([
                        "JSDocPropertyTags",
                        "nodes",
                        self.node_slice_ref(data.js_doc_property_tags)
                    ]),
                    json!(["IsArrayType", "bool", data.is_array_type]),
                ],
            ),
            NodeData::JSDocParameterOrPropertyTag(data) => (
                "JSDocParameterOrPropertyTag",
                vec![
                    json!(["TagName", "node", self.node_ref(data.tag_name)]),
                    json!(["Comment", "list", self.list_ref(data.comment, false)]),
                    json!(["name", "node", self.node_ref(data.name)]),
                    json!(["IsBracketed", "bool", data.is_bracketed]),
                    json!([
                        "TypeExpression",
                        "node",
                        self.node_ref(data.type_expression)
                    ]),
                    json!(["IsNameFirst", "bool", data.is_name_first]),
                ],
            ),
        }
    }
}
