#!/usr/bin/env python3
"""Reproduce casing data from the clean pinned source and the oracle Go toolchain."""
import argparse
import ast
import hashlib
import json
import os
import pathlib
import re
import subprocess

CRATE = pathlib.Path(__file__).resolve().parents[1]
REPO = CRATE.parents[1]
GO_VERSION = "go1.27.1"


def command(*args, **kwargs):
    return subprocess.check_output(args, text=True, **kwargs).strip()


def rust_string(value):
    return '"' + ''.join(f'\\u{{{ord(ch):x}}}' for ch in value) + '"'


def generate():
    upstream = REPO / "upstream"
    pin = json.loads((REPO / "data/upstream.json").read_text())["pin"]
    if command("git", "-C", str(upstream), "rev-parse", "HEAD") != pin:
        raise ValueError("upstream HEAD differs from the recorded pin")
    if command("git", "-C", str(upstream), "status", "--porcelain", "--untracked-files=all"):
        raise ValueError("upstream must be clean")
    path = upstream / "tsc/internal/stringutil/js_case_generated.go"
    source = path.read_text()
    env = dict(os.environ, GOTOOLCHAIN="local", GO111MODULE="off")
    env.setdefault("GOCACHE", str(REPO / "target/go-build"))
    simple = json.loads(command("go", "run", str(CRATE / "tools/simple_lower.go"), env=env))
    if simple["go"] != GO_VERSION:
        raise ValueError(f"expected oracle toolchain {GO_VERSION}, got {simple['go']}")

    lines = [
        "// Generated by tools/generate_case_tables.py; do not edit.",
        f"// Upstream: {pin}",
        f"// js_case_generated.go SHA-256: {hashlib.sha256(path.read_bytes()).hexdigest()}",
        "// JS casing: Unicode 15.1.0 (including Final_Sigma and derived properties).",
        f"// LowerFirstChar: {simple['go']} unicode.ToLower, Unicode {simple['unicode']}.",
        "#![allow(clippy::unreadable_literal)] // Preserve upstream code-point notation.",
        "pub(crate) type Mapping = (i32, &'static str, &'static str, Option<&'static str>);",
        "#[rustfmt::skip]",
        "pub(crate) static CASE_MAPPINGS: &[Mapping] = &[",
    ]
    mapping_block = source.split("var specialCasingMappings = map[rune]specialCasingMapping{", 1)[1].split("\n}", 1)[0]
    keys = []
    for row in mapping_block.splitlines():
        if not row.strip():
            continue
        match = re.fullmatch(r'\s*(0x[0-9A-Fa-f]+):\s*\{lower: ("[^"\n]*"), upper: ("[^"\n]*"),(?: conditionalLower: ("[^"\n]*"),)? condition: (specialCasingCondition\w+)\},', row)
        if not match:
            raise ValueError(f"unrecognized mapping row: {row}")
        key, lower, upper, conditional, condition = match.groups()
        keys.append(int(key, 16))
        if condition not in {"specialCasingConditionNone", "specialCasingConditionFinalSigma"}:
            raise ValueError(f"unknown casing condition: {condition}")
        if (conditional is not None) != (condition == "specialCasingConditionFinalSigma"):
            raise ValueError("conditional mapping and condition disagree")
        conditional = "None" if conditional is None else f"Some({rust_string(ast.literal_eval(conditional))})"
        lines.append(f"    ({key}, {rust_string(ast.literal_eval(lower))}, {rust_string(ast.literal_eval(upper))}, {conditional}),")
    if not keys or keys != sorted(set(keys)):
        raise ValueError("mapping keys must be sorted and unique")
    lines.append("];")
    for go_name, rust_name in [("unicodeCasedRanges", "CASED_RANGES"), ("unicodeCaseIgnorableRanges", "CASE_IGNORABLE_RANGES")]:
        block = source.split(f"var {go_name} = &unicode.RangeTable{{", 1)[1].split("\n}", 1)[0]
        ranges = []
        for row in block.splitlines():
            if not row.strip() or row.strip() in {"R16: []unicode.Range16{", "R32: []unicode.Range32{", "},"}:
                continue
            if re.fullmatch(r'\s*LatinOffset: \d+,', row):
                continue  # An optimization index, not an additional property range.
            match = re.fullmatch(r'\s*\{(0x[0-9A-Fa-f]+), (0x[0-9A-Fa-f]+), (\d+)\},', row)
            if not match:
                raise ValueError(f"unrecognized property row: {row}")
            lo, hi, stride = (int(value, 0) for value in match.groups())
            if lo > hi or stride <= 0 or (ranges and ranges[-1][1] >= lo):
                raise ValueError("property ranges must be ordered, disjoint and nonempty")
            ranges.append((lo, hi, stride))
        if not ranges:
            raise ValueError("empty property table")
        lines += ["#[rustfmt::skip]", f"pub(crate) static {rust_name}: &[(i32, i32, i32)] = &["]
        lines += [f"    (0x{lo:X}, 0x{hi:X}, {stride})," for lo, hi, stride in ranges]
        lines.append("];")
    lines += ["#[rustfmt::skip]", "pub(crate) static SIMPLE_LOWER: &[(i32, i32)] = &["]
    rows = simple["lower"]
    if [r[0] for r in rows] != sorted({r[0] for r in rows}):
        raise ValueError("simple lowercase keys must be sorted and unique")
    lines += [f"    (0x{key:X}, 0x{value:X})," for key, value in rows]
    lines.append("];")
    return '\n'.join(lines) + '\n'


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = CRATE / "src/case_tables.rs"
    generated = generate()
    if args.check:
        if output.read_text() != generated:
            raise SystemExit("case tables differ; run tools/generate_case_tables.py")
    else:
        output.write_text(generated)
