#!/usr/bin/env python3
"""Generate the pinned Go strconv.IsPrint table used only for Go string quoting."""
import argparse
import json
import os
from pathlib import Path
import subprocess
import tomllib

CRATE = Path(__file__).resolve().parents[1]
REPO = CRATE.parents[1]


def generate():
    expected = tomllib.loads((REPO / "data/s04/toolchains.toml").read_text())["go"]
    env = dict(os.environ, GOTOOLCHAIN="local", GO111MODULE="off")
    result = json.loads(subprocess.check_output(
        ["go", "run", str(CRATE / "tools/go_print.go")], env=env, text=True))
    if result["go"] != expected:
        raise ValueError(f"expected oracle toolchain {expected}, got {result['go']}")
    ranges = result["ranges"]
    previous = -2
    for row in ranges:
        if (not isinstance(row, list) or len(row) != 2
                or any(type(value) is not int for value in row)
                or not 0 <= row[0] <= row[1] <= 0x10ffff
                or row[0] <= previous + 1):
            raise ValueError("print ranges must be ordered, disjoint and maximally joined")
        previous = row[1]
    if not ranges:
        raise ValueError("empty Go print table")
    lines = [
        "// Generated by tools/generate_go_quote.py; do not edit.",
        f"// Authority: {result['go']} strconv.IsPrint, Unicode {result['unicode']}.",
        "#![allow(clippy::unreadable_literal)] // Preserve Go rune notation.",
        "#[rustfmt::skip]",
        "pub(super) const PRINT_RANGES: &[(i32, i32)] = &[",
    ]
    lines.extend(f"    (0x{start:X}, 0x{end:X})," for start, end in ranges)
    return "\n".join([*lines, "];", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    output = CRATE / "src/go_print_generated.rs"
    if args.check:
        if output.read_text() != generated:
            raise SystemExit("Go quote table differs; run tools/generate_go_quote.py")
    else:
        output.write_text(generated)


if __name__ == "__main__":
    main()
