[package]
name = "ts_scanner"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ts_arena = { path = "../ts_arena", version = "0.1.0" }
stacker = "=0.1.25"
ts_ast = { path = "../ts_ast", version = "0.1.0" }
ts_core = { path = "../ts_core", version = "0.1.0" }
ts_diagnostics = { path = "../ts_diagnostics", version = "0.1.0" }
ts_jsnum = { path = "../ts_jsnum", version = "0.1.0" }
ts_jsstring = { path = "../ts_jsstring", version = "0.1.0" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
