//! List formats (`ListFormat` in `tsc/internal/printer/printer.go`): how a node
//! list is delimited, bracketed, spaced and broken across lines. Values are the
//! pinned source's bits, checked against the compiled Go package by the printer
//! observation fixture.

pub type ListFormat = u32;

pub const NONE: ListFormat = 0;

// Line separators
pub const SINGLE_LINE: ListFormat = 0;
pub const MULTI_LINE: ListFormat = 1 << 0;
pub const PRESERVE_LINES: ListFormat = 1 << 1;
pub const LINES_MASK: ListFormat = SINGLE_LINE | MULTI_LINE | PRESERVE_LINES;

// Delimiters
pub const NOT_DELIMITED: ListFormat = 0;
pub const BAR_DELIMITED: ListFormat = 1 << 2;
pub const AMPERSAND_DELIMITED: ListFormat = 1 << 3;
pub const COMMA_DELIMITED: ListFormat = 1 << 4;
pub const ASTERISK_DELIMITED: ListFormat = 1 << 5;
pub const DELIMITERS_MASK: ListFormat =
    BAR_DELIMITED | AMPERSAND_DELIMITED | COMMA_DELIMITED | ASTERISK_DELIMITED;

pub const ALLOW_TRAILING_COMMA: ListFormat = 1 << 6;

// Whitespace
pub const INDENTED: ListFormat = 1 << 7;
pub const SPACE_BETWEEN_BRACES: ListFormat = 1 << 8;
pub const SPACE_BETWEEN_SIBLINGS: ListFormat = 1 << 9;

// Brackets/Braces
pub const BRACES: ListFormat = 1 << 10;
pub const PARENTHESIS: ListFormat = 1 << 11;
pub const ANGLE_BRACKETS: ListFormat = 1 << 12;
pub const SQUARE_BRACKETS: ListFormat = 1 << 13;
pub const BRACKETS_MASK: ListFormat = BRACES | PARENTHESIS | ANGLE_BRACKETS | SQUARE_BRACKETS;

pub const OPTIONAL_IF_NIL: ListFormat = 1 << 14;
pub const OPTIONAL_IF_EMPTY: ListFormat = 1 << 15;
pub const OPTIONAL: ListFormat = OPTIONAL_IF_NIL | OPTIONAL_IF_EMPTY;

// Other
pub const PREFER_NEW_LINE: ListFormat = 1 << 16;
pub const NO_TRAILING_NEW_LINE: ListFormat = 1 << 17;
pub const NO_INTERVENING_COMMENTS: ListFormat = 1 << 18;
pub const NO_SPACE_IF_EMPTY: ListFormat = 1 << 19;
pub const SINGLE_ELEMENT: ListFormat = 1 << 20;
pub const SPACE_AFTER_LIST: ListFormat = 1 << 21;

// Precomputed formats
pub const MODIFIERS: ListFormat =
    SINGLE_LINE | SPACE_BETWEEN_SIBLINGS | NO_INTERVENING_COMMENTS | SPACE_AFTER_LIST;
pub const HERITAGE_CLAUSES: ListFormat = SINGLE_LINE | SPACE_BETWEEN_SIBLINGS;
pub const SINGLE_LINE_TYPE_LITERAL_MEMBERS: ListFormat =
    SINGLE_LINE | SPACE_BETWEEN_BRACES | SPACE_BETWEEN_SIBLINGS;
pub const MULTI_LINE_TYPE_LITERAL_MEMBERS: ListFormat = MULTI_LINE | INDENTED | OPTIONAL_IF_EMPTY;
pub const SINGLE_LINE_TUPLE_TYPE_ELEMENTS: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE;
pub const MULTI_LINE_TUPLE_TYPE_ELEMENTS: ListFormat =
    COMMA_DELIMITED | INDENTED | SPACE_BETWEEN_SIBLINGS | MULTI_LINE;
pub const UNION_TYPE_CONSTITUENTS: ListFormat =
    BAR_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE;
pub const INTERSECTION_TYPE_CONSTITUENTS: ListFormat =
    AMPERSAND_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE;
pub const OBJECT_BINDING_PATTERN_ELEMENTS: ListFormat = SINGLE_LINE
    | ALLOW_TRAILING_COMMA
    | SPACE_BETWEEN_BRACES
    | COMMA_DELIMITED
    | SPACE_BETWEEN_SIBLINGS
    | NO_SPACE_IF_EMPTY;
pub const ARRAY_BINDING_PATTERN_ELEMENTS: ListFormat = SINGLE_LINE
    | ALLOW_TRAILING_COMMA
    | COMMA_DELIMITED
    | SPACE_BETWEEN_SIBLINGS
    | NO_SPACE_IF_EMPTY;
pub const OBJECT_LITERAL_EXPRESSION_PROPERTIES: ListFormat = PRESERVE_LINES
    | COMMA_DELIMITED
    | SPACE_BETWEEN_SIBLINGS
    | SPACE_BETWEEN_BRACES
    | INDENTED
    | BRACES
    | NO_SPACE_IF_EMPTY;
pub const IMPORT_ATTRIBUTES: ListFormat = PRESERVE_LINES
    | COMMA_DELIMITED
    | SPACE_BETWEEN_SIBLINGS
    | SPACE_BETWEEN_BRACES
    | INDENTED
    | BRACES
    | NO_SPACE_IF_EMPTY;
pub const ARRAY_LITERAL_EXPRESSION_ELEMENTS: ListFormat = PRESERVE_LINES
    | COMMA_DELIMITED
    | SPACE_BETWEEN_SIBLINGS
    | ALLOW_TRAILING_COMMA
    | INDENTED
    | SQUARE_BRACKETS;
pub const COMMA_LIST_ELEMENTS: ListFormat = COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE;
pub const CALL_EXPRESSION_ARGUMENTS: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE | PARENTHESIS;
pub const NEW_EXPRESSION_ARGUMENTS: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE | PARENTHESIS | OPTIONAL_IF_NIL;
pub const TEMPLATE_EXPRESSION_SPANS: ListFormat = SINGLE_LINE | NO_INTERVENING_COMMENTS;
pub const SINGLE_LINE_BLOCK_STATEMENTS: ListFormat =
    SPACE_BETWEEN_BRACES | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE;
pub const MULTI_LINE_BLOCK_STATEMENTS: ListFormat = INDENTED | MULTI_LINE;
pub const VARIABLE_DECLARATION_LIST: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE;
pub const SINGLE_LINE_FUNCTION_BODY_STATEMENTS: ListFormat =
    SINGLE_LINE | SPACE_BETWEEN_SIBLINGS | SPACE_BETWEEN_BRACES;
pub const MULTI_LINE_FUNCTION_BODY_STATEMENTS: ListFormat = MULTI_LINE;
pub const CLASS_HERITAGE_CLAUSES: ListFormat = SINGLE_LINE;
pub const CLASS_MEMBERS: ListFormat = INDENTED | MULTI_LINE;
pub const INTERFACE_MEMBERS: ListFormat = INDENTED | MULTI_LINE;
pub const ENUM_MEMBERS: ListFormat = COMMA_DELIMITED | INDENTED | MULTI_LINE;
pub const CASE_BLOCK_CLAUSES: ListFormat = INDENTED | MULTI_LINE;
pub const NAMED_IMPORTS_OR_EXPORTS_ELEMENTS: ListFormat = COMMA_DELIMITED
    | SPACE_BETWEEN_SIBLINGS
    | ALLOW_TRAILING_COMMA
    | SINGLE_LINE
    | SPACE_BETWEEN_BRACES
    | NO_SPACE_IF_EMPTY;
pub const JSX_ELEMENT_OR_FRAGMENT_CHILDREN: ListFormat = SINGLE_LINE | NO_INTERVENING_COMMENTS;
pub const JSX_ELEMENT_ATTRIBUTES: ListFormat =
    SINGLE_LINE | SPACE_BETWEEN_SIBLINGS | NO_INTERVENING_COMMENTS;
pub const CASE_OR_DEFAULT_CLAUSE_STATEMENTS: ListFormat =
    INDENTED | MULTI_LINE | NO_TRAILING_NEW_LINE | OPTIONAL_IF_EMPTY;
pub const HERITAGE_CLAUSE_TYPES: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE;
pub const SOURCE_FILE_STATEMENTS: ListFormat = MULTI_LINE | NO_TRAILING_NEW_LINE;
pub const DECORATORS: ListFormat = MULTI_LINE | OPTIONAL | SPACE_AFTER_LIST;
pub const TYPE_ARGUMENTS: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE | ANGLE_BRACKETS | OPTIONAL;
pub const TYPE_PARAMETERS: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE | ANGLE_BRACKETS | OPTIONAL;
pub const PARAMETERS: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE | PARENTHESIS;
pub const SINGLE_ARROW_PARAMETER: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE;
pub const INDEX_SIGNATURE_PARAMETERS: ListFormat =
    COMMA_DELIMITED | SPACE_BETWEEN_SIBLINGS | SINGLE_LINE | INDENTED | SQUARE_BRACKETS;
pub const JSDOC_COMMENT: ListFormat = MULTI_LINE | ASTERISK_DELIMITED;
pub const IMPORT_CLAUSE_ENTRIES: ListFormat = IMPORT_ATTRIBUTES;
