#!/usr/bin/env python3
"""Generate access-only payload observers from the frozen source schema, never behavior."""
import argparse
import json
from pathlib import Path
import re
import subprocess
import tomllib

ROOT = Path(__file__).resolve().parents[3]


def snake(name):
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).lower()
    return "r#type" if name == "type" else name


def category(typ):
    while typ["kind"] == "alias":
        typ = typ["resolved"]
    kind = typ["kind"]
    if kind == "union":
        kind = typ["baseKind"]
    if kind in ("node", "kind"):
        return kind
    if kind == "primitive":
        return {"string": "text", "bool": "bool", "TokenFlags": "number", "any": "opaque"}[typ["name"]]
    if kind == "list":
        if typ["list"] == "raw":
            return "strings" if category(typ["element"]) == "text" else "nodes"
        return "modifiers" if typ["list"] == "ModifierList" else "list"
    raise ValueError(f"unhandled source schema type: {typ}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.loads((ROOT / "data/s03/schema/ast.json").read_bytes())
    edition = tomllib.loads((ROOT / "Cargo.toml").read_text())["workspace"]["package"]["edition"]
    go = ['// Generated by tools/s07/binder/generate_syntax.py; access-only observer.', 'package ast', '',
          'type S07SyntaxField struct { Name, Kind string; Value any }',
          'func S07SyntaxFields(node *Node) (string, []S07SyntaxField) {',
          ' switch data := node.data.(type) {']
    rust = ['// Generated by tools/s07/binder/generate_syntax.py; access-only observer.',
            'use super::{json, Graph, Value, NodeDataRead, hex};', 'impl Graph<\'_> {',
            ' pub(super) fn syntax_fields(&mut self, node: &(impl ts_ast::NodeAccess + ?Sized)) -> (&\'static str, Vec<Value>) {',
            '  match node.data() {']
    seen = 0
    for node in schema['nodes']:
        fields = [f for f in node['fields'] if not f['goOnly'] and not f['noGo'] and f['name'] != 'Flags']
        go.append(f" case *{node['name']}:")
        if not fields:
            go.append('  _ = data')
        go.append(f"  return \"{node['name']}\", []S07SyntaxField{{")
        rust.append(f"   NodeDataRead::{node['name']}(data) => {{")
        if not fields:
            rust.append('    let _ = data;')
        rust.append(f"    (\"{node['name']}\", vec![")
        for field in fields:
            name = field['name']; cat = category(field['type']); member = 'data.' + snake(name) + '()'
            go.append(f'   {{"{name}", "{cat}", data.{name}}},')
            value = {'node': f'self.node_ref({member})', 'list': f'self.list_ref({member}, false)',
                     'modifiers': f'self.list_ref({member}, true)', 'nodes': f'self.node_slice_ref({member})',
                     'strings': f'self.text_slice_ref({member})', 'kind': f'{member}.raw()',
                     'text': f'hex({member})', 'bool': member, 'number': member,
                     'opaque': 'Value::Null'}[cat]
            rust.append(f'     json!(["{name}", "{cat}", {value}]),')
            seen += 1
        go.extend(['  }'])
        rust.extend(['    ])', '   }'])
    go.extend([' default: panic("S07 observer: unsupported syntax payload")', ' }', '}'])
    rust.extend(['  }', ' }', '}'])
    for path, lines in [(ROOT/'scripts/s07_oracle/syntax_bridge.go', go),
                        (ROOT/'crates/ts_binder/examples/support/syntax_generated.rs', rust)]:
        raw = ('\n'.join(lines)+'\n').encode()
        formatter = ['gofmt'] if path.suffix == '.go' else ['rustfmt', '--edition', edition, '--config-path', str(ROOT/'rustfmt.toml'), '--emit', 'stdout']
        raw = subprocess.run(formatter, input=raw, check=True, stdout=subprocess.PIPE).stdout
        if args.check:
            if path.read_bytes() != raw:
                raise ValueError(f'generated S07 observer drift: {path}')
        else:
            path.write_bytes(raw)
    print(f'{len(schema["nodes"])} source payloads, {seen} non-header syntax fields')


if __name__ == '__main__':
    main()
