package ast

// Calls the pinned Node methods directly. Constructor inputs and the operation
// matrix are frozen here; no accessor algorithm is transcribed into this oracle.
import (
	"fmt"
	"github.com/microsoft/TypeScript/tsc/internal/core"
	"os"
	"strings"
	"testing"
)

func TestS06Accessors(t *testing.T) {
	out, err := os.Create(os.Getenv("S06_ACCESSORS_OUTPUT"))
	if err != nil {
		t.Fatal(err)
	}
	defer out.Close()
	f := NewNodeFactory(NodeFactoryHooks{})
	a := f.NewIdentifier("a")
	b := f.NewIdentifier("b")
	q := f.NewToken(KindQuestionToken)
	e := f.NewToken(KindExclamationToken)
	mods := f.NewModifierList([]*Node{f.NewToken(KindPublicKeyword)})
	ids := map[*Node]string{nil: "nil", a: "a", b: "b", q: "q", e: "e"}
	id := func(n *Node) string {
		if s, ok := ids[n]; ok {
			return s
		}
		panic("unregistered fixture child")
	}
	nodes := func(ns []*Node) string {
		parts := make([]string, len(ns))
		for i, n := range ns {
			parts[i] = id(n)
		}
		return strings.Join(parts, ",")
	}
	list := func(ns *NodeList) string {
		if ns == nil {
			return "nil"
		}
		return "list:" + nodes(ns.Nodes)
	}
	observe := func(name string, action func() string) {
		outcome := ""
		func() {
			defer func() {
				if p := recover(); p != nil {
					message := fmt.Sprint(p)
					if message == "runtime error: invalid memory address or nil pointer dereference" {
						outcome = "panic:nil"
					} else if strings.HasPrefix(message, "interface conversion: ") {
						outcome = "panic:payload:" + message
					} else {
						outcome = "panic:message:" + message
					}
				}
			}()
			outcome = "value:" + action()
		}()
		fmt.Fprintf(out, "%s\t%s\n", name, outcome)
	}
	check := func(name string, n *Node) {

		observe(name+"/Name", func() string { return id(n.Name()) })
		observe(name+"/Expression", func() string { return id(n.Expression()) })
		observe(name+"/Type", func() string { return id(n.Type()) })
		observe(name+"/Initializer", func() string { return id(n.Initializer()) })
		observe(name+"/TagName", func() string { return id(n.TagName()) })
		observe(name+"/PropertyName", func() string { return id(n.PropertyName()) })
		observe(name+"/Label", func() string { return id(n.Label()) })
		observe(name+"/Attributes", func() string { return id(n.Attributes()) })
		observe(name+"/ModuleSpecifier", func() string { return id(n.ModuleSpecifier()) })
		observe(name+"/ImportClause", func() string { return id(n.ImportClause()) })
		observe(name+"/Statement", func() string { return id(n.Statement()) })
		observe(name+"/PostfixToken", func() string { return id(n.PostfixToken()) })
		observe(name+"/QuestionDotToken", func() string { return id(n.QuestionDotToken()) })
		observe(name+"/TypeExpression", func() string { return id(n.TypeExpression()) })
		observe(name+"/ClassName", func() string { return id(n.ClassName()) })
		observe(name+"/Body", func() string { return id(n.Body()) })
		observe(name+"/PropertyNameOrName", func() string { return id(n.PropertyNameOrName()) })
		observe(name+"/ArgumentList", func() string { return list(n.ArgumentList()) })
		observe(name+"/TypeArgumentList", func() string { return list(n.TypeArgumentList()) })
		observe(name+"/TypeParameterList", func() string { return list(n.TypeParameterList()) })
		observe(name+"/ParameterList", func() string { return list(n.ParameterList()) })
		observe(name+"/MemberList", func() string { return list(n.MemberList()) })
		observe(name+"/StatementList", func() string { return list(n.StatementList()) })
		observe(name+"/CommentList", func() string { return list(n.CommentList()) })
		observe(name+"/Children", func() string { return list(n.Children()) })
		observe(name+"/PropertyList", func() string { return list(n.PropertyList()) })
		observe(name+"/ElementList", func() string { return list(n.ElementList()) })
		observe(name+"/Modifiers", func() string {
			m := n.Modifiers()
			if m == nil {
				return "nil"
			}
			return "list:" + nodes(m.Nodes)
		})
		observe(name+"/Arguments", func() string { return nodes(n.Arguments()) })
		observe(name+"/TypeArguments", func() string { return nodes(n.TypeArguments()) })
		observe(name+"/TypeParameters", func() string { return nodes(n.TypeParameters()) })
		observe(name+"/Parameters", func() string { return nodes(n.Parameters()) })
		observe(name+"/Members", func() string { return nodes(n.Members()) })
		observe(name+"/Statements", func() string { return nodes(n.Statements()) })
		observe(name+"/ModifierNodes", func() string { return nodes(n.ModifierNodes()) })
		observe(name+"/Comments", func() string { return nodes(n.Comments()) })
		observe(name+"/Properties", func() string { return nodes(n.Properties()) })
		observe(name+"/Elements", func() string { return nodes(n.Elements()) })
		observe(name+"/QuestionToken", func() string { return id(n.QuestionToken()) })
		observe(name+"/ModifierFlags", func() string { return fmt.Sprint(n.ModifierFlags()) })
		observe(name+"/KindString", func() string { return n.KindString() })
		observe(name+"/KindValue", func() string { return fmt.Sprint(n.KindValue()) })
		observe(name+"/CanHaveStatements", func() string { return fmt.Sprint(n.CanHaveStatements()) })
		observe(name+"/IsTypeOnly", func() string { return fmt.Sprint(n.IsTypeOnly()) })
		observe(name+"/Text", func() string { return fmt.Sprintf("%x", n.Text()) })
		observe(name+"/RawText", func() string { return fmt.Sprintf("%x", n.RawText()) })
		observe(name+"/SetExpression", func() string { n.AsMutable().SetExpression(b); return id(n.Expression()) })
		observe(name+"/SetType", func() string { n.AsMutable().SetType(b); return id(n.Type()) })
		observe(name+"/SetInitializer", func() string { n.AsMutable().SetInitializer(b); return id(n.Initializer()) })
		observe(name+"/SetModifiers", func() string { n.AsMutable().SetModifiers(mods); return fmt.Sprint(n.ModifierFlags()) })
	}
	for kind := Kind(-1); kind <= KindCount; kind++ {
		check(fmt.Sprintf("token/%d", kind), f.NewToken(kind))
	}
	for _, kind := range []Kind{-32768, 32767} {
		check(fmt.Sprintf("token/%d", kind), f.NewToken(kind))
	}
	check("constructor/NewToken", f.NewToken(KindUnknown))
	check("constructor/NewIdentifier", f.NewIdentifier("x\xff"))
	check("constructor/NewPrivateIdentifier", f.NewPrivateIdentifier("x\xff"))
	check("constructor/NewQualifiedName", f.NewQualifiedName(nil, nil))
	check("constructor/NewComputedPropertyName", f.NewComputedPropertyName(nil))
	check("constructor/NewDecorator", f.NewDecorator(nil))
	check("constructor/NewEmptyStatement", f.NewEmptyStatement())
	check("constructor/NewIfStatement", f.NewIfStatement(nil, nil, nil))
	check("constructor/NewDoStatement", f.NewDoStatement(nil, nil))
	check("constructor/NewWhileStatement", f.NewWhileStatement(nil, nil))
	check("constructor/NewForStatement", f.NewForStatement(nil, nil, nil, nil))
	check("constructor/NewForInOrOfStatement", f.NewForInOrOfStatement(KindUnknown, nil, nil, nil, nil))
	check("constructor/NewBreakStatement", f.NewBreakStatement(nil))
	check("constructor/NewContinueStatement", f.NewContinueStatement(nil))
	check("constructor/NewReturnStatement", f.NewReturnStatement(nil))
	check("constructor/NewWithStatement", f.NewWithStatement(nil, nil))
	check("constructor/NewSwitchStatement", f.NewSwitchStatement(nil, nil))
	check("constructor/NewCaseBlock", f.NewCaseBlock(nil))
	check("constructor/NewCaseOrDefaultClause", f.NewCaseOrDefaultClause(KindUnknown, nil, nil))
	check("constructor/NewThrowStatement", f.NewThrowStatement(nil))
	check("constructor/NewTryStatement", f.NewTryStatement(nil, nil, nil))
	check("constructor/NewCatchClause", f.NewCatchClause(nil, nil))
	check("constructor/NewDebuggerStatement", f.NewDebuggerStatement())
	check("constructor/NewLabeledStatement", f.NewLabeledStatement(nil, nil))
	check("constructor/NewExpressionStatement", f.NewExpressionStatement(nil))
	check("constructor/NewBlock", f.NewBlock(nil, false))
	check("constructor/NewVariableStatement", f.NewVariableStatement(nil, nil))
	check("constructor/NewVariableDeclaration", f.NewVariableDeclaration(nil, nil, nil, nil))
	check("constructor/NewVariableDeclarationList", f.NewVariableDeclarationList(nil, 0))
	check("constructor/NewBindingPattern", f.NewBindingPattern(KindUnknown, nil))
	check("constructor/NewParameterDeclaration", f.NewParameterDeclaration(nil, nil, nil, nil, nil, nil))
	check("constructor/NewBindingElement", f.NewBindingElement(nil, nil, nil, nil))
	check("constructor/NewMissingDeclaration", f.NewMissingDeclaration(nil))
	check("constructor/NewFunctionDeclaration", f.NewFunctionDeclaration(nil, nil, nil, nil, nil, nil, nil, nil))
	check("constructor/NewClassDeclaration", f.NewClassDeclaration(nil, nil, nil, nil, nil))
	check("constructor/NewClassExpression", f.NewClassExpression(nil, nil, nil, nil, nil))
	check("constructor/NewHeritageClause", f.NewHeritageClause(KindUnknown, nil))
	check("constructor/NewInterfaceDeclaration", f.NewInterfaceDeclaration(nil, nil, nil, nil, nil))
	check("constructor/NewTypeAliasDeclaration", f.NewTypeAliasDeclaration(nil, nil, nil, nil))
	check("constructor/NewJSTypeAliasDeclaration", f.NewJSTypeAliasDeclaration(nil, nil, nil, nil))
	check("constructor/NewEnumMember", f.NewEnumMember(nil, nil))
	check("constructor/NewEnumDeclaration", f.NewEnumDeclaration(nil, nil, nil))
	check("constructor/NewModuleBlock", f.NewModuleBlock(nil))
	check("constructor/NewNotEmittedStatement", f.NewNotEmittedStatement())
	check("constructor/NewNotEmittedTypeElement", f.NewNotEmittedTypeElement())
	check("constructor/NewImportDeclaration", f.NewImportDeclaration(nil, nil, nil, nil))
	check("constructor/NewJSImportDeclaration", f.NewJSImportDeclaration(nil, nil, nil, nil))
	check("constructor/NewExternalModuleReference", f.NewExternalModuleReference(nil))
	check("constructor/NewNamespaceImport", f.NewNamespaceImport(nil))
	check("constructor/NewNamedImports", f.NewNamedImports(nil))
	check("constructor/NewExportAssignment", f.NewExportAssignment(nil, false, nil, nil))
	check("constructor/NewNamespaceExportDeclaration", f.NewNamespaceExportDeclaration(nil, nil))
	check("constructor/NewNamespaceExport", f.NewNamespaceExport(nil))
	check("constructor/NewNamedExports", f.NewNamedExports(nil))
	check("constructor/NewExportSpecifier", f.NewExportSpecifier(false, nil, nil))
	check("constructor/NewCallSignatureDeclaration", f.NewCallSignatureDeclaration(nil, nil, nil))
	check("constructor/NewConstructSignatureDeclaration", f.NewConstructSignatureDeclaration(nil, nil, nil))
	check("constructor/NewConstructorDeclaration", f.NewConstructorDeclaration(nil, nil, nil, nil, nil, nil))
	check("constructor/NewGetAccessorDeclaration", f.NewGetAccessorDeclaration(nil, nil, nil, nil, nil, nil, nil))
	check("constructor/NewSetAccessorDeclaration", f.NewSetAccessorDeclaration(nil, nil, nil, nil, nil, nil, nil))
	check("constructor/NewIndexSignatureDeclaration", f.NewIndexSignatureDeclaration(nil, nil, nil))
	check("constructor/NewMethodSignatureDeclaration", f.NewMethodSignatureDeclaration(nil, nil, nil, nil, nil, nil))
	check("constructor/NewMethodDeclaration", f.NewMethodDeclaration(nil, nil, nil, nil, nil, nil, nil, nil, nil))
	check("constructor/NewPropertySignatureDeclaration", f.NewPropertySignatureDeclaration(nil, nil, nil, nil, nil))
	check("constructor/NewPropertyDeclaration", f.NewPropertyDeclaration(nil, nil, nil, nil, nil))
	check("constructor/NewSemicolonClassElement", f.NewSemicolonClassElement())
	check("constructor/NewClassStaticBlockDeclaration", f.NewClassStaticBlockDeclaration(nil, nil))
	check("constructor/NewOmittedExpression", f.NewOmittedExpression())
	check("constructor/NewKeywordExpression", f.NewKeywordExpression(KindUnknown))
	check("constructor/NewStringLiteral", f.NewStringLiteral("x\xff", 0))
	check("constructor/NewNumericLiteral", f.NewNumericLiteral("x\xff", 0))
	check("constructor/NewBigIntLiteral", f.NewBigIntLiteral("x\xff", 0))
	check("constructor/NewRegularExpressionLiteral", f.NewRegularExpressionLiteral("x\xff", 0))
	check("constructor/NewNoSubstitutionTemplateLiteral", f.NewNoSubstitutionTemplateLiteral("x\xff", 0))
	check("constructor/NewBinaryExpression", f.NewBinaryExpression(nil, nil, nil, nil, nil))
	check("constructor/NewPrefixUnaryExpression", f.NewPrefixUnaryExpression(KindUnknown, nil))
	check("constructor/NewPostfixUnaryExpression", f.NewPostfixUnaryExpression(nil, KindUnknown))
	check("constructor/NewYieldExpression", f.NewYieldExpression(nil, nil))
	check("constructor/NewArrowFunction", f.NewArrowFunction(nil, nil, nil, nil, nil, nil, nil))
	check("constructor/NewFunctionExpression", f.NewFunctionExpression(nil, nil, nil, nil, nil, nil, nil, nil))
	check("constructor/NewAsExpression", f.NewAsExpression(nil, nil))
	check("constructor/NewSatisfiesExpression", f.NewSatisfiesExpression(nil, nil))
	check("constructor/NewConditionalExpression", f.NewConditionalExpression(nil, nil, nil, nil, nil))
	check("constructor/NewPropertyAccessExpression", f.NewPropertyAccessExpression(nil, nil, nil, 0))
	check("constructor/NewElementAccessExpression", f.NewElementAccessExpression(nil, nil, nil, 0))
	check("constructor/NewCallExpression", f.NewCallExpression(nil, nil, nil, nil, 0))
	check("constructor/NewNewExpression", f.NewNewExpression(nil, nil, nil))
	check("constructor/NewMetaProperty", f.NewMetaProperty(KindUnknown, nil))
	check("constructor/NewNonNullExpression", f.NewNonNullExpression(nil, 0))
	check("constructor/NewSpreadElement", f.NewSpreadElement(nil))
	check("constructor/NewTemplateExpression", f.NewTemplateExpression(nil, nil))
	check("constructor/NewTemplateSpan", f.NewTemplateSpan(nil, nil))
	check("constructor/NewTaggedTemplateExpression", f.NewTaggedTemplateExpression(nil, nil, nil, nil, 0))
	check("constructor/NewParenthesizedExpression", f.NewParenthesizedExpression(nil))
	check("constructor/NewArrayLiteralExpression", f.NewArrayLiteralExpression(nil, false))
	check("constructor/NewObjectLiteralExpression", f.NewObjectLiteralExpression(nil, false))
	check("constructor/NewSpreadAssignment", f.NewSpreadAssignment(nil))
	check("constructor/NewPropertyAssignment", f.NewPropertyAssignment(nil, nil, nil, nil, nil))
	check("constructor/NewShorthandPropertyAssignment", f.NewShorthandPropertyAssignment(nil, nil, nil, nil, nil, nil))
	check("constructor/NewDeleteExpression", f.NewDeleteExpression(nil))
	check("constructor/NewTypeOfExpression", f.NewTypeOfExpression(nil))
	check("constructor/NewVoidExpression", f.NewVoidExpression(nil))
	check("constructor/NewAwaitExpression", f.NewAwaitExpression(nil))
	check("constructor/NewTypeAssertion", f.NewTypeAssertion(nil, nil))
	check("constructor/NewKeywordTypeNode", f.NewKeywordTypeNode(KindUnknown))
	check("constructor/NewUnionTypeNode", f.NewUnionTypeNode(nil))
	check("constructor/NewIntersectionTypeNode", f.NewIntersectionTypeNode(nil))
	check("constructor/NewConditionalTypeNode", f.NewConditionalTypeNode(nil, nil, nil, nil))
	check("constructor/NewTypeOperatorNode", f.NewTypeOperatorNode(KindUnknown, nil))
	check("constructor/NewInferTypeNode", f.NewInferTypeNode(nil))
	check("constructor/NewArrayTypeNode", f.NewArrayTypeNode(nil))
	check("constructor/NewIndexedAccessTypeNode", f.NewIndexedAccessTypeNode(nil, nil))
	check("constructor/NewTypeReferenceNode", f.NewTypeReferenceNode(nil, nil))
	check("constructor/NewExpressionWithTypeArguments", f.NewExpressionWithTypeArguments(nil, nil))
	check("constructor/NewLiteralTypeNode", f.NewLiteralTypeNode(nil))
	check("constructor/NewThisTypeNode", f.NewThisTypeNode())
	check("constructor/NewTypePredicateNode", f.NewTypePredicateNode(nil, nil, nil))
	check("constructor/NewImportAttribute", f.NewImportAttribute(nil, nil))
	check("constructor/NewImportAttributes", f.NewImportAttributes(KindUnknown, nil, false))
	check("constructor/NewTypeQueryNode", f.NewTypeQueryNode(nil, nil))
	check("constructor/NewMappedTypeNode", f.NewMappedTypeNode(nil, nil, nil, nil, nil, nil))
	check("constructor/NewTypeLiteralNode", f.NewTypeLiteralNode(nil))
	check("constructor/NewTupleTypeNode", f.NewTupleTypeNode(nil))
	check("constructor/NewNamedTupleMember", f.NewNamedTupleMember(nil, nil, nil, nil))
	check("constructor/NewOptionalTypeNode", f.NewOptionalTypeNode(nil))
	check("constructor/NewRestTypeNode", f.NewRestTypeNode(nil))
	check("constructor/NewParenthesizedTypeNode", f.NewParenthesizedTypeNode(nil))
	check("constructor/NewFunctionTypeNode", f.NewFunctionTypeNode(nil, nil, nil))
	check("constructor/NewConstructorTypeNode", f.NewConstructorTypeNode(nil, nil, nil, nil))
	check("constructor/NewTemplateHead", f.NewTemplateHead("x\xff", "x\xff", 0))
	check("constructor/NewTemplateMiddle", f.NewTemplateMiddle("x\xff", "x\xff", 0))
	check("constructor/NewTemplateTail", f.NewTemplateTail("x\xff", "x\xff", 0))
	check("constructor/NewTemplateLiteralTypeNode", f.NewTemplateLiteralTypeNode(nil, nil))
	check("constructor/NewTemplateLiteralTypeSpan", f.NewTemplateLiteralTypeSpan(nil, nil))
	check("constructor/NewPartiallyEmittedExpression", f.NewPartiallyEmittedExpression(nil))
	check("constructor/NewJsxElement", f.NewJsxElement(nil, nil, nil))
	check("constructor/NewJsxAttributes", f.NewJsxAttributes(nil))
	check("constructor/NewJsxNamespacedName", f.NewJsxNamespacedName(nil, nil))
	check("constructor/NewJsxOpeningElement", f.NewJsxOpeningElement(nil, nil, nil))
	check("constructor/NewJsxSelfClosingElement", f.NewJsxSelfClosingElement(nil, nil, nil))
	check("constructor/NewJsxFragment", f.NewJsxFragment(nil, nil, nil))
	check("constructor/NewJsxOpeningFragment", f.NewJsxOpeningFragment())
	check("constructor/NewJsxClosingFragment", f.NewJsxClosingFragment())
	check("constructor/NewJsxAttribute", f.NewJsxAttribute(nil, nil))
	check("constructor/NewJsxSpreadAttribute", f.NewJsxSpreadAttribute(nil))
	check("constructor/NewJsxClosingElement", f.NewJsxClosingElement(nil))
	check("constructor/NewJsxExpression", f.NewJsxExpression(nil, nil))
	check("constructor/NewJsxText", f.NewJsxText("x\xff", false))
	check("constructor/NewSyntaxList", f.NewSyntaxList(nil))
	check("constructor/NewJSDoc", f.NewJSDoc(nil, nil))
	check("constructor/NewJSDocTypeExpression", f.NewJSDocTypeExpression(nil))
	check("constructor/NewJSDocNonNullableType", f.NewJSDocNonNullableType(nil))
	check("constructor/NewJSDocNullableType", f.NewJSDocNullableType(nil))
	check("constructor/NewJSDocAllType", f.NewJSDocAllType())
	check("constructor/NewJSDocVariadicType", f.NewJSDocVariadicType(nil))
	check("constructor/NewJSDocOptionalType", f.NewJSDocOptionalType(nil))
	check("constructor/NewJSDocTypeTag", f.NewJSDocTypeTag(nil, nil, nil))
	check("constructor/NewJSDocUnknownTag", f.NewJSDocUnknownTag(nil, nil))
	check("constructor/NewJSDocTemplateTag", f.NewJSDocTemplateTag(nil, nil, nil, nil))
	check("constructor/NewJSDocReturnTag", f.NewJSDocReturnTag(nil, nil, nil))
	check("constructor/NewJSDocPublicTag", f.NewJSDocPublicTag(nil, nil))
	check("constructor/NewJSDocPrivateTag", f.NewJSDocPrivateTag(nil, nil))
	check("constructor/NewJSDocProtectedTag", f.NewJSDocProtectedTag(nil, nil))
	check("constructor/NewJSDocReadonlyTag", f.NewJSDocReadonlyTag(nil, nil))
	check("constructor/NewJSDocOverrideTag", f.NewJSDocOverrideTag(nil, nil))
	check("constructor/NewJSDocDeprecatedTag", f.NewJSDocDeprecatedTag(nil, nil))
	check("constructor/NewJSDocSeeTag", f.NewJSDocSeeTag(nil, nil, nil))
	check("constructor/NewJSDocImplementsTag", f.NewJSDocImplementsTag(nil, nil, nil))
	check("constructor/NewJSDocAugmentsTag", f.NewJSDocAugmentsTag(nil, nil, nil))
	check("constructor/NewJSDocSatisfiesTag", f.NewJSDocSatisfiesTag(nil, nil, nil))
	check("constructor/NewJSDocThrowsTag", f.NewJSDocThrowsTag(nil, nil, nil))
	check("constructor/NewJSDocThisTag", f.NewJSDocThisTag(nil, nil, nil))
	check("constructor/NewJSDocImportTag", f.NewJSDocImportTag(nil, nil, nil, nil, nil))
	check("constructor/NewJSDocCallbackTag", f.NewJSDocCallbackTag(nil, nil, nil, nil))
	check("constructor/NewJSDocOverloadTag", f.NewJSDocOverloadTag(nil, nil, nil))
	check("constructor/NewJSDocTypedefTag", f.NewJSDocTypedefTag(nil, nil, nil, nil))
	check("constructor/NewJSDocSignature", f.NewJSDocSignature(nil, nil, nil))
	check("constructor/NewJSDocNameReference", f.NewJSDocNameReference(nil))
	check("constructor/NewModuleDeclaration", f.NewModuleDeclaration(nil, KindUnknown, nil, nil, nil))
	check("constructor/NewImportEqualsDeclaration", f.NewImportEqualsDeclaration(nil, false, nil, nil))
	check("constructor/NewExportDeclaration", f.NewExportDeclaration(nil, false, nil, nil, nil))
	check("constructor/NewImportTypeNode", f.NewImportTypeNode(false, nil, nil, nil, nil))
	check("constructor/NewImportClause", f.NewImportClause(KindUnknown, nil, nil))
	check("constructor/NewImportSpecifier", f.NewImportSpecifier(false, nil, nil))
	check("constructor/NewJSDocText", f.NewJSDocText([]string{"x", "y\xff"}))
	check("constructor/NewJSDocLink", f.NewJSDocLink(nil, []string{"x", "y\xff"}))
	check("constructor/NewJSDocLinkPlain", f.NewJSDocLinkPlain(nil, []string{"x", "y\xff"}))
	check("constructor/NewJSDocLinkCode", f.NewJSDocLinkCode(nil, []string{"x", "y\xff"}))
	check("constructor/NewTypeParameterDeclaration", f.NewTypeParameterDeclaration(nil, nil, nil, nil, nil))
	check("constructor/NewSyntheticReferenceExpression", f.NewSyntheticReferenceExpression(nil, nil))
	check("constructor/NewJSDocTypeLiteral", f.NewJSDocTypeLiteral(nil, false))
	check("constructor/NewJSDocParameterOrPropertyTag", f.NewJSDocParameterOrPropertyTag(KindUnknown, nil, nil, false, nil, false, nil))
	// Nonempty, nil-containing and alternate-kind payloads supplement the zero-input constructors.
	listAB := f.NewNodeList([]*Node{a, nil, b})
	check("nonnull/call", f.NewCallExpression(a, q, listAB, listAB, NodeFlagsOptionalChain))
	check("nonnull/function", f.NewFunctionDeclaration(nil, nil, a, listAB, listAB, b, nil, a))
	check("nonnull/property-question", f.NewPropertyDeclaration(nil, a, q, b, a))
	check("nonnull/property-exclamation", f.NewPropertyDeclaration(nil, a, e, b, a))
	check("nonnull/jsx-name", f.NewJsxNamespacedName(a, b))
	check("nonnull/meta", f.NewMetaProperty(KindImportKeyword, a))
	check("nonnull/import-type", f.NewImportClause(KindTypeKeyword, a, b))
	check("nonnull/retag-function", func() *Node {
		n := f.NewFunctionDeclaration(nil, nil, a, listAB, listAB, b, nil, a)
		n.Kind = KindIdentifier
		return n
	}())
	source := f.NewSourceFile(SourceFileParseOptions{FileName: "/canonical.ts", Path: "/cache/canonical.ts", ExternalModuleIndicatorOptions: ExternalModuleIndicatorOptions{JSX: true}}, "a\r\n\xf0\x9f\x98\x80z", nil, nil).AsSourceFile()
	sourceCheck := func(name string, sf *SourceFile) {
		observe(name+"/FileName", func() string { return fmt.Sprintf("%x", sf.FileName()) })
		observe(name+"/Path", func() string { return fmt.Sprintf("%x", sf.Path()) })
		observe(name+"/Text", func() string { return fmt.Sprintf("%x", sf.Text()) })
		observe(name+"/OriginalText", func() string { return fmt.Sprintf("%x", sf.OriginalText()) })
		observe(name+"/OriginalFileName", func() string { return fmt.Sprintf("%x", sf.OriginalFileName()) })
		observe(name+"/ParseOptions", func() string {
			o := sf.ParseOptions()
			return fmt.Sprintf("%x:%x:%t:%t", o.FileName, o.Path, o.ExternalModuleIndicatorOptions.JSX, o.ExternalModuleIndicatorOptions.Force)
		})
		observe(name+"/ContentMapper", func() string { return fmt.Sprintf("%x", sf.ContentMapper()) })
		observe(name+"/ContentMapperTransformIdentity", func() string { return fmt.Sprintf("%x", sf.ContentMapperTransformIdentity()) })
		observe(name+"/ContentMapperParseOptions", func() string {
			o := sf.ContentMapperParseOptions()
			return fmt.Sprintf("%x:%x:%t:%t", o.FileName, o.Path, o.ExternalModuleIndicatorOptions.JSX, o.ExternalModuleIndicatorOptions.Force)
		})
		observe(name+"/VirtualFileName", func() string { return fmt.Sprintf("%x", sf.VirtualFileName()) })
		observe(name+"/IsContentMapperFailureStub", func() string { return fmt.Sprint(sf.IsContentMapperFailureStub()) })
		observe(name+"/IsContentMapperSupplemental", func() string { return fmt.Sprint(sf.IsContentMapperSupplemental()) })
		observe(name+"/SpanMap", func() string { return fmt.Sprint(sf.SpanMap() == nil) })
		observe(name+"/CanonicalSourceFile", func() string { return fmt.Sprint(sf.CanonicalSourceFile() == source) })
		observe(name+"/SupplementalSourceFiles", func() string { return fmt.Sprint(len(sf.SupplementalSourceFiles())) })
		observe(name+"/DiagnosticDirectives", func() string { return fmt.Sprint(len(sf.DiagnosticDirectives())) })
		observe(name+"/Imports", func() string { return nodes(sf.Imports()) })
		observe(name+"/Diagnostics", func() string { return fmt.Sprint(len(sf.Diagnostics())) })
		observe(name+"/JSDiagnostics", func() string { return fmt.Sprint(len(sf.JSDiagnostics())) })
		observe(name+"/JSDocDiagnostics", func() string { return fmt.Sprint(len(sf.JSDocDiagnostics())) })
		observe(name+"/GetPositionMap", func() string {
			p := sf.GetPositionMap()
			parts := []string{fmt.Sprint(p == sf.GetPositionMap()), fmt.Sprint(p.IsAsciiOnly())}
			for i := 0; i <= len(sf.Text()); i++ {
				parts = append(parts, fmt.Sprint(p.UTF8ToUTF16(i)))
			}
			return strings.Join(parts, ",")
		})
	}
	sourceCheck("source/plain", source)
	for _, kind := range []core.ScriptKind{-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 100} {
		source.ScriptKind = kind
		observe(fmt.Sprintf("source/IsJS/%d", kind), func() string { return fmt.Sprint(source.IsJS()) })
	}
	source.imports = []*Node{a, nil, b}
	source.SetDiagnostics([]*Diagnostic{{}})
	source.SetJSDiagnostics([]*Diagnostic{{}, {}})
	source.SetJSDocDiagnostics([]*Diagnostic{{}, {}, {}})
	source.SetHasLazyJSDoc(true)
	observe("source/lazy/true", func() string { return fmt.Sprint(source.hasLazyJSDoc) })
	source.SetHasLazyJSDoc(false)
	observe("source/lazy/false", func() string { return fmt.Sprint(source.hasLazyJSDoc) })
	source.SetContentMapperInfo(ContentMapperSourceFileInfo{OriginalText: "ignored", VirtualFileName: "virtual"})
	sourceCheck("source/empty-mapper", source)
	supplemental := f.NewSourceFile(SourceFileParseOptions{FileName: "/supp.ts"}, "transformed", nil, nil).AsSourceFile()
	supplemental.SetContentMapperInfo(ContentMapperSourceFileInfo{ContentMapper: "mapper", TransformIdentity: "v1", OriginalText: "original\xff", VirtualFileName: "virtual", CanonicalSourceFile: source, ParseOptions: source.ParseOptions(), DiagnosticDirectives: []MappedDiagnosticDirective{{}}, SupplementalSourceFiles: []*SourceFile{source}})
	sourceCheck("source/supplemental", supplemental)
	observe("source/duplicate-info", func() string { supplemental.SetContentMapperInfo(ContentMapperSourceFileInfo{}); return "unexpected" })

}
