[package]
name = "ts_tspath"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ts_core = { version = "0.1.0", path = "../ts_core" }
ts_jsstring = { version = "0.1.0", path = "../ts_jsstring" }

[lints]
workspace = true

[dev-dependencies]
serde_json = "1"
