#!/usr/bin/env python3
"""Render the pinned client declaration surface from gen-proto's JSON export.

Wire type spellings, visibility, documentation and declaration order are facts
supplied by the pinned extractor. This adapter only emits TypeScript syntax;
the upstream pinned formatter supplies the final client bytes.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def unique_object(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def property_name(name: str) -> str:
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name):
        return name
    return json.dumps(name, ensure_ascii=False)


def render(contract: dict) -> str:
    if contract.get("schemaVersion") != 1 or contract.get("generator") != "tools/gen-proto":
        raise ValueError("unsupported API contract schema or generator")
    types = {}
    for item in contract["types"]:
        if item["id"] in types:
            raise ValueError(f"duplicate exported type: {item['id']}")
        types[item["id"]] = item
    order = contract["declarationOrder"]
    if len(set(order)) != len(order):
        raise ValueError("duplicate DTO declaration")
    if set(order) != {key for key, item in types.items() if item["kind"] == "dto"}:
        raise ValueError("DTO declaration order does not cover exported DTOs")
    methods = contract["methods"]
    if len({method["id"] for method in methods}) != len(methods):
        raise ValueError("duplicate method ID")

    chunks = ["// Code generated by gen-proto; DO NOT EDIT.\n\n"]
    imports = contract["imports"]
    for item in imports:
        chunks.append(f"import {{ {', '.join(item['names'])} }} from {json.dumps(item['path'])};\n")
    if imports:
        chunks.append("\n")
        for item in imports:
            chunks.append(f"export {{ {', '.join(item['names'])} }} from {json.dumps(item['path'])};\n")
    chunks.append("\n")
    chunks.append("export type APIMethod<TParams, TResult> = { params: TParams; result: TResult; };\n\n")
    chunks.append("export interface APIMethodInfo {\n")
    for method in methods:
        chunks.append(
            f"    {property_name(method['id'])}: APIMethod<"
            f"{method['params']['typescript']}, {method['result']['typescript']}>;\n"
        )
    chunks.append("}\n\n")
    for alias in contract["aliases"]:
        chunks.extend([alias["typescriptDoc"], f"export type {alias['name']} = {alias['typescript']};\n\n"])
    for key in order:
        item = types[key]
        chunks.extend([item["typescriptDoc"], f"export interface {item['typescript']} {{\n"])
        for field in item.get("fields", []):
            if not field["clientVisible"]:
                continue
            chunks.append(field["typescriptDoc"])
            optional = "?" if field["optional"] else ""
            chunks.append(f"    {property_name(field['jsonName'])}{optional}: {field['typescript']};\n")
        chunks.append("}\n\n")
    return "".join(chunks).rstrip("\n") + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("contract", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    contract = json.loads(args.contract.read_text(), object_pairs_hook=unique_object)
    output = render(contract)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(output.replace("\n", "\r\n").encode())


if __name__ == "__main__":
    main()
