[package]
name = "ts_pseudochecker"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
stacker = "=0.1.25"
ts_ast = { version = "0.1.0", path = "../ts_ast" }
ts_arena = { version = "0.1.0", path = "../ts_arena" }

[dev-dependencies]
serde_json = "1"
ts_parser = { version = "0.1.0", path = "../ts_parser" }
ts_binder = { version = "0.1.0", path = "../ts_binder" }
ts_core = { version = "0.1.0", path = "../ts_core" }
ts_jsstring = { version = "0.1.0", path = "../ts_jsstring" }

[lints]
workspace = true
