[package]
name = "ts_ast"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
layout-profile = []

[dependencies]
stacker = "=0.1.25"
ts_core = { path = "../ts_core", version = "0.1.0" }
ts_diagnostics = { path = "../ts_diagnostics", version = "0.1.0" }
ts_arena = { path = "../ts_arena", version = "0.1.0" }
ts_jsstring = { path = "../ts_jsstring", version = "0.1.0" }

[lints]
workspace = true
