[package]
name = "ts_ast"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ts_arena = { path = "../ts_arena", version = "0.1.0" }
ts_jsstring = { path = "../ts_jsstring", version = "0.1.0" }

[lints]
workspace = true
