[package]
name = "e4_harness"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ts_jsstring = { version = "0.0.0", path = "../ts_jsstring" }

[[bin]]
name = "e4-harness"
path = "src/main.rs"

[lints]
workspace = true
