#!/usr/bin/env python3
"""Render exact Go comparison traces as dependency-free Rust test fixtures."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]


def render(data):
    lines = [
        '// Generated by tools/s06/node-index-sort/render.py from the independent Go traces.',
        f'// Observed toolchain: {data["go"]}. Do not edit.',
        '#[rustfmt::skip]',
        'const FIXTURES: &[Fixture] = &[',
    ]
    for case in data['cases']:
        lines.extend([
            '    Fixture {',
            f'        name: {json.dumps(case["name"])}, mode: {json.dumps(case["mode"])}, lazy: {str(case["lazy"]).lower()},',
            f'        keys: &{json.dumps(case["keys"])},',
            f'        start: {case["start"]}, end: {case["end"]},',
            f'        sorted: &{json.dumps(case["sorted"])},',
            f'        trace: &{json.dumps(case["trace"])},',
            f'        result: {str(case["result"]).lower()}, result_index: {case["result_index"]}, panicked: {str(case["panicked"]).lower()},',
            '    },',
        ])
    lines.append('];')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    data = json.loads((ROOT / 'data/s06/node-index-sort-traces.json').read_text())
    (ROOT / 'crates/ts_core/src/go_sort/fixtures.rs').write_text(render(data))
