// Generated by cargo xtask gen from the pinned SchemaAPI; do not edit.
// Upstream: 1f70213d4922b434345f639b441681e470c7cfc1
// port: tsc/internal/ast/ast_generated.go

use crate::{
    ArrayLiteralExpressionData, ArrayTypeNodeData, ArrowFunctionData, AsExpressionData,
    AwaitExpressionData, BigIntLiteralData, BinaryExpressionData, BindingElementData,
    BindingPatternData, BlockData, BreakStatementData, CallExpressionData,
    CallSignatureDeclarationData, CaseBlockData, CaseOrDefaultClauseData, CatchClauseData,
    ClassDeclarationData, ClassExpressionData, ClassStaticBlockDeclarationData,
    ComputedPropertyNameData, ConditionalExpressionData, ConditionalTypeNodeData,
    ConstructSignatureDeclarationData, ConstructorDeclarationData, ConstructorTypeNodeData,
    ContinueStatementData, DebuggerStatementData, DecoratorData, DeleteExpressionData,
    DoStatementData, ElementAccessExpressionData, EmptyStatementData, EnumDeclarationData,
    EnumMemberData, ExportAssignmentData, ExportDeclarationData, ExportSpecifierData,
    ExpressionStatementData, ExpressionWithTypeArgumentsData, ExternalModuleReferenceData,
    ForInOrOfStatementData, ForStatementData, FunctionDeclarationData, FunctionExpressionData,
    FunctionTypeNodeData, GetAccessorDeclarationData, HeritageClauseData, IdentifierData,
    IfStatementData, ImportAttributeData, ImportAttributesData, ImportClauseData,
    ImportDeclarationData, ImportEqualsDeclarationData, ImportSpecifierData, ImportTypeNodeData,
    IndexSignatureDeclarationData, IndexedAccessTypeNodeData, InferTypeNodeData,
    InterfaceDeclarationData, IntersectionTypeNodeData, JSDocAllTypeData, JSDocAugmentsTagData,
    JSDocCallbackTagData, JSDocData, JSDocDeprecatedTagData, JSDocImplementsTagData,
    JSDocImportTagData, JSDocLinkCodeData, JSDocLinkData, JSDocLinkPlainData,
    JSDocNameReferenceData, JSDocNonNullableTypeData, JSDocNullableTypeData, JSDocOptionalTypeData,
    JSDocOverloadTagData, JSDocOverrideTagData, JSDocParameterOrPropertyTagData,
    JSDocPrivateTagData, JSDocProtectedTagData, JSDocPublicTagData, JSDocReadonlyTagData,
    JSDocReturnTagData, JSDocSatisfiesTagData, JSDocSeeTagData, JSDocSignatureData,
    JSDocTemplateTagData, JSDocTextData, JSDocThisTagData, JSDocThrowsTagData,
    JSDocTypeExpressionData, JSDocTypeLiteralData, JSDocTypeTagData, JSDocTypedefTagData,
    JSDocUnknownTagData, JSDocVariadicTypeData, JsxAttributeData, JsxAttributesData,
    JsxClosingElementData, JsxClosingFragmentData, JsxElementData, JsxExpressionData,
    JsxFragmentData, JsxNamespacedNameData, JsxOpeningElementData, JsxOpeningFragmentData,
    JsxSelfClosingElementData, JsxSpreadAttributeData, JsxTextData, KeywordExpressionData,
    KeywordTypeNodeData, LabeledStatementData, LiteralTypeNodeData, MappedTypeNodeData,
    MetaPropertyData, MethodDeclarationData, MethodSignatureDeclarationData,
    MissingDeclarationData, ModuleBlockData, ModuleDeclarationData, NamedExportsData,
    NamedImportsData, NamedTupleMemberData, NamespaceExportData, NamespaceExportDeclarationData,
    NamespaceImportData, NewExpressionData, NoSubstitutionTemplateLiteralData, NodeData,
    NonNullExpressionData, NotEmittedStatementData, NotEmittedTypeElementData, NumericLiteralData,
    ObjectLiteralExpressionData, OmittedExpressionData, OptionalTypeNodeData,
    ParameterDeclarationData, ParenthesizedExpressionData, ParenthesizedTypeNodeData,
    PartiallyEmittedExpressionData, PostfixUnaryExpressionData, PrefixUnaryExpressionData,
    PrivateIdentifierData, PropertyAccessExpressionData, PropertyAssignmentData,
    PropertyDeclarationData, PropertySignatureDeclarationData, QualifiedNameData,
    RegularExpressionLiteralData, RestTypeNodeData, ReturnStatementData, SatisfiesExpressionData,
    SemicolonClassElementData, SetAccessorDeclarationData, ShorthandPropertyAssignmentData,
    SourceFileData, SpreadAssignmentData, SpreadElementData, StringLiteralData,
    SwitchStatementData, SyntaxKind, SyntaxListData, SyntheticExpressionData,
    SyntheticReferenceExpressionData, TaggedTemplateExpressionData, TemplateExpressionData,
    TemplateHeadData, TemplateLiteralTypeNodeData, TemplateLiteralTypeSpanData, TemplateMiddleData,
    TemplateSpanData, TemplateTailData, ThisTypeNodeData, ThrowStatementData, TokenData,
    TryStatementData, TupleTypeNodeData, TypeAliasDeclarationData, TypeAssertionData,
    TypeLiteralNodeData, TypeOfExpressionData, TypeOperatorNodeData, TypeParameterDeclarationData,
    TypePredicateNodeData, TypeQueryNodeData, TypeReferenceNodeData, UnionTypeNodeData,
    VariableDeclarationData, VariableDeclarationListData, VariableStatementData,
    VoidExpressionData, WhileStatementData, WithStatementData, YieldExpressionData,
};

impl NodeData {
    pub fn as_token(&self) -> Option<&TokenData> {
        if let Self::Token(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_identifier(&self) -> Option<&IdentifierData> {
        if let Self::Identifier(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_private_identifier(&self) -> Option<&PrivateIdentifierData> {
        if let Self::PrivateIdentifier(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_qualified_name(&self) -> Option<&QualifiedNameData> {
        if let Self::QualifiedName(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_computed_property_name(&self) -> Option<&ComputedPropertyNameData> {
        if let Self::ComputedPropertyName(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_decorator(&self) -> Option<&DecoratorData> {
        if let Self::Decorator(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_empty_statement(&self) -> Option<&EmptyStatementData> {
        if let Self::EmptyStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_if_statement(&self) -> Option<&IfStatementData> {
        if let Self::IfStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_do_statement(&self) -> Option<&DoStatementData> {
        if let Self::DoStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_while_statement(&self) -> Option<&WhileStatementData> {
        if let Self::WhileStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_for_statement(&self) -> Option<&ForStatementData> {
        if let Self::ForStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_for_in_or_of_statement(&self) -> Option<&ForInOrOfStatementData> {
        if let Self::ForInOrOfStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_break_statement(&self) -> Option<&BreakStatementData> {
        if let Self::BreakStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_continue_statement(&self) -> Option<&ContinueStatementData> {
        if let Self::ContinueStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_return_statement(&self) -> Option<&ReturnStatementData> {
        if let Self::ReturnStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_with_statement(&self) -> Option<&WithStatementData> {
        if let Self::WithStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_switch_statement(&self) -> Option<&SwitchStatementData> {
        if let Self::SwitchStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_case_block(&self) -> Option<&CaseBlockData> {
        if let Self::CaseBlock(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_case_or_default_clause(&self) -> Option<&CaseOrDefaultClauseData> {
        if let Self::CaseOrDefaultClause(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_throw_statement(&self) -> Option<&ThrowStatementData> {
        if let Self::ThrowStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_try_statement(&self) -> Option<&TryStatementData> {
        if let Self::TryStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_catch_clause(&self) -> Option<&CatchClauseData> {
        if let Self::CatchClause(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_debugger_statement(&self) -> Option<&DebuggerStatementData> {
        if let Self::DebuggerStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_labeled_statement(&self) -> Option<&LabeledStatementData> {
        if let Self::LabeledStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_expression_statement(&self) -> Option<&ExpressionStatementData> {
        if let Self::ExpressionStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_block(&self) -> Option<&BlockData> {
        if let Self::Block(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_variable_statement(&self) -> Option<&VariableStatementData> {
        if let Self::VariableStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_variable_declaration(&self) -> Option<&VariableDeclarationData> {
        if let Self::VariableDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_variable_declaration_list(&self) -> Option<&VariableDeclarationListData> {
        if let Self::VariableDeclarationList(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_binding_pattern(&self) -> Option<&BindingPatternData> {
        if let Self::BindingPattern(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_parameter_declaration(&self) -> Option<&ParameterDeclarationData> {
        if let Self::ParameterDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_binding_element(&self) -> Option<&BindingElementData> {
        if let Self::BindingElement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_missing_declaration(&self) -> Option<&MissingDeclarationData> {
        if let Self::MissingDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_function_declaration(&self) -> Option<&FunctionDeclarationData> {
        if let Self::FunctionDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_class_declaration(&self) -> Option<&ClassDeclarationData> {
        if let Self::ClassDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_class_expression(&self) -> Option<&ClassExpressionData> {
        if let Self::ClassExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_heritage_clause(&self) -> Option<&HeritageClauseData> {
        if let Self::HeritageClause(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_interface_declaration(&self) -> Option<&InterfaceDeclarationData> {
        if let Self::InterfaceDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_type_alias_declaration(&self) -> Option<&TypeAliasDeclarationData> {
        if let Self::TypeAliasDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_enum_member(&self) -> Option<&EnumMemberData> {
        if let Self::EnumMember(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_enum_declaration(&self) -> Option<&EnumDeclarationData> {
        if let Self::EnumDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_module_block(&self) -> Option<&ModuleBlockData> {
        if let Self::ModuleBlock(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_not_emitted_statement(&self) -> Option<&NotEmittedStatementData> {
        if let Self::NotEmittedStatement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_not_emitted_type_element(&self) -> Option<&NotEmittedTypeElementData> {
        if let Self::NotEmittedTypeElement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_import_declaration(&self) -> Option<&ImportDeclarationData> {
        if let Self::ImportDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_external_module_reference(&self) -> Option<&ExternalModuleReferenceData> {
        if let Self::ExternalModuleReference(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_namespace_import(&self) -> Option<&NamespaceImportData> {
        if let Self::NamespaceImport(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_named_imports(&self) -> Option<&NamedImportsData> {
        if let Self::NamedImports(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_export_assignment(&self) -> Option<&ExportAssignmentData> {
        if let Self::ExportAssignment(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_namespace_export_declaration(&self) -> Option<&NamespaceExportDeclarationData> {
        if let Self::NamespaceExportDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_namespace_export(&self) -> Option<&NamespaceExportData> {
        if let Self::NamespaceExport(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_named_exports(&self) -> Option<&NamedExportsData> {
        if let Self::NamedExports(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_export_specifier(&self) -> Option<&ExportSpecifierData> {
        if let Self::ExportSpecifier(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_call_signature_declaration(&self) -> Option<&CallSignatureDeclarationData> {
        if let Self::CallSignatureDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_construct_signature_declaration(&self) -> Option<&ConstructSignatureDeclarationData> {
        if let Self::ConstructSignatureDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_constructor_declaration(&self) -> Option<&ConstructorDeclarationData> {
        if let Self::ConstructorDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_get_accessor_declaration(&self) -> Option<&GetAccessorDeclarationData> {
        if let Self::GetAccessorDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_set_accessor_declaration(&self) -> Option<&SetAccessorDeclarationData> {
        if let Self::SetAccessorDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_index_signature_declaration(&self) -> Option<&IndexSignatureDeclarationData> {
        if let Self::IndexSignatureDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_method_signature_declaration(&self) -> Option<&MethodSignatureDeclarationData> {
        if let Self::MethodSignatureDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_method_declaration(&self) -> Option<&MethodDeclarationData> {
        if let Self::MethodDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_property_signature_declaration(&self) -> Option<&PropertySignatureDeclarationData> {
        if let Self::PropertySignatureDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_property_declaration(&self) -> Option<&PropertyDeclarationData> {
        if let Self::PropertyDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_semicolon_class_element(&self) -> Option<&SemicolonClassElementData> {
        if let Self::SemicolonClassElement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_class_static_block_declaration(&self) -> Option<&ClassStaticBlockDeclarationData> {
        if let Self::ClassStaticBlockDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_omitted_expression(&self) -> Option<&OmittedExpressionData> {
        if let Self::OmittedExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_keyword_expression(&self) -> Option<&KeywordExpressionData> {
        if let Self::KeywordExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_string_literal(&self) -> Option<&StringLiteralData> {
        if let Self::StringLiteral(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_numeric_literal(&self) -> Option<&NumericLiteralData> {
        if let Self::NumericLiteral(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_big_int_literal(&self) -> Option<&BigIntLiteralData> {
        if let Self::BigIntLiteral(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_regular_expression_literal(&self) -> Option<&RegularExpressionLiteralData> {
        if let Self::RegularExpressionLiteral(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_no_substitution_template_literal(
        &self,
    ) -> Option<&NoSubstitutionTemplateLiteralData> {
        if let Self::NoSubstitutionTemplateLiteral(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_binary_expression(&self) -> Option<&BinaryExpressionData> {
        if let Self::BinaryExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_prefix_unary_expression(&self) -> Option<&PrefixUnaryExpressionData> {
        if let Self::PrefixUnaryExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_postfix_unary_expression(&self) -> Option<&PostfixUnaryExpressionData> {
        if let Self::PostfixUnaryExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_yield_expression(&self) -> Option<&YieldExpressionData> {
        if let Self::YieldExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_arrow_function(&self) -> Option<&ArrowFunctionData> {
        if let Self::ArrowFunction(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_function_expression(&self) -> Option<&FunctionExpressionData> {
        if let Self::FunctionExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_as_expression(&self) -> Option<&AsExpressionData> {
        if let Self::AsExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_satisfies_expression(&self) -> Option<&SatisfiesExpressionData> {
        if let Self::SatisfiesExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_conditional_expression(&self) -> Option<&ConditionalExpressionData> {
        if let Self::ConditionalExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_property_access_expression(&self) -> Option<&PropertyAccessExpressionData> {
        if let Self::PropertyAccessExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_element_access_expression(&self) -> Option<&ElementAccessExpressionData> {
        if let Self::ElementAccessExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_call_expression(&self) -> Option<&CallExpressionData> {
        if let Self::CallExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_new_expression(&self) -> Option<&NewExpressionData> {
        if let Self::NewExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_meta_property(&self) -> Option<&MetaPropertyData> {
        if let Self::MetaProperty(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_non_null_expression(&self) -> Option<&NonNullExpressionData> {
        if let Self::NonNullExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_spread_element(&self) -> Option<&SpreadElementData> {
        if let Self::SpreadElement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_template_expression(&self) -> Option<&TemplateExpressionData> {
        if let Self::TemplateExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_template_span(&self) -> Option<&TemplateSpanData> {
        if let Self::TemplateSpan(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_tagged_template_expression(&self) -> Option<&TaggedTemplateExpressionData> {
        if let Self::TaggedTemplateExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_parenthesized_expression(&self) -> Option<&ParenthesizedExpressionData> {
        if let Self::ParenthesizedExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_array_literal_expression(&self) -> Option<&ArrayLiteralExpressionData> {
        if let Self::ArrayLiteralExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_object_literal_expression(&self) -> Option<&ObjectLiteralExpressionData> {
        if let Self::ObjectLiteralExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_spread_assignment(&self) -> Option<&SpreadAssignmentData> {
        if let Self::SpreadAssignment(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_property_assignment(&self) -> Option<&PropertyAssignmentData> {
        if let Self::PropertyAssignment(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_shorthand_property_assignment(&self) -> Option<&ShorthandPropertyAssignmentData> {
        if let Self::ShorthandPropertyAssignment(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_delete_expression(&self) -> Option<&DeleteExpressionData> {
        if let Self::DeleteExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_type_of_expression(&self) -> Option<&TypeOfExpressionData> {
        if let Self::TypeOfExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_void_expression(&self) -> Option<&VoidExpressionData> {
        if let Self::VoidExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_await_expression(&self) -> Option<&AwaitExpressionData> {
        if let Self::AwaitExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_type_assertion(&self) -> Option<&TypeAssertionData> {
        if let Self::TypeAssertion(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_keyword_type_node(&self) -> Option<&KeywordTypeNodeData> {
        if let Self::KeywordTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_union_type_node(&self) -> Option<&UnionTypeNodeData> {
        if let Self::UnionTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_intersection_type_node(&self) -> Option<&IntersectionTypeNodeData> {
        if let Self::IntersectionTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_conditional_type_node(&self) -> Option<&ConditionalTypeNodeData> {
        if let Self::ConditionalTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_type_operator_node(&self) -> Option<&TypeOperatorNodeData> {
        if let Self::TypeOperatorNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_infer_type_node(&self) -> Option<&InferTypeNodeData> {
        if let Self::InferTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_array_type_node(&self) -> Option<&ArrayTypeNodeData> {
        if let Self::ArrayTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_indexed_access_type_node(&self) -> Option<&IndexedAccessTypeNodeData> {
        if let Self::IndexedAccessTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_type_reference_node(&self) -> Option<&TypeReferenceNodeData> {
        if let Self::TypeReferenceNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_expression_with_type_arguments(&self) -> Option<&ExpressionWithTypeArgumentsData> {
        if let Self::ExpressionWithTypeArguments(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_literal_type_node(&self) -> Option<&LiteralTypeNodeData> {
        if let Self::LiteralTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_this_type_node(&self) -> Option<&ThisTypeNodeData> {
        if let Self::ThisTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_type_predicate_node(&self) -> Option<&TypePredicateNodeData> {
        if let Self::TypePredicateNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_import_attribute(&self) -> Option<&ImportAttributeData> {
        if let Self::ImportAttribute(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_import_attributes(&self) -> Option<&ImportAttributesData> {
        if let Self::ImportAttributes(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_type_query_node(&self) -> Option<&TypeQueryNodeData> {
        if let Self::TypeQueryNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_mapped_type_node(&self) -> Option<&MappedTypeNodeData> {
        if let Self::MappedTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_type_literal_node(&self) -> Option<&TypeLiteralNodeData> {
        if let Self::TypeLiteralNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_tuple_type_node(&self) -> Option<&TupleTypeNodeData> {
        if let Self::TupleTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_named_tuple_member(&self) -> Option<&NamedTupleMemberData> {
        if let Self::NamedTupleMember(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_optional_type_node(&self) -> Option<&OptionalTypeNodeData> {
        if let Self::OptionalTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_rest_type_node(&self) -> Option<&RestTypeNodeData> {
        if let Self::RestTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_parenthesized_type_node(&self) -> Option<&ParenthesizedTypeNodeData> {
        if let Self::ParenthesizedTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_function_type_node(&self) -> Option<&FunctionTypeNodeData> {
        if let Self::FunctionTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_constructor_type_node(&self) -> Option<&ConstructorTypeNodeData> {
        if let Self::ConstructorTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_template_head(&self) -> Option<&TemplateHeadData> {
        if let Self::TemplateHead(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_template_middle(&self) -> Option<&TemplateMiddleData> {
        if let Self::TemplateMiddle(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_template_tail(&self) -> Option<&TemplateTailData> {
        if let Self::TemplateTail(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_template_literal_type_node(&self) -> Option<&TemplateLiteralTypeNodeData> {
        if let Self::TemplateLiteralTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_template_literal_type_span(&self) -> Option<&TemplateLiteralTypeSpanData> {
        if let Self::TemplateLiteralTypeSpan(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_synthetic_expression(&self) -> Option<&SyntheticExpressionData> {
        if let Self::SyntheticExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_partially_emitted_expression(&self) -> Option<&PartiallyEmittedExpressionData> {
        if let Self::PartiallyEmittedExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_element(&self) -> Option<&JsxElementData> {
        if let Self::JsxElement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_attributes(&self) -> Option<&JsxAttributesData> {
        if let Self::JsxAttributes(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_namespaced_name(&self) -> Option<&JsxNamespacedNameData> {
        if let Self::JsxNamespacedName(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_opening_element(&self) -> Option<&JsxOpeningElementData> {
        if let Self::JsxOpeningElement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_self_closing_element(&self) -> Option<&JsxSelfClosingElementData> {
        if let Self::JsxSelfClosingElement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_fragment(&self) -> Option<&JsxFragmentData> {
        if let Self::JsxFragment(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_opening_fragment(&self) -> Option<&JsxOpeningFragmentData> {
        if let Self::JsxOpeningFragment(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_closing_fragment(&self) -> Option<&JsxClosingFragmentData> {
        if let Self::JsxClosingFragment(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_attribute(&self) -> Option<&JsxAttributeData> {
        if let Self::JsxAttribute(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_spread_attribute(&self) -> Option<&JsxSpreadAttributeData> {
        if let Self::JsxSpreadAttribute(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_closing_element(&self) -> Option<&JsxClosingElementData> {
        if let Self::JsxClosingElement(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_expression(&self) -> Option<&JsxExpressionData> {
        if let Self::JsxExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_jsx_text(&self) -> Option<&JsxTextData> {
        if let Self::JsxText(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_syntax_list(&self) -> Option<&SyntaxListData> {
        if let Self::SyntaxList(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc(&self) -> Option<&JSDocData> {
        if let Self::JSDoc(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_type_expression(&self) -> Option<&JSDocTypeExpressionData> {
        if let Self::JSDocTypeExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_non_nullable_type(&self) -> Option<&JSDocNonNullableTypeData> {
        if let Self::JSDocNonNullableType(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_nullable_type(&self) -> Option<&JSDocNullableTypeData> {
        if let Self::JSDocNullableType(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_all_type(&self) -> Option<&JSDocAllTypeData> {
        if let Self::JSDocAllType(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_variadic_type(&self) -> Option<&JSDocVariadicTypeData> {
        if let Self::JSDocVariadicType(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_optional_type(&self) -> Option<&JSDocOptionalTypeData> {
        if let Self::JSDocOptionalType(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_type_tag(&self) -> Option<&JSDocTypeTagData> {
        if let Self::JSDocTypeTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_unknown_tag(&self) -> Option<&JSDocUnknownTagData> {
        if let Self::JSDocUnknownTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_template_tag(&self) -> Option<&JSDocTemplateTagData> {
        if let Self::JSDocTemplateTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_return_tag(&self) -> Option<&JSDocReturnTagData> {
        if let Self::JSDocReturnTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_public_tag(&self) -> Option<&JSDocPublicTagData> {
        if let Self::JSDocPublicTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_private_tag(&self) -> Option<&JSDocPrivateTagData> {
        if let Self::JSDocPrivateTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_protected_tag(&self) -> Option<&JSDocProtectedTagData> {
        if let Self::JSDocProtectedTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_readonly_tag(&self) -> Option<&JSDocReadonlyTagData> {
        if let Self::JSDocReadonlyTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_override_tag(&self) -> Option<&JSDocOverrideTagData> {
        if let Self::JSDocOverrideTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_deprecated_tag(&self) -> Option<&JSDocDeprecatedTagData> {
        if let Self::JSDocDeprecatedTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_see_tag(&self) -> Option<&JSDocSeeTagData> {
        if let Self::JSDocSeeTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_implements_tag(&self) -> Option<&JSDocImplementsTagData> {
        if let Self::JSDocImplementsTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_augments_tag(&self) -> Option<&JSDocAugmentsTagData> {
        if let Self::JSDocAugmentsTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_satisfies_tag(&self) -> Option<&JSDocSatisfiesTagData> {
        if let Self::JSDocSatisfiesTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_throws_tag(&self) -> Option<&JSDocThrowsTagData> {
        if let Self::JSDocThrowsTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_this_tag(&self) -> Option<&JSDocThisTagData> {
        if let Self::JSDocThisTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_import_tag(&self) -> Option<&JSDocImportTagData> {
        if let Self::JSDocImportTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_callback_tag(&self) -> Option<&JSDocCallbackTagData> {
        if let Self::JSDocCallbackTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_overload_tag(&self) -> Option<&JSDocOverloadTagData> {
        if let Self::JSDocOverloadTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_typedef_tag(&self) -> Option<&JSDocTypedefTagData> {
        if let Self::JSDocTypedefTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_signature(&self) -> Option<&JSDocSignatureData> {
        if let Self::JSDocSignature(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_name_reference(&self) -> Option<&JSDocNameReferenceData> {
        if let Self::JSDocNameReference(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_source_file(&self) -> Option<&SourceFileData> {
        if let Self::SourceFile(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_module_declaration(&self) -> Option<&ModuleDeclarationData> {
        if let Self::ModuleDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_import_equals_declaration(&self) -> Option<&ImportEqualsDeclarationData> {
        if let Self::ImportEqualsDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_export_declaration(&self) -> Option<&ExportDeclarationData> {
        if let Self::ExportDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_import_type_node(&self) -> Option<&ImportTypeNodeData> {
        if let Self::ImportTypeNode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_import_clause(&self) -> Option<&ImportClauseData> {
        if let Self::ImportClause(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_import_specifier(&self) -> Option<&ImportSpecifierData> {
        if let Self::ImportSpecifier(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_text(&self) -> Option<&JSDocTextData> {
        if let Self::JSDocText(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_link(&self) -> Option<&JSDocLinkData> {
        if let Self::JSDocLink(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_link_plain(&self) -> Option<&JSDocLinkPlainData> {
        if let Self::JSDocLinkPlain(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_link_code(&self) -> Option<&JSDocLinkCodeData> {
        if let Self::JSDocLinkCode(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_type_parameter_declaration(&self) -> Option<&TypeParameterDeclarationData> {
        if let Self::TypeParameterDeclaration(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_synthetic_reference_expression(&self) -> Option<&SyntheticReferenceExpressionData> {
        if let Self::SyntheticReferenceExpression(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_type_literal(&self) -> Option<&JSDocTypeLiteralData> {
        if let Self::JSDocTypeLiteral(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn as_js_doc_parameter_or_property_tag(&self) -> Option<&JSDocParameterOrPropertyTagData> {
        if let Self::JSDocParameterOrPropertyTag(data) = self {
            Some(data)
        } else {
            None
        }
    }
    pub fn name(&self) -> &'static str {
        match self {
            Self::Token(_) => "Token",
            Self::Identifier(_) => "Identifier",
            Self::PrivateIdentifier(_) => "PrivateIdentifier",
            Self::QualifiedName(_) => "QualifiedName",
            Self::ComputedPropertyName(_) => "ComputedPropertyName",
            Self::Decorator(_) => "Decorator",
            Self::EmptyStatement(_) => "EmptyStatement",
            Self::IfStatement(_) => "IfStatement",
            Self::DoStatement(_) => "DoStatement",
            Self::WhileStatement(_) => "WhileStatement",
            Self::ForStatement(_) => "ForStatement",
            Self::ForInOrOfStatement(_) => "ForInOrOfStatement",
            Self::BreakStatement(_) => "BreakStatement",
            Self::ContinueStatement(_) => "ContinueStatement",
            Self::ReturnStatement(_) => "ReturnStatement",
            Self::WithStatement(_) => "WithStatement",
            Self::SwitchStatement(_) => "SwitchStatement",
            Self::CaseBlock(_) => "CaseBlock",
            Self::CaseOrDefaultClause(_) => "CaseOrDefaultClause",
            Self::ThrowStatement(_) => "ThrowStatement",
            Self::TryStatement(_) => "TryStatement",
            Self::CatchClause(_) => "CatchClause",
            Self::DebuggerStatement(_) => "DebuggerStatement",
            Self::LabeledStatement(_) => "LabeledStatement",
            Self::ExpressionStatement(_) => "ExpressionStatement",
            Self::Block(_) => "Block",
            Self::VariableStatement(_) => "VariableStatement",
            Self::VariableDeclaration(_) => "VariableDeclaration",
            Self::VariableDeclarationList(_) => "VariableDeclarationList",
            Self::BindingPattern(_) => "BindingPattern",
            Self::ParameterDeclaration(_) => "ParameterDeclaration",
            Self::BindingElement(_) => "BindingElement",
            Self::MissingDeclaration(_) => "MissingDeclaration",
            Self::FunctionDeclaration(_) => "FunctionDeclaration",
            Self::ClassDeclaration(_) => "ClassDeclaration",
            Self::ClassExpression(_) => "ClassExpression",
            Self::HeritageClause(_) => "HeritageClause",
            Self::InterfaceDeclaration(_) => "InterfaceDeclaration",
            Self::TypeAliasDeclaration(_) => "TypeAliasDeclaration",
            Self::EnumMember(_) => "EnumMember",
            Self::EnumDeclaration(_) => "EnumDeclaration",
            Self::ModuleBlock(_) => "ModuleBlock",
            Self::NotEmittedStatement(_) => "NotEmittedStatement",
            Self::NotEmittedTypeElement(_) => "NotEmittedTypeElement",
            Self::ImportDeclaration(_) => "ImportDeclaration",
            Self::ExternalModuleReference(_) => "ExternalModuleReference",
            Self::NamespaceImport(_) => "NamespaceImport",
            Self::NamedImports(_) => "NamedImports",
            Self::ExportAssignment(_) => "ExportAssignment",
            Self::NamespaceExportDeclaration(_) => "NamespaceExportDeclaration",
            Self::NamespaceExport(_) => "NamespaceExport",
            Self::NamedExports(_) => "NamedExports",
            Self::ExportSpecifier(_) => "ExportSpecifier",
            Self::CallSignatureDeclaration(_) => "CallSignatureDeclaration",
            Self::ConstructSignatureDeclaration(_) => "ConstructSignatureDeclaration",
            Self::ConstructorDeclaration(_) => "ConstructorDeclaration",
            Self::GetAccessorDeclaration(_) => "GetAccessorDeclaration",
            Self::SetAccessorDeclaration(_) => "SetAccessorDeclaration",
            Self::IndexSignatureDeclaration(_) => "IndexSignatureDeclaration",
            Self::MethodSignatureDeclaration(_) => "MethodSignatureDeclaration",
            Self::MethodDeclaration(_) => "MethodDeclaration",
            Self::PropertySignatureDeclaration(_) => "PropertySignatureDeclaration",
            Self::PropertyDeclaration(_) => "PropertyDeclaration",
            Self::SemicolonClassElement(_) => "SemicolonClassElement",
            Self::ClassStaticBlockDeclaration(_) => "ClassStaticBlockDeclaration",
            Self::OmittedExpression(_) => "OmittedExpression",
            Self::KeywordExpression(_) => "KeywordExpression",
            Self::StringLiteral(_) => "StringLiteral",
            Self::NumericLiteral(_) => "NumericLiteral",
            Self::BigIntLiteral(_) => "BigIntLiteral",
            Self::RegularExpressionLiteral(_) => "RegularExpressionLiteral",
            Self::NoSubstitutionTemplateLiteral(_) => "NoSubstitutionTemplateLiteral",
            Self::BinaryExpression(_) => "BinaryExpression",
            Self::PrefixUnaryExpression(_) => "PrefixUnaryExpression",
            Self::PostfixUnaryExpression(_) => "PostfixUnaryExpression",
            Self::YieldExpression(_) => "YieldExpression",
            Self::ArrowFunction(_) => "ArrowFunction",
            Self::FunctionExpression(_) => "FunctionExpression",
            Self::AsExpression(_) => "AsExpression",
            Self::SatisfiesExpression(_) => "SatisfiesExpression",
            Self::ConditionalExpression(_) => "ConditionalExpression",
            Self::PropertyAccessExpression(_) => "PropertyAccessExpression",
            Self::ElementAccessExpression(_) => "ElementAccessExpression",
            Self::CallExpression(_) => "CallExpression",
            Self::NewExpression(_) => "NewExpression",
            Self::MetaProperty(_) => "MetaProperty",
            Self::NonNullExpression(_) => "NonNullExpression",
            Self::SpreadElement(_) => "SpreadElement",
            Self::TemplateExpression(_) => "TemplateExpression",
            Self::TemplateSpan(_) => "TemplateSpan",
            Self::TaggedTemplateExpression(_) => "TaggedTemplateExpression",
            Self::ParenthesizedExpression(_) => "ParenthesizedExpression",
            Self::ArrayLiteralExpression(_) => "ArrayLiteralExpression",
            Self::ObjectLiteralExpression(_) => "ObjectLiteralExpression",
            Self::SpreadAssignment(_) => "SpreadAssignment",
            Self::PropertyAssignment(_) => "PropertyAssignment",
            Self::ShorthandPropertyAssignment(_) => "ShorthandPropertyAssignment",
            Self::DeleteExpression(_) => "DeleteExpression",
            Self::TypeOfExpression(_) => "TypeOfExpression",
            Self::VoidExpression(_) => "VoidExpression",
            Self::AwaitExpression(_) => "AwaitExpression",
            Self::TypeAssertion(_) => "TypeAssertion",
            Self::KeywordTypeNode(_) => "KeywordTypeNode",
            Self::UnionTypeNode(_) => "UnionTypeNode",
            Self::IntersectionTypeNode(_) => "IntersectionTypeNode",
            Self::ConditionalTypeNode(_) => "ConditionalTypeNode",
            Self::TypeOperatorNode(_) => "TypeOperatorNode",
            Self::InferTypeNode(_) => "InferTypeNode",
            Self::ArrayTypeNode(_) => "ArrayTypeNode",
            Self::IndexedAccessTypeNode(_) => "IndexedAccessTypeNode",
            Self::TypeReferenceNode(_) => "TypeReferenceNode",
            Self::ExpressionWithTypeArguments(_) => "ExpressionWithTypeArguments",
            Self::LiteralTypeNode(_) => "LiteralTypeNode",
            Self::ThisTypeNode(_) => "ThisTypeNode",
            Self::TypePredicateNode(_) => "TypePredicateNode",
            Self::ImportAttribute(_) => "ImportAttribute",
            Self::ImportAttributes(_) => "ImportAttributes",
            Self::TypeQueryNode(_) => "TypeQueryNode",
            Self::MappedTypeNode(_) => "MappedTypeNode",
            Self::TypeLiteralNode(_) => "TypeLiteralNode",
            Self::TupleTypeNode(_) => "TupleTypeNode",
            Self::NamedTupleMember(_) => "NamedTupleMember",
            Self::OptionalTypeNode(_) => "OptionalTypeNode",
            Self::RestTypeNode(_) => "RestTypeNode",
            Self::ParenthesizedTypeNode(_) => "ParenthesizedTypeNode",
            Self::FunctionTypeNode(_) => "FunctionTypeNode",
            Self::ConstructorTypeNode(_) => "ConstructorTypeNode",
            Self::TemplateHead(_) => "TemplateHead",
            Self::TemplateMiddle(_) => "TemplateMiddle",
            Self::TemplateTail(_) => "TemplateTail",
            Self::TemplateLiteralTypeNode(_) => "TemplateLiteralTypeNode",
            Self::TemplateLiteralTypeSpan(_) => "TemplateLiteralTypeSpan",
            Self::SyntheticExpression(_) => "SyntheticExpression",
            Self::PartiallyEmittedExpression(_) => "PartiallyEmittedExpression",
            Self::JsxElement(_) => "JsxElement",
            Self::JsxAttributes(_) => "JsxAttributes",
            Self::JsxNamespacedName(_) => "JsxNamespacedName",
            Self::JsxOpeningElement(_) => "JsxOpeningElement",
            Self::JsxSelfClosingElement(_) => "JsxSelfClosingElement",
            Self::JsxFragment(_) => "JsxFragment",
            Self::JsxOpeningFragment(_) => "JsxOpeningFragment",
            Self::JsxClosingFragment(_) => "JsxClosingFragment",
            Self::JsxAttribute(_) => "JsxAttribute",
            Self::JsxSpreadAttribute(_) => "JsxSpreadAttribute",
            Self::JsxClosingElement(_) => "JsxClosingElement",
            Self::JsxExpression(_) => "JsxExpression",
            Self::JsxText(_) => "JsxText",
            Self::SyntaxList(_) => "SyntaxList",
            Self::JSDoc(_) => "JSDoc",
            Self::JSDocTypeExpression(_) => "JSDocTypeExpression",
            Self::JSDocNonNullableType(_) => "JSDocNonNullableType",
            Self::JSDocNullableType(_) => "JSDocNullableType",
            Self::JSDocAllType(_) => "JSDocAllType",
            Self::JSDocVariadicType(_) => "JSDocVariadicType",
            Self::JSDocOptionalType(_) => "JSDocOptionalType",
            Self::JSDocTypeTag(_) => "JSDocTypeTag",
            Self::JSDocUnknownTag(_) => "JSDocUnknownTag",
            Self::JSDocTemplateTag(_) => "JSDocTemplateTag",
            Self::JSDocReturnTag(_) => "JSDocReturnTag",
            Self::JSDocPublicTag(_) => "JSDocPublicTag",
            Self::JSDocPrivateTag(_) => "JSDocPrivateTag",
            Self::JSDocProtectedTag(_) => "JSDocProtectedTag",
            Self::JSDocReadonlyTag(_) => "JSDocReadonlyTag",
            Self::JSDocOverrideTag(_) => "JSDocOverrideTag",
            Self::JSDocDeprecatedTag(_) => "JSDocDeprecatedTag",
            Self::JSDocSeeTag(_) => "JSDocSeeTag",
            Self::JSDocImplementsTag(_) => "JSDocImplementsTag",
            Self::JSDocAugmentsTag(_) => "JSDocAugmentsTag",
            Self::JSDocSatisfiesTag(_) => "JSDocSatisfiesTag",
            Self::JSDocThrowsTag(_) => "JSDocThrowsTag",
            Self::JSDocThisTag(_) => "JSDocThisTag",
            Self::JSDocImportTag(_) => "JSDocImportTag",
            Self::JSDocCallbackTag(_) => "JSDocCallbackTag",
            Self::JSDocOverloadTag(_) => "JSDocOverloadTag",
            Self::JSDocTypedefTag(_) => "JSDocTypedefTag",
            Self::JSDocSignature(_) => "JSDocSignature",
            Self::JSDocNameReference(_) => "JSDocNameReference",
            Self::SourceFile(_) => "SourceFile",
            Self::ModuleDeclaration(_) => "ModuleDeclaration",
            Self::ImportEqualsDeclaration(_) => "ImportEqualsDeclaration",
            Self::ExportDeclaration(_) => "ExportDeclaration",
            Self::ImportTypeNode(_) => "ImportTypeNode",
            Self::ImportClause(_) => "ImportClause",
            Self::ImportSpecifier(_) => "ImportSpecifier",
            Self::JSDocText(_) => "JSDocText",
            Self::JSDocLink(_) => "JSDocLink",
            Self::JSDocLinkPlain(_) => "JSDocLinkPlain",
            Self::JSDocLinkCode(_) => "JSDocLinkCode",
            Self::TypeParameterDeclaration(_) => "TypeParameterDeclaration",
            Self::SyntheticReferenceExpression(_) => "SyntheticReferenceExpression",
            Self::JSDocTypeLiteral(_) => "JSDocTypeLiteral",
            Self::JSDocParameterOrPropertyTag(_) => "JSDocParameterOrPropertyTag",
        }
    }
    pub fn supports_kind(&self, kind: SyntaxKind) -> bool {
        match self {
            Self::Token(_) => matches!(
                kind,
                SyntaxKind::Unknown
                    | SyntaxKind::EndOfFile
                    | SyntaxKind::SingleLineCommentTrivia
                    | SyntaxKind::MultiLineCommentTrivia
                    | SyntaxKind::NewLineTrivia
                    | SyntaxKind::WhitespaceTrivia
                    | SyntaxKind::ConflictMarkerTrivia
                    | SyntaxKind::NonTextFileMarkerTrivia
                    | SyntaxKind::NumericLiteral
                    | SyntaxKind::BigIntLiteral
                    | SyntaxKind::StringLiteral
                    | SyntaxKind::JsxText
                    | SyntaxKind::JsxTextAllWhiteSpaces
                    | SyntaxKind::RegularExpressionLiteral
                    | SyntaxKind::NoSubstitutionTemplateLiteral
                    | SyntaxKind::TemplateHead
                    | SyntaxKind::TemplateMiddle
                    | SyntaxKind::TemplateTail
                    | SyntaxKind::OpenBraceToken
                    | SyntaxKind::CloseBraceToken
                    | SyntaxKind::OpenParenToken
                    | SyntaxKind::CloseParenToken
                    | SyntaxKind::OpenBracketToken
                    | SyntaxKind::CloseBracketToken
                    | SyntaxKind::DotToken
                    | SyntaxKind::DotDotDotToken
                    | SyntaxKind::SemicolonToken
                    | SyntaxKind::CommaToken
                    | SyntaxKind::QuestionDotToken
                    | SyntaxKind::LessThanToken
                    | SyntaxKind::LessThanSlashToken
                    | SyntaxKind::GreaterThanToken
                    | SyntaxKind::LessThanEqualsToken
                    | SyntaxKind::GreaterThanEqualsToken
                    | SyntaxKind::EqualsEqualsToken
                    | SyntaxKind::ExclamationEqualsToken
                    | SyntaxKind::EqualsEqualsEqualsToken
                    | SyntaxKind::ExclamationEqualsEqualsToken
                    | SyntaxKind::EqualsGreaterThanToken
                    | SyntaxKind::PlusToken
                    | SyntaxKind::MinusToken
                    | SyntaxKind::AsteriskToken
                    | SyntaxKind::AsteriskAsteriskToken
                    | SyntaxKind::SlashToken
                    | SyntaxKind::PercentToken
                    | SyntaxKind::PlusPlusToken
                    | SyntaxKind::MinusMinusToken
                    | SyntaxKind::LessThanLessThanToken
                    | SyntaxKind::GreaterThanGreaterThanToken
                    | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
                    | SyntaxKind::AmpersandToken
                    | SyntaxKind::BarToken
                    | SyntaxKind::CaretToken
                    | SyntaxKind::ExclamationToken
                    | SyntaxKind::TildeToken
                    | SyntaxKind::AmpersandAmpersandToken
                    | SyntaxKind::BarBarToken
                    | SyntaxKind::QuestionToken
                    | SyntaxKind::ColonToken
                    | SyntaxKind::AtToken
                    | SyntaxKind::QuestionQuestionToken
                    | SyntaxKind::BacktickToken
                    | SyntaxKind::HashToken
                    | SyntaxKind::EqualsToken
                    | SyntaxKind::PlusEqualsToken
                    | SyntaxKind::MinusEqualsToken
                    | SyntaxKind::AsteriskEqualsToken
                    | SyntaxKind::AsteriskAsteriskEqualsToken
                    | SyntaxKind::SlashEqualsToken
                    | SyntaxKind::PercentEqualsToken
                    | SyntaxKind::LessThanLessThanEqualsToken
                    | SyntaxKind::GreaterThanGreaterThanEqualsToken
                    | SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken
                    | SyntaxKind::AmpersandEqualsToken
                    | SyntaxKind::BarEqualsToken
                    | SyntaxKind::BarBarEqualsToken
                    | SyntaxKind::AmpersandAmpersandEqualsToken
                    | SyntaxKind::QuestionQuestionEqualsToken
                    | SyntaxKind::CaretEqualsToken
                    | SyntaxKind::Identifier
                    | SyntaxKind::PrivateIdentifier
                    | SyntaxKind::JSDocCommentTextToken
                    | SyntaxKind::BreakKeyword
                    | SyntaxKind::CaseKeyword
                    | SyntaxKind::CatchKeyword
                    | SyntaxKind::ClassKeyword
                    | SyntaxKind::ConstKeyword
                    | SyntaxKind::ContinueKeyword
                    | SyntaxKind::DebuggerKeyword
                    | SyntaxKind::DefaultKeyword
                    | SyntaxKind::DeleteKeyword
                    | SyntaxKind::DoKeyword
                    | SyntaxKind::ElseKeyword
                    | SyntaxKind::EnumKeyword
                    | SyntaxKind::ExportKeyword
                    | SyntaxKind::ExtendsKeyword
                    | SyntaxKind::FalseKeyword
                    | SyntaxKind::FinallyKeyword
                    | SyntaxKind::ForKeyword
                    | SyntaxKind::FunctionKeyword
                    | SyntaxKind::IfKeyword
                    | SyntaxKind::ImportKeyword
                    | SyntaxKind::InKeyword
                    | SyntaxKind::InstanceOfKeyword
                    | SyntaxKind::NewKeyword
                    | SyntaxKind::NullKeyword
                    | SyntaxKind::ReturnKeyword
                    | SyntaxKind::SuperKeyword
                    | SyntaxKind::SwitchKeyword
                    | SyntaxKind::ThisKeyword
                    | SyntaxKind::ThrowKeyword
                    | SyntaxKind::TrueKeyword
                    | SyntaxKind::TryKeyword
                    | SyntaxKind::TypeOfKeyword
                    | SyntaxKind::VarKeyword
                    | SyntaxKind::VoidKeyword
                    | SyntaxKind::WhileKeyword
                    | SyntaxKind::WithKeyword
                    | SyntaxKind::ImplementsKeyword
                    | SyntaxKind::InterfaceKeyword
                    | SyntaxKind::LetKeyword
                    | SyntaxKind::PackageKeyword
                    | SyntaxKind::PrivateKeyword
                    | SyntaxKind::ProtectedKeyword
                    | SyntaxKind::PublicKeyword
                    | SyntaxKind::StaticKeyword
                    | SyntaxKind::YieldKeyword
                    | SyntaxKind::AbstractKeyword
                    | SyntaxKind::AccessorKeyword
                    | SyntaxKind::AsKeyword
                    | SyntaxKind::AssertsKeyword
                    | SyntaxKind::AssertKeyword
                    | SyntaxKind::AnyKeyword
                    | SyntaxKind::AsyncKeyword
                    | SyntaxKind::AwaitKeyword
                    | SyntaxKind::BooleanKeyword
                    | SyntaxKind::ConstructorKeyword
                    | SyntaxKind::DeclareKeyword
                    | SyntaxKind::GetKeyword
                    | SyntaxKind::ImmediateKeyword
                    | SyntaxKind::InferKeyword
                    | SyntaxKind::IntrinsicKeyword
                    | SyntaxKind::IsKeyword
                    | SyntaxKind::KeyOfKeyword
                    | SyntaxKind::ModuleKeyword
                    | SyntaxKind::NamespaceKeyword
                    | SyntaxKind::NeverKeyword
                    | SyntaxKind::OutKeyword
                    | SyntaxKind::ReadonlyKeyword
                    | SyntaxKind::RequireKeyword
                    | SyntaxKind::NumberKeyword
                    | SyntaxKind::ObjectKeyword
                    | SyntaxKind::SatisfiesKeyword
                    | SyntaxKind::SetKeyword
                    | SyntaxKind::StringKeyword
                    | SyntaxKind::SymbolKeyword
                    | SyntaxKind::TypeKeyword
                    | SyntaxKind::UndefinedKeyword
                    | SyntaxKind::UniqueKeyword
                    | SyntaxKind::UnknownKeyword
                    | SyntaxKind::UsingKeyword
                    | SyntaxKind::FromKeyword
                    | SyntaxKind::GlobalKeyword
                    | SyntaxKind::BigIntKeyword
                    | SyntaxKind::OverrideKeyword
                    | SyntaxKind::OfKeyword
                    | SyntaxKind::DeferKeyword
            ),
            Self::Identifier(_) => matches!(kind, SyntaxKind::Identifier),
            Self::PrivateIdentifier(_) => matches!(kind, SyntaxKind::PrivateIdentifier),
            Self::QualifiedName(_) => matches!(kind, SyntaxKind::QualifiedName),
            Self::ComputedPropertyName(_) => matches!(kind, SyntaxKind::ComputedPropertyName),
            Self::Decorator(_) => matches!(kind, SyntaxKind::Decorator),
            Self::EmptyStatement(_) => matches!(kind, SyntaxKind::EmptyStatement),
            Self::IfStatement(_) => matches!(kind, SyntaxKind::IfStatement),
            Self::DoStatement(_) => matches!(kind, SyntaxKind::DoStatement),
            Self::WhileStatement(_) => matches!(kind, SyntaxKind::WhileStatement),
            Self::ForStatement(_) => matches!(kind, SyntaxKind::ForStatement),
            Self::ForInOrOfStatement(_) => matches!(
                kind,
                SyntaxKind::ForInStatement | SyntaxKind::ForOfStatement
            ),
            Self::BreakStatement(_) => matches!(kind, SyntaxKind::BreakStatement),
            Self::ContinueStatement(_) => matches!(kind, SyntaxKind::ContinueStatement),
            Self::ReturnStatement(_) => matches!(kind, SyntaxKind::ReturnStatement),
            Self::WithStatement(_) => matches!(kind, SyntaxKind::WithStatement),
            Self::SwitchStatement(_) => matches!(kind, SyntaxKind::SwitchStatement),
            Self::CaseBlock(_) => matches!(kind, SyntaxKind::CaseBlock),
            Self::CaseOrDefaultClause(_) => {
                matches!(kind, SyntaxKind::CaseClause | SyntaxKind::DefaultClause)
            }
            Self::ThrowStatement(_) => matches!(kind, SyntaxKind::ThrowStatement),
            Self::TryStatement(_) => matches!(kind, SyntaxKind::TryStatement),
            Self::CatchClause(_) => matches!(kind, SyntaxKind::CatchClause),
            Self::DebuggerStatement(_) => matches!(kind, SyntaxKind::DebuggerStatement),
            Self::LabeledStatement(_) => matches!(kind, SyntaxKind::LabeledStatement),
            Self::ExpressionStatement(_) => matches!(kind, SyntaxKind::ExpressionStatement),
            Self::Block(_) => matches!(kind, SyntaxKind::Block),
            Self::VariableStatement(_) => matches!(kind, SyntaxKind::VariableStatement),
            Self::VariableDeclaration(_) => matches!(kind, SyntaxKind::VariableDeclaration),
            Self::VariableDeclarationList(_) => matches!(kind, SyntaxKind::VariableDeclarationList),
            Self::BindingPattern(_) => matches!(
                kind,
                SyntaxKind::ObjectBindingPattern | SyntaxKind::ArrayBindingPattern
            ),
            Self::ParameterDeclaration(_) => matches!(kind, SyntaxKind::Parameter),
            Self::BindingElement(_) => matches!(kind, SyntaxKind::BindingElement),
            Self::MissingDeclaration(_) => matches!(kind, SyntaxKind::MissingDeclaration),
            Self::FunctionDeclaration(_) => matches!(kind, SyntaxKind::FunctionDeclaration),
            Self::ClassDeclaration(_) => matches!(kind, SyntaxKind::ClassDeclaration),
            Self::ClassExpression(_) => matches!(kind, SyntaxKind::ClassExpression),
            Self::HeritageClause(_) => matches!(kind, SyntaxKind::HeritageClause),
            Self::InterfaceDeclaration(_) => matches!(kind, SyntaxKind::InterfaceDeclaration),
            Self::TypeAliasDeclaration(_) => matches!(
                kind,
                SyntaxKind::TypeAliasDeclaration | SyntaxKind::JSTypeAliasDeclaration
            ),
            Self::EnumMember(_) => matches!(kind, SyntaxKind::EnumMember),
            Self::EnumDeclaration(_) => matches!(kind, SyntaxKind::EnumDeclaration),
            Self::ModuleBlock(_) => matches!(kind, SyntaxKind::ModuleBlock),
            Self::NotEmittedStatement(_) => matches!(kind, SyntaxKind::NotEmittedStatement),
            Self::NotEmittedTypeElement(_) => matches!(kind, SyntaxKind::NotEmittedTypeElement),
            Self::ImportDeclaration(_) => matches!(
                kind,
                SyntaxKind::ImportDeclaration | SyntaxKind::JSImportDeclaration
            ),
            Self::ExternalModuleReference(_) => matches!(kind, SyntaxKind::ExternalModuleReference),
            Self::NamespaceImport(_) => matches!(kind, SyntaxKind::NamespaceImport),
            Self::NamedImports(_) => matches!(kind, SyntaxKind::NamedImports),
            Self::ExportAssignment(_) => matches!(kind, SyntaxKind::ExportAssignment),
            Self::NamespaceExportDeclaration(_) => {
                matches!(kind, SyntaxKind::NamespaceExportDeclaration)
            }
            Self::NamespaceExport(_) => matches!(kind, SyntaxKind::NamespaceExport),
            Self::NamedExports(_) => matches!(kind, SyntaxKind::NamedExports),
            Self::ExportSpecifier(_) => matches!(kind, SyntaxKind::ExportSpecifier),
            Self::CallSignatureDeclaration(_) => matches!(kind, SyntaxKind::CallSignature),
            Self::ConstructSignatureDeclaration(_) => {
                matches!(kind, SyntaxKind::ConstructSignature)
            }
            Self::ConstructorDeclaration(_) => matches!(kind, SyntaxKind::Constructor),
            Self::GetAccessorDeclaration(_) => matches!(kind, SyntaxKind::GetAccessor),
            Self::SetAccessorDeclaration(_) => matches!(kind, SyntaxKind::SetAccessor),
            Self::IndexSignatureDeclaration(_) => matches!(kind, SyntaxKind::IndexSignature),
            Self::MethodSignatureDeclaration(_) => matches!(kind, SyntaxKind::MethodSignature),
            Self::MethodDeclaration(_) => matches!(kind, SyntaxKind::MethodDeclaration),
            Self::PropertySignatureDeclaration(_) => matches!(kind, SyntaxKind::PropertySignature),
            Self::PropertyDeclaration(_) => matches!(kind, SyntaxKind::PropertyDeclaration),
            Self::SemicolonClassElement(_) => matches!(kind, SyntaxKind::SemicolonClassElement),
            Self::ClassStaticBlockDeclaration(_) => {
                matches!(kind, SyntaxKind::ClassStaticBlockDeclaration)
            }
            Self::OmittedExpression(_) => matches!(kind, SyntaxKind::OmittedExpression),
            Self::KeywordExpression(_) => matches!(
                kind,
                SyntaxKind::NullKeyword
                    | SyntaxKind::TrueKeyword
                    | SyntaxKind::FalseKeyword
                    | SyntaxKind::ThisKeyword
                    | SyntaxKind::SuperKeyword
                    | SyntaxKind::ImportKeyword
            ),
            Self::StringLiteral(_) => matches!(kind, SyntaxKind::StringLiteral),
            Self::NumericLiteral(_) => matches!(kind, SyntaxKind::NumericLiteral),
            Self::BigIntLiteral(_) => matches!(kind, SyntaxKind::BigIntLiteral),
            Self::RegularExpressionLiteral(_) => {
                matches!(kind, SyntaxKind::RegularExpressionLiteral)
            }
            Self::NoSubstitutionTemplateLiteral(_) => {
                matches!(kind, SyntaxKind::NoSubstitutionTemplateLiteral)
            }
            Self::BinaryExpression(_) => matches!(kind, SyntaxKind::BinaryExpression),
            Self::PrefixUnaryExpression(_) => matches!(kind, SyntaxKind::PrefixUnaryExpression),
            Self::PostfixUnaryExpression(_) => matches!(kind, SyntaxKind::PostfixUnaryExpression),
            Self::YieldExpression(_) => matches!(kind, SyntaxKind::YieldExpression),
            Self::ArrowFunction(_) => matches!(kind, SyntaxKind::ArrowFunction),
            Self::FunctionExpression(_) => matches!(kind, SyntaxKind::FunctionExpression),
            Self::AsExpression(_) => matches!(kind, SyntaxKind::AsExpression),
            Self::SatisfiesExpression(_) => matches!(kind, SyntaxKind::SatisfiesExpression),
            Self::ConditionalExpression(_) => matches!(kind, SyntaxKind::ConditionalExpression),
            Self::PropertyAccessExpression(_) => {
                matches!(kind, SyntaxKind::PropertyAccessExpression)
            }
            Self::ElementAccessExpression(_) => matches!(kind, SyntaxKind::ElementAccessExpression),
            Self::CallExpression(_) => matches!(kind, SyntaxKind::CallExpression),
            Self::NewExpression(_) => matches!(kind, SyntaxKind::NewExpression),
            Self::MetaProperty(_) => matches!(kind, SyntaxKind::MetaProperty),
            Self::NonNullExpression(_) => matches!(kind, SyntaxKind::NonNullExpression),
            Self::SpreadElement(_) => matches!(kind, SyntaxKind::SpreadElement),
            Self::TemplateExpression(_) => matches!(kind, SyntaxKind::TemplateExpression),
            Self::TemplateSpan(_) => matches!(kind, SyntaxKind::TemplateSpan),
            Self::TaggedTemplateExpression(_) => {
                matches!(kind, SyntaxKind::TaggedTemplateExpression)
            }
            Self::ParenthesizedExpression(_) => matches!(kind, SyntaxKind::ParenthesizedExpression),
            Self::ArrayLiteralExpression(_) => matches!(kind, SyntaxKind::ArrayLiteralExpression),
            Self::ObjectLiteralExpression(_) => matches!(kind, SyntaxKind::ObjectLiteralExpression),
            Self::SpreadAssignment(_) => matches!(kind, SyntaxKind::SpreadAssignment),
            Self::PropertyAssignment(_) => matches!(kind, SyntaxKind::PropertyAssignment),
            Self::ShorthandPropertyAssignment(_) => {
                matches!(kind, SyntaxKind::ShorthandPropertyAssignment)
            }
            Self::DeleteExpression(_) => matches!(kind, SyntaxKind::DeleteExpression),
            Self::TypeOfExpression(_) => matches!(kind, SyntaxKind::TypeOfExpression),
            Self::VoidExpression(_) => matches!(kind, SyntaxKind::VoidExpression),
            Self::AwaitExpression(_) => matches!(kind, SyntaxKind::AwaitExpression),
            Self::TypeAssertion(_) => matches!(kind, SyntaxKind::TypeAssertionExpression),
            Self::KeywordTypeNode(_) => matches!(
                kind,
                SyntaxKind::AnyKeyword
                    | SyntaxKind::BigIntKeyword
                    | SyntaxKind::BooleanKeyword
                    | SyntaxKind::IntrinsicKeyword
                    | SyntaxKind::NeverKeyword
                    | SyntaxKind::NumberKeyword
                    | SyntaxKind::ObjectKeyword
                    | SyntaxKind::StringKeyword
                    | SyntaxKind::SymbolKeyword
                    | SyntaxKind::UndefinedKeyword
                    | SyntaxKind::UnknownKeyword
                    | SyntaxKind::VoidKeyword
            ),
            Self::UnionTypeNode(_) => matches!(kind, SyntaxKind::UnionType),
            Self::IntersectionTypeNode(_) => matches!(kind, SyntaxKind::IntersectionType),
            Self::ConditionalTypeNode(_) => matches!(kind, SyntaxKind::ConditionalType),
            Self::TypeOperatorNode(_) => matches!(kind, SyntaxKind::TypeOperator),
            Self::InferTypeNode(_) => matches!(kind, SyntaxKind::InferType),
            Self::ArrayTypeNode(_) => matches!(kind, SyntaxKind::ArrayType),
            Self::IndexedAccessTypeNode(_) => matches!(kind, SyntaxKind::IndexedAccessType),
            Self::TypeReferenceNode(_) => matches!(kind, SyntaxKind::TypeReference),
            Self::ExpressionWithTypeArguments(_) => {
                matches!(kind, SyntaxKind::ExpressionWithTypeArguments)
            }
            Self::LiteralTypeNode(_) => matches!(kind, SyntaxKind::LiteralType),
            Self::ThisTypeNode(_) => matches!(kind, SyntaxKind::ThisType),
            Self::TypePredicateNode(_) => matches!(kind, SyntaxKind::TypePredicate),
            Self::ImportAttribute(_) => matches!(kind, SyntaxKind::ImportAttribute),
            Self::ImportAttributes(_) => matches!(kind, SyntaxKind::ImportAttributes),
            Self::TypeQueryNode(_) => matches!(kind, SyntaxKind::TypeQuery),
            Self::MappedTypeNode(_) => matches!(kind, SyntaxKind::MappedType),
            Self::TypeLiteralNode(_) => matches!(kind, SyntaxKind::TypeLiteral),
            Self::TupleTypeNode(_) => matches!(kind, SyntaxKind::TupleType),
            Self::NamedTupleMember(_) => matches!(kind, SyntaxKind::NamedTupleMember),
            Self::OptionalTypeNode(_) => matches!(kind, SyntaxKind::OptionalType),
            Self::RestTypeNode(_) => matches!(kind, SyntaxKind::RestType),
            Self::ParenthesizedTypeNode(_) => matches!(kind, SyntaxKind::ParenthesizedType),
            Self::FunctionTypeNode(_) => matches!(kind, SyntaxKind::FunctionType),
            Self::ConstructorTypeNode(_) => matches!(kind, SyntaxKind::ConstructorType),
            Self::TemplateHead(_) => matches!(kind, SyntaxKind::TemplateHead),
            Self::TemplateMiddle(_) => matches!(kind, SyntaxKind::TemplateMiddle),
            Self::TemplateTail(_) => matches!(kind, SyntaxKind::TemplateTail),
            Self::TemplateLiteralTypeNode(_) => matches!(kind, SyntaxKind::TemplateLiteralType),
            Self::TemplateLiteralTypeSpan(_) => matches!(kind, SyntaxKind::TemplateLiteralTypeSpan),
            Self::SyntheticExpression(_) => matches!(kind, SyntaxKind::SyntheticExpression),
            Self::PartiallyEmittedExpression(_) => {
                matches!(kind, SyntaxKind::PartiallyEmittedExpression)
            }
            Self::JsxElement(_) => matches!(kind, SyntaxKind::JsxElement),
            Self::JsxAttributes(_) => matches!(kind, SyntaxKind::JsxAttributes),
            Self::JsxNamespacedName(_) => matches!(kind, SyntaxKind::JsxNamespacedName),
            Self::JsxOpeningElement(_) => matches!(kind, SyntaxKind::JsxOpeningElement),
            Self::JsxSelfClosingElement(_) => matches!(kind, SyntaxKind::JsxSelfClosingElement),
            Self::JsxFragment(_) => matches!(kind, SyntaxKind::JsxFragment),
            Self::JsxOpeningFragment(_) => matches!(kind, SyntaxKind::JsxOpeningFragment),
            Self::JsxClosingFragment(_) => matches!(kind, SyntaxKind::JsxClosingFragment),
            Self::JsxAttribute(_) => matches!(kind, SyntaxKind::JsxAttribute),
            Self::JsxSpreadAttribute(_) => matches!(kind, SyntaxKind::JsxSpreadAttribute),
            Self::JsxClosingElement(_) => matches!(kind, SyntaxKind::JsxClosingElement),
            Self::JsxExpression(_) => matches!(kind, SyntaxKind::JsxExpression),
            Self::JsxText(_) => matches!(kind, SyntaxKind::JsxText),
            Self::SyntaxList(_) => matches!(kind, SyntaxKind::SyntaxList),
            Self::JSDoc(_) => matches!(kind, SyntaxKind::JSDoc),
            Self::JSDocTypeExpression(_) => matches!(kind, SyntaxKind::JSDocTypeExpression),
            Self::JSDocNonNullableType(_) => matches!(kind, SyntaxKind::JSDocNonNullableType),
            Self::JSDocNullableType(_) => matches!(kind, SyntaxKind::JSDocNullableType),
            Self::JSDocAllType(_) => matches!(kind, SyntaxKind::JSDocAllType),
            Self::JSDocVariadicType(_) => matches!(kind, SyntaxKind::JSDocVariadicType),
            Self::JSDocOptionalType(_) => matches!(kind, SyntaxKind::JSDocOptionalType),
            Self::JSDocTypeTag(_) => matches!(kind, SyntaxKind::JSDocTypeTag),
            Self::JSDocUnknownTag(_) => matches!(kind, SyntaxKind::JSDocUnknownTag),
            Self::JSDocTemplateTag(_) => matches!(kind, SyntaxKind::JSDocTemplateTag),
            Self::JSDocReturnTag(_) => matches!(kind, SyntaxKind::JSDocReturnTag),
            Self::JSDocPublicTag(_) => matches!(kind, SyntaxKind::JSDocPublicTag),
            Self::JSDocPrivateTag(_) => matches!(kind, SyntaxKind::JSDocPrivateTag),
            Self::JSDocProtectedTag(_) => matches!(kind, SyntaxKind::JSDocProtectedTag),
            Self::JSDocReadonlyTag(_) => matches!(kind, SyntaxKind::JSDocReadonlyTag),
            Self::JSDocOverrideTag(_) => matches!(kind, SyntaxKind::JSDocOverrideTag),
            Self::JSDocDeprecatedTag(_) => matches!(kind, SyntaxKind::JSDocDeprecatedTag),
            Self::JSDocSeeTag(_) => matches!(kind, SyntaxKind::JSDocSeeTag),
            Self::JSDocImplementsTag(_) => matches!(kind, SyntaxKind::JSDocImplementsTag),
            Self::JSDocAugmentsTag(_) => matches!(kind, SyntaxKind::JSDocAugmentsTag),
            Self::JSDocSatisfiesTag(_) => matches!(kind, SyntaxKind::JSDocSatisfiesTag),
            Self::JSDocThrowsTag(_) => matches!(kind, SyntaxKind::JSDocThrowsTag),
            Self::JSDocThisTag(_) => matches!(kind, SyntaxKind::JSDocThisTag),
            Self::JSDocImportTag(_) => matches!(kind, SyntaxKind::JSDocImportTag),
            Self::JSDocCallbackTag(_) => matches!(kind, SyntaxKind::JSDocCallbackTag),
            Self::JSDocOverloadTag(_) => matches!(kind, SyntaxKind::JSDocOverloadTag),
            Self::JSDocTypedefTag(_) => matches!(kind, SyntaxKind::JSDocTypedefTag),
            Self::JSDocSignature(_) => matches!(kind, SyntaxKind::JSDocSignature),
            Self::JSDocNameReference(_) => matches!(kind, SyntaxKind::JSDocNameReference),
            Self::SourceFile(_) => matches!(kind, SyntaxKind::SourceFile),
            Self::ModuleDeclaration(_) => matches!(kind, SyntaxKind::ModuleDeclaration),
            Self::ImportEqualsDeclaration(_) => matches!(kind, SyntaxKind::ImportEqualsDeclaration),
            Self::ExportDeclaration(_) => matches!(kind, SyntaxKind::ExportDeclaration),
            Self::ImportTypeNode(_) => matches!(kind, SyntaxKind::ImportType),
            Self::ImportClause(_) => matches!(kind, SyntaxKind::ImportClause),
            Self::ImportSpecifier(_) => matches!(kind, SyntaxKind::ImportSpecifier),
            Self::JSDocText(_) => matches!(kind, SyntaxKind::JSDocText),
            Self::JSDocLink(_) => matches!(kind, SyntaxKind::JSDocLink),
            Self::JSDocLinkPlain(_) => matches!(kind, SyntaxKind::JSDocLinkPlain),
            Self::JSDocLinkCode(_) => matches!(kind, SyntaxKind::JSDocLinkCode),
            Self::TypeParameterDeclaration(_) => matches!(kind, SyntaxKind::TypeParameter),
            Self::SyntheticReferenceExpression(_) => {
                matches!(kind, SyntaxKind::SyntheticReferenceExpression)
            }
            Self::JSDocTypeLiteral(_) => matches!(kind, SyntaxKind::JSDocTypeLiteral),
            Self::JSDocParameterOrPropertyTag(_) => matches!(
                kind,
                SyntaxKind::JSDocParameterTag | SyntaxKind::JSDocPropertyTag
            ),
        }
    }
}
