// Generated by cargo xtask gen from the pinned SchemaAPI; do not edit.
// Upstream: 1f70213d4922b434345f639b441681e470c7cfc1
// upstream: tsc/internal/ast/kind_generated.go

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
pub enum SyntaxKind {
    Unknown = 0,
    EndOfFile = 1,
    SingleLineCommentTrivia = 2,
    MultiLineCommentTrivia = 3,
    NewLineTrivia = 4,
    WhitespaceTrivia = 5,
    ConflictMarkerTrivia = 6,
    NonTextFileMarkerTrivia = 7,
    NumericLiteral = 8,
    BigIntLiteral = 9,
    StringLiteral = 10,
    JsxText = 11,
    JsxTextAllWhiteSpaces = 12,
    RegularExpressionLiteral = 13,
    NoSubstitutionTemplateLiteral = 14,
    TemplateHead = 15,
    TemplateMiddle = 16,
    TemplateTail = 17,
    OpenBraceToken = 18,
    CloseBraceToken = 19,
    OpenParenToken = 20,
    CloseParenToken = 21,
    OpenBracketToken = 22,
    CloseBracketToken = 23,
    DotToken = 24,
    DotDotDotToken = 25,
    SemicolonToken = 26,
    CommaToken = 27,
    QuestionDotToken = 28,
    LessThanToken = 29,
    LessThanSlashToken = 30,
    GreaterThanToken = 31,
    LessThanEqualsToken = 32,
    GreaterThanEqualsToken = 33,
    EqualsEqualsToken = 34,
    ExclamationEqualsToken = 35,
    EqualsEqualsEqualsToken = 36,
    ExclamationEqualsEqualsToken = 37,
    EqualsGreaterThanToken = 38,
    PlusToken = 39,
    MinusToken = 40,
    AsteriskToken = 41,
    AsteriskAsteriskToken = 42,
    SlashToken = 43,
    PercentToken = 44,
    PlusPlusToken = 45,
    MinusMinusToken = 46,
    LessThanLessThanToken = 47,
    GreaterThanGreaterThanToken = 48,
    GreaterThanGreaterThanGreaterThanToken = 49,
    AmpersandToken = 50,
    BarToken = 51,
    CaretToken = 52,
    ExclamationToken = 53,
    TildeToken = 54,
    AmpersandAmpersandToken = 55,
    BarBarToken = 56,
    QuestionToken = 57,
    ColonToken = 58,
    AtToken = 59,
    QuestionQuestionToken = 60,
    BacktickToken = 61,
    HashToken = 62,
    EqualsToken = 63,
    PlusEqualsToken = 64,
    MinusEqualsToken = 65,
    AsteriskEqualsToken = 66,
    AsteriskAsteriskEqualsToken = 67,
    SlashEqualsToken = 68,
    PercentEqualsToken = 69,
    LessThanLessThanEqualsToken = 70,
    GreaterThanGreaterThanEqualsToken = 71,
    GreaterThanGreaterThanGreaterThanEqualsToken = 72,
    AmpersandEqualsToken = 73,
    BarEqualsToken = 74,
    BarBarEqualsToken = 75,
    AmpersandAmpersandEqualsToken = 76,
    QuestionQuestionEqualsToken = 77,
    CaretEqualsToken = 78,
    Identifier = 79,
    PrivateIdentifier = 80,
    JSDocCommentTextToken = 81,
    BreakKeyword = 82,
    CaseKeyword = 83,
    CatchKeyword = 84,
    ClassKeyword = 85,
    ConstKeyword = 86,
    ContinueKeyword = 87,
    DebuggerKeyword = 88,
    DefaultKeyword = 89,
    DeleteKeyword = 90,
    DoKeyword = 91,
    ElseKeyword = 92,
    EnumKeyword = 93,
    ExportKeyword = 94,
    ExtendsKeyword = 95,
    FalseKeyword = 96,
    FinallyKeyword = 97,
    ForKeyword = 98,
    FunctionKeyword = 99,
    IfKeyword = 100,
    ImportKeyword = 101,
    InKeyword = 102,
    InstanceOfKeyword = 103,
    NewKeyword = 104,
    NullKeyword = 105,
    ReturnKeyword = 106,
    SuperKeyword = 107,
    SwitchKeyword = 108,
    ThisKeyword = 109,
    ThrowKeyword = 110,
    TrueKeyword = 111,
    TryKeyword = 112,
    TypeOfKeyword = 113,
    VarKeyword = 114,
    VoidKeyword = 115,
    WhileKeyword = 116,
    WithKeyword = 117,
    ImplementsKeyword = 118,
    InterfaceKeyword = 119,
    LetKeyword = 120,
    PackageKeyword = 121,
    PrivateKeyword = 122,
    ProtectedKeyword = 123,
    PublicKeyword = 124,
    StaticKeyword = 125,
    YieldKeyword = 126,
    AbstractKeyword = 127,
    AccessorKeyword = 128,
    AsKeyword = 129,
    AssertsKeyword = 130,
    AssertKeyword = 131,
    AnyKeyword = 132,
    AsyncKeyword = 133,
    AwaitKeyword = 134,
    BooleanKeyword = 135,
    ConstructorKeyword = 136,
    DeclareKeyword = 137,
    GetKeyword = 138,
    ImmediateKeyword = 139,
    InferKeyword = 140,
    IntrinsicKeyword = 141,
    IsKeyword = 142,
    KeyOfKeyword = 143,
    ModuleKeyword = 144,
    NamespaceKeyword = 145,
    NeverKeyword = 146,
    OutKeyword = 147,
    ReadonlyKeyword = 148,
    RequireKeyword = 149,
    NumberKeyword = 150,
    ObjectKeyword = 151,
    SatisfiesKeyword = 152,
    SetKeyword = 153,
    StringKeyword = 154,
    SymbolKeyword = 155,
    TypeKeyword = 156,
    UndefinedKeyword = 157,
    UniqueKeyword = 158,
    UnknownKeyword = 159,
    UsingKeyword = 160,
    FromKeyword = 161,
    GlobalKeyword = 162,
    BigIntKeyword = 163,
    OverrideKeyword = 164,
    OfKeyword = 165,
    DeferKeyword = 166,
    QualifiedName = 167,
    ComputedPropertyName = 168,
    TypeParameter = 169,
    Parameter = 170,
    Decorator = 171,
    PropertySignature = 172,
    PropertyDeclaration = 173,
    MethodSignature = 174,
    MethodDeclaration = 175,
    ClassStaticBlockDeclaration = 176,
    Constructor = 177,
    GetAccessor = 178,
    SetAccessor = 179,
    CallSignature = 180,
    ConstructSignature = 181,
    IndexSignature = 182,
    TypePredicate = 183,
    TypeReference = 184,
    FunctionType = 185,
    ConstructorType = 186,
    TypeQuery = 187,
    TypeLiteral = 188,
    ArrayType = 189,
    TupleType = 190,
    OptionalType = 191,
    RestType = 192,
    UnionType = 193,
    IntersectionType = 194,
    ConditionalType = 195,
    InferType = 196,
    ParenthesizedType = 197,
    ThisType = 198,
    TypeOperator = 199,
    IndexedAccessType = 200,
    MappedType = 201,
    LiteralType = 202,
    NamedTupleMember = 203,
    TemplateLiteralType = 204,
    TemplateLiteralTypeSpan = 205,
    ImportType = 206,
    ObjectBindingPattern = 207,
    ArrayBindingPattern = 208,
    BindingElement = 209,
    ArrayLiteralExpression = 210,
    ObjectLiteralExpression = 211,
    PropertyAccessExpression = 212,
    ElementAccessExpression = 213,
    CallExpression = 214,
    NewExpression = 215,
    TaggedTemplateExpression = 216,
    TypeAssertionExpression = 217,
    ParenthesizedExpression = 218,
    FunctionExpression = 219,
    ArrowFunction = 220,
    DeleteExpression = 221,
    TypeOfExpression = 222,
    VoidExpression = 223,
    AwaitExpression = 224,
    PrefixUnaryExpression = 225,
    PostfixUnaryExpression = 226,
    BinaryExpression = 227,
    ConditionalExpression = 228,
    TemplateExpression = 229,
    YieldExpression = 230,
    SpreadElement = 231,
    ClassExpression = 232,
    OmittedExpression = 233,
    ExpressionWithTypeArguments = 234,
    AsExpression = 235,
    NonNullExpression = 236,
    MetaProperty = 237,
    SyntheticExpression = 238,
    SatisfiesExpression = 239,
    TemplateSpan = 240,
    SemicolonClassElement = 241,
    Block = 242,
    EmptyStatement = 243,
    VariableStatement = 244,
    ExpressionStatement = 245,
    IfStatement = 246,
    DoStatement = 247,
    WhileStatement = 248,
    ForStatement = 249,
    ForInStatement = 250,
    ForOfStatement = 251,
    ContinueStatement = 252,
    BreakStatement = 253,
    ReturnStatement = 254,
    WithStatement = 255,
    SwitchStatement = 256,
    LabeledStatement = 257,
    ThrowStatement = 258,
    TryStatement = 259,
    DebuggerStatement = 260,
    VariableDeclaration = 261,
    VariableDeclarationList = 262,
    FunctionDeclaration = 263,
    ClassDeclaration = 264,
    InterfaceDeclaration = 265,
    TypeAliasDeclaration = 266,
    EnumDeclaration = 267,
    ModuleDeclaration = 268,
    ModuleBlock = 269,
    CaseBlock = 270,
    NamespaceExportDeclaration = 271,
    ImportEqualsDeclaration = 272,
    ImportDeclaration = 273,
    ImportClause = 274,
    NamespaceImport = 275,
    NamedImports = 276,
    ImportSpecifier = 277,
    ExportAssignment = 278,
    ExportDeclaration = 279,
    NamedExports = 280,
    NamespaceExport = 281,
    ExportSpecifier = 282,
    MissingDeclaration = 283,
    ExternalModuleReference = 284,
    JsxElement = 285,
    JsxSelfClosingElement = 286,
    JsxOpeningElement = 287,
    JsxClosingElement = 288,
    JsxFragment = 289,
    JsxOpeningFragment = 290,
    JsxClosingFragment = 291,
    JsxAttribute = 292,
    JsxAttributes = 293,
    JsxSpreadAttribute = 294,
    JsxExpression = 295,
    JsxNamespacedName = 296,
    CaseClause = 297,
    DefaultClause = 298,
    HeritageClause = 299,
    CatchClause = 300,
    ImportAttributes = 301,
    ImportAttribute = 302,
    PropertyAssignment = 303,
    ShorthandPropertyAssignment = 304,
    SpreadAssignment = 305,
    EnumMember = 306,
    SourceFile = 307,
    JSDocTypeExpression = 308,
    JSDocNameReference = 309,
    JSDocAllType = 310,
    JSDocNullableType = 311,
    JSDocNonNullableType = 312,
    JSDocOptionalType = 313,
    JSDocVariadicType = 314,
    JSDoc = 315,
    JSDocText = 316,
    JSDocTypeLiteral = 317,
    JSDocSignature = 318,
    JSDocLink = 319,
    JSDocLinkCode = 320,
    JSDocLinkPlain = 321,
    JSDocUnknownTag = 322,
    JSDocAugmentsTag = 323,
    JSDocImplementsTag = 324,
    JSDocDeprecatedTag = 325,
    JSDocPublicTag = 326,
    JSDocPrivateTag = 327,
    JSDocProtectedTag = 328,
    JSDocReadonlyTag = 329,
    JSDocOverrideTag = 330,
    JSDocCallbackTag = 331,
    JSDocOverloadTag = 332,
    JSDocParameterTag = 333,
    JSDocReturnTag = 334,
    JSDocThisTag = 335,
    JSDocTypeTag = 336,
    JSDocTemplateTag = 337,
    JSDocTypedefTag = 338,
    JSDocSeeTag = 339,
    JSDocPropertyTag = 340,
    JSDocThrowsTag = 341,
    JSDocSatisfiesTag = 342,
    JSDocImportTag = 343,
    SyntaxList = 344,
    JSTypeAliasDeclaration = 345,
    JSImportDeclaration = 346,
    NotEmittedStatement = 347,
    PartiallyEmittedExpression = 348,
    SyntheticReferenceExpression = 349,
    NotEmittedTypeElement = 350,
}
impl SyntaxKind {
    pub const COUNT: usize = 351;
    pub const ALL: &'static [Self] = &[
        Self::Unknown,
        Self::EndOfFile,
        Self::SingleLineCommentTrivia,
        Self::MultiLineCommentTrivia,
        Self::NewLineTrivia,
        Self::WhitespaceTrivia,
        Self::ConflictMarkerTrivia,
        Self::NonTextFileMarkerTrivia,
        Self::NumericLiteral,
        Self::BigIntLiteral,
        Self::StringLiteral,
        Self::JsxText,
        Self::JsxTextAllWhiteSpaces,
        Self::RegularExpressionLiteral,
        Self::NoSubstitutionTemplateLiteral,
        Self::TemplateHead,
        Self::TemplateMiddle,
        Self::TemplateTail,
        Self::OpenBraceToken,
        Self::CloseBraceToken,
        Self::OpenParenToken,
        Self::CloseParenToken,
        Self::OpenBracketToken,
        Self::CloseBracketToken,
        Self::DotToken,
        Self::DotDotDotToken,
        Self::SemicolonToken,
        Self::CommaToken,
        Self::QuestionDotToken,
        Self::LessThanToken,
        Self::LessThanSlashToken,
        Self::GreaterThanToken,
        Self::LessThanEqualsToken,
        Self::GreaterThanEqualsToken,
        Self::EqualsEqualsToken,
        Self::ExclamationEqualsToken,
        Self::EqualsEqualsEqualsToken,
        Self::ExclamationEqualsEqualsToken,
        Self::EqualsGreaterThanToken,
        Self::PlusToken,
        Self::MinusToken,
        Self::AsteriskToken,
        Self::AsteriskAsteriskToken,
        Self::SlashToken,
        Self::PercentToken,
        Self::PlusPlusToken,
        Self::MinusMinusToken,
        Self::LessThanLessThanToken,
        Self::GreaterThanGreaterThanToken,
        Self::GreaterThanGreaterThanGreaterThanToken,
        Self::AmpersandToken,
        Self::BarToken,
        Self::CaretToken,
        Self::ExclamationToken,
        Self::TildeToken,
        Self::AmpersandAmpersandToken,
        Self::BarBarToken,
        Self::QuestionToken,
        Self::ColonToken,
        Self::AtToken,
        Self::QuestionQuestionToken,
        Self::BacktickToken,
        Self::HashToken,
        Self::EqualsToken,
        Self::PlusEqualsToken,
        Self::MinusEqualsToken,
        Self::AsteriskEqualsToken,
        Self::AsteriskAsteriskEqualsToken,
        Self::SlashEqualsToken,
        Self::PercentEqualsToken,
        Self::LessThanLessThanEqualsToken,
        Self::GreaterThanGreaterThanEqualsToken,
        Self::GreaterThanGreaterThanGreaterThanEqualsToken,
        Self::AmpersandEqualsToken,
        Self::BarEqualsToken,
        Self::BarBarEqualsToken,
        Self::AmpersandAmpersandEqualsToken,
        Self::QuestionQuestionEqualsToken,
        Self::CaretEqualsToken,
        Self::Identifier,
        Self::PrivateIdentifier,
        Self::JSDocCommentTextToken,
        Self::BreakKeyword,
        Self::CaseKeyword,
        Self::CatchKeyword,
        Self::ClassKeyword,
        Self::ConstKeyword,
        Self::ContinueKeyword,
        Self::DebuggerKeyword,
        Self::DefaultKeyword,
        Self::DeleteKeyword,
        Self::DoKeyword,
        Self::ElseKeyword,
        Self::EnumKeyword,
        Self::ExportKeyword,
        Self::ExtendsKeyword,
        Self::FalseKeyword,
        Self::FinallyKeyword,
        Self::ForKeyword,
        Self::FunctionKeyword,
        Self::IfKeyword,
        Self::ImportKeyword,
        Self::InKeyword,
        Self::InstanceOfKeyword,
        Self::NewKeyword,
        Self::NullKeyword,
        Self::ReturnKeyword,
        Self::SuperKeyword,
        Self::SwitchKeyword,
        Self::ThisKeyword,
        Self::ThrowKeyword,
        Self::TrueKeyword,
        Self::TryKeyword,
        Self::TypeOfKeyword,
        Self::VarKeyword,
        Self::VoidKeyword,
        Self::WhileKeyword,
        Self::WithKeyword,
        Self::ImplementsKeyword,
        Self::InterfaceKeyword,
        Self::LetKeyword,
        Self::PackageKeyword,
        Self::PrivateKeyword,
        Self::ProtectedKeyword,
        Self::PublicKeyword,
        Self::StaticKeyword,
        Self::YieldKeyword,
        Self::AbstractKeyword,
        Self::AccessorKeyword,
        Self::AsKeyword,
        Self::AssertsKeyword,
        Self::AssertKeyword,
        Self::AnyKeyword,
        Self::AsyncKeyword,
        Self::AwaitKeyword,
        Self::BooleanKeyword,
        Self::ConstructorKeyword,
        Self::DeclareKeyword,
        Self::GetKeyword,
        Self::ImmediateKeyword,
        Self::InferKeyword,
        Self::IntrinsicKeyword,
        Self::IsKeyword,
        Self::KeyOfKeyword,
        Self::ModuleKeyword,
        Self::NamespaceKeyword,
        Self::NeverKeyword,
        Self::OutKeyword,
        Self::ReadonlyKeyword,
        Self::RequireKeyword,
        Self::NumberKeyword,
        Self::ObjectKeyword,
        Self::SatisfiesKeyword,
        Self::SetKeyword,
        Self::StringKeyword,
        Self::SymbolKeyword,
        Self::TypeKeyword,
        Self::UndefinedKeyword,
        Self::UniqueKeyword,
        Self::UnknownKeyword,
        Self::UsingKeyword,
        Self::FromKeyword,
        Self::GlobalKeyword,
        Self::BigIntKeyword,
        Self::OverrideKeyword,
        Self::OfKeyword,
        Self::DeferKeyword,
        Self::QualifiedName,
        Self::ComputedPropertyName,
        Self::TypeParameter,
        Self::Parameter,
        Self::Decorator,
        Self::PropertySignature,
        Self::PropertyDeclaration,
        Self::MethodSignature,
        Self::MethodDeclaration,
        Self::ClassStaticBlockDeclaration,
        Self::Constructor,
        Self::GetAccessor,
        Self::SetAccessor,
        Self::CallSignature,
        Self::ConstructSignature,
        Self::IndexSignature,
        Self::TypePredicate,
        Self::TypeReference,
        Self::FunctionType,
        Self::ConstructorType,
        Self::TypeQuery,
        Self::TypeLiteral,
        Self::ArrayType,
        Self::TupleType,
        Self::OptionalType,
        Self::RestType,
        Self::UnionType,
        Self::IntersectionType,
        Self::ConditionalType,
        Self::InferType,
        Self::ParenthesizedType,
        Self::ThisType,
        Self::TypeOperator,
        Self::IndexedAccessType,
        Self::MappedType,
        Self::LiteralType,
        Self::NamedTupleMember,
        Self::TemplateLiteralType,
        Self::TemplateLiteralTypeSpan,
        Self::ImportType,
        Self::ObjectBindingPattern,
        Self::ArrayBindingPattern,
        Self::BindingElement,
        Self::ArrayLiteralExpression,
        Self::ObjectLiteralExpression,
        Self::PropertyAccessExpression,
        Self::ElementAccessExpression,
        Self::CallExpression,
        Self::NewExpression,
        Self::TaggedTemplateExpression,
        Self::TypeAssertionExpression,
        Self::ParenthesizedExpression,
        Self::FunctionExpression,
        Self::ArrowFunction,
        Self::DeleteExpression,
        Self::TypeOfExpression,
        Self::VoidExpression,
        Self::AwaitExpression,
        Self::PrefixUnaryExpression,
        Self::PostfixUnaryExpression,
        Self::BinaryExpression,
        Self::ConditionalExpression,
        Self::TemplateExpression,
        Self::YieldExpression,
        Self::SpreadElement,
        Self::ClassExpression,
        Self::OmittedExpression,
        Self::ExpressionWithTypeArguments,
        Self::AsExpression,
        Self::NonNullExpression,
        Self::MetaProperty,
        Self::SyntheticExpression,
        Self::SatisfiesExpression,
        Self::TemplateSpan,
        Self::SemicolonClassElement,
        Self::Block,
        Self::EmptyStatement,
        Self::VariableStatement,
        Self::ExpressionStatement,
        Self::IfStatement,
        Self::DoStatement,
        Self::WhileStatement,
        Self::ForStatement,
        Self::ForInStatement,
        Self::ForOfStatement,
        Self::ContinueStatement,
        Self::BreakStatement,
        Self::ReturnStatement,
        Self::WithStatement,
        Self::SwitchStatement,
        Self::LabeledStatement,
        Self::ThrowStatement,
        Self::TryStatement,
        Self::DebuggerStatement,
        Self::VariableDeclaration,
        Self::VariableDeclarationList,
        Self::FunctionDeclaration,
        Self::ClassDeclaration,
        Self::InterfaceDeclaration,
        Self::TypeAliasDeclaration,
        Self::EnumDeclaration,
        Self::ModuleDeclaration,
        Self::ModuleBlock,
        Self::CaseBlock,
        Self::NamespaceExportDeclaration,
        Self::ImportEqualsDeclaration,
        Self::ImportDeclaration,
        Self::ImportClause,
        Self::NamespaceImport,
        Self::NamedImports,
        Self::ImportSpecifier,
        Self::ExportAssignment,
        Self::ExportDeclaration,
        Self::NamedExports,
        Self::NamespaceExport,
        Self::ExportSpecifier,
        Self::MissingDeclaration,
        Self::ExternalModuleReference,
        Self::JsxElement,
        Self::JsxSelfClosingElement,
        Self::JsxOpeningElement,
        Self::JsxClosingElement,
        Self::JsxFragment,
        Self::JsxOpeningFragment,
        Self::JsxClosingFragment,
        Self::JsxAttribute,
        Self::JsxAttributes,
        Self::JsxSpreadAttribute,
        Self::JsxExpression,
        Self::JsxNamespacedName,
        Self::CaseClause,
        Self::DefaultClause,
        Self::HeritageClause,
        Self::CatchClause,
        Self::ImportAttributes,
        Self::ImportAttribute,
        Self::PropertyAssignment,
        Self::ShorthandPropertyAssignment,
        Self::SpreadAssignment,
        Self::EnumMember,
        Self::SourceFile,
        Self::JSDocTypeExpression,
        Self::JSDocNameReference,
        Self::JSDocAllType,
        Self::JSDocNullableType,
        Self::JSDocNonNullableType,
        Self::JSDocOptionalType,
        Self::JSDocVariadicType,
        Self::JSDoc,
        Self::JSDocText,
        Self::JSDocTypeLiteral,
        Self::JSDocSignature,
        Self::JSDocLink,
        Self::JSDocLinkCode,
        Self::JSDocLinkPlain,
        Self::JSDocUnknownTag,
        Self::JSDocAugmentsTag,
        Self::JSDocImplementsTag,
        Self::JSDocDeprecatedTag,
        Self::JSDocPublicTag,
        Self::JSDocPrivateTag,
        Self::JSDocProtectedTag,
        Self::JSDocReadonlyTag,
        Self::JSDocOverrideTag,
        Self::JSDocCallbackTag,
        Self::JSDocOverloadTag,
        Self::JSDocParameterTag,
        Self::JSDocReturnTag,
        Self::JSDocThisTag,
        Self::JSDocTypeTag,
        Self::JSDocTemplateTag,
        Self::JSDocTypedefTag,
        Self::JSDocSeeTag,
        Self::JSDocPropertyTag,
        Self::JSDocThrowsTag,
        Self::JSDocSatisfiesTag,
        Self::JSDocImportTag,
        Self::SyntaxList,
        Self::JSTypeAliasDeclaration,
        Self::JSImportDeclaration,
        Self::NotEmittedStatement,
        Self::PartiallyEmittedExpression,
        Self::SyntheticReferenceExpression,
        Self::NotEmittedTypeElement,
    ];
    pub fn from_u16(value: u16) -> Option<Self> {
        Self::ALL.get(usize::from(value)).copied()
    }
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::EndOfFile => "EndOfFile",
            Self::SingleLineCommentTrivia => "SingleLineCommentTrivia",
            Self::MultiLineCommentTrivia => "MultiLineCommentTrivia",
            Self::NewLineTrivia => "NewLineTrivia",
            Self::WhitespaceTrivia => "WhitespaceTrivia",
            Self::ConflictMarkerTrivia => "ConflictMarkerTrivia",
            Self::NonTextFileMarkerTrivia => "NonTextFileMarkerTrivia",
            Self::NumericLiteral => "NumericLiteral",
            Self::BigIntLiteral => "BigIntLiteral",
            Self::StringLiteral => "StringLiteral",
            Self::JsxText => "JsxText",
            Self::JsxTextAllWhiteSpaces => "JsxTextAllWhiteSpaces",
            Self::RegularExpressionLiteral => "RegularExpressionLiteral",
            Self::NoSubstitutionTemplateLiteral => "NoSubstitutionTemplateLiteral",
            Self::TemplateHead => "TemplateHead",
            Self::TemplateMiddle => "TemplateMiddle",
            Self::TemplateTail => "TemplateTail",
            Self::OpenBraceToken => "OpenBraceToken",
            Self::CloseBraceToken => "CloseBraceToken",
            Self::OpenParenToken => "OpenParenToken",
            Self::CloseParenToken => "CloseParenToken",
            Self::OpenBracketToken => "OpenBracketToken",
            Self::CloseBracketToken => "CloseBracketToken",
            Self::DotToken => "DotToken",
            Self::DotDotDotToken => "DotDotDotToken",
            Self::SemicolonToken => "SemicolonToken",
            Self::CommaToken => "CommaToken",
            Self::QuestionDotToken => "QuestionDotToken",
            Self::LessThanToken => "LessThanToken",
            Self::LessThanSlashToken => "LessThanSlashToken",
            Self::GreaterThanToken => "GreaterThanToken",
            Self::LessThanEqualsToken => "LessThanEqualsToken",
            Self::GreaterThanEqualsToken => "GreaterThanEqualsToken",
            Self::EqualsEqualsToken => "EqualsEqualsToken",
            Self::ExclamationEqualsToken => "ExclamationEqualsToken",
            Self::EqualsEqualsEqualsToken => "EqualsEqualsEqualsToken",
            Self::ExclamationEqualsEqualsToken => "ExclamationEqualsEqualsToken",
            Self::EqualsGreaterThanToken => "EqualsGreaterThanToken",
            Self::PlusToken => "PlusToken",
            Self::MinusToken => "MinusToken",
            Self::AsteriskToken => "AsteriskToken",
            Self::AsteriskAsteriskToken => "AsteriskAsteriskToken",
            Self::SlashToken => "SlashToken",
            Self::PercentToken => "PercentToken",
            Self::PlusPlusToken => "PlusPlusToken",
            Self::MinusMinusToken => "MinusMinusToken",
            Self::LessThanLessThanToken => "LessThanLessThanToken",
            Self::GreaterThanGreaterThanToken => "GreaterThanGreaterThanToken",
            Self::GreaterThanGreaterThanGreaterThanToken => {
                "GreaterThanGreaterThanGreaterThanToken"
            }
            Self::AmpersandToken => "AmpersandToken",
            Self::BarToken => "BarToken",
            Self::CaretToken => "CaretToken",
            Self::ExclamationToken => "ExclamationToken",
            Self::TildeToken => "TildeToken",
            Self::AmpersandAmpersandToken => "AmpersandAmpersandToken",
            Self::BarBarToken => "BarBarToken",
            Self::QuestionToken => "QuestionToken",
            Self::ColonToken => "ColonToken",
            Self::AtToken => "AtToken",
            Self::QuestionQuestionToken => "QuestionQuestionToken",
            Self::BacktickToken => "BacktickToken",
            Self::HashToken => "HashToken",
            Self::EqualsToken => "EqualsToken",
            Self::PlusEqualsToken => "PlusEqualsToken",
            Self::MinusEqualsToken => "MinusEqualsToken",
            Self::AsteriskEqualsToken => "AsteriskEqualsToken",
            Self::AsteriskAsteriskEqualsToken => "AsteriskAsteriskEqualsToken",
            Self::SlashEqualsToken => "SlashEqualsToken",
            Self::PercentEqualsToken => "PercentEqualsToken",
            Self::LessThanLessThanEqualsToken => "LessThanLessThanEqualsToken",
            Self::GreaterThanGreaterThanEqualsToken => "GreaterThanGreaterThanEqualsToken",
            Self::GreaterThanGreaterThanGreaterThanEqualsToken => {
                "GreaterThanGreaterThanGreaterThanEqualsToken"
            }
            Self::AmpersandEqualsToken => "AmpersandEqualsToken",
            Self::BarEqualsToken => "BarEqualsToken",
            Self::BarBarEqualsToken => "BarBarEqualsToken",
            Self::AmpersandAmpersandEqualsToken => "AmpersandAmpersandEqualsToken",
            Self::QuestionQuestionEqualsToken => "QuestionQuestionEqualsToken",
            Self::CaretEqualsToken => "CaretEqualsToken",
            Self::Identifier => "Identifier",
            Self::PrivateIdentifier => "PrivateIdentifier",
            Self::JSDocCommentTextToken => "JSDocCommentTextToken",
            Self::BreakKeyword => "BreakKeyword",
            Self::CaseKeyword => "CaseKeyword",
            Self::CatchKeyword => "CatchKeyword",
            Self::ClassKeyword => "ClassKeyword",
            Self::ConstKeyword => "ConstKeyword",
            Self::ContinueKeyword => "ContinueKeyword",
            Self::DebuggerKeyword => "DebuggerKeyword",
            Self::DefaultKeyword => "DefaultKeyword",
            Self::DeleteKeyword => "DeleteKeyword",
            Self::DoKeyword => "DoKeyword",
            Self::ElseKeyword => "ElseKeyword",
            Self::EnumKeyword => "EnumKeyword",
            Self::ExportKeyword => "ExportKeyword",
            Self::ExtendsKeyword => "ExtendsKeyword",
            Self::FalseKeyword => "FalseKeyword",
            Self::FinallyKeyword => "FinallyKeyword",
            Self::ForKeyword => "ForKeyword",
            Self::FunctionKeyword => "FunctionKeyword",
            Self::IfKeyword => "IfKeyword",
            Self::ImportKeyword => "ImportKeyword",
            Self::InKeyword => "InKeyword",
            Self::InstanceOfKeyword => "InstanceOfKeyword",
            Self::NewKeyword => "NewKeyword",
            Self::NullKeyword => "NullKeyword",
            Self::ReturnKeyword => "ReturnKeyword",
            Self::SuperKeyword => "SuperKeyword",
            Self::SwitchKeyword => "SwitchKeyword",
            Self::ThisKeyword => "ThisKeyword",
            Self::ThrowKeyword => "ThrowKeyword",
            Self::TrueKeyword => "TrueKeyword",
            Self::TryKeyword => "TryKeyword",
            Self::TypeOfKeyword => "TypeOfKeyword",
            Self::VarKeyword => "VarKeyword",
            Self::VoidKeyword => "VoidKeyword",
            Self::WhileKeyword => "WhileKeyword",
            Self::WithKeyword => "WithKeyword",
            Self::ImplementsKeyword => "ImplementsKeyword",
            Self::InterfaceKeyword => "InterfaceKeyword",
            Self::LetKeyword => "LetKeyword",
            Self::PackageKeyword => "PackageKeyword",
            Self::PrivateKeyword => "PrivateKeyword",
            Self::ProtectedKeyword => "ProtectedKeyword",
            Self::PublicKeyword => "PublicKeyword",
            Self::StaticKeyword => "StaticKeyword",
            Self::YieldKeyword => "YieldKeyword",
            Self::AbstractKeyword => "AbstractKeyword",
            Self::AccessorKeyword => "AccessorKeyword",
            Self::AsKeyword => "AsKeyword",
            Self::AssertsKeyword => "AssertsKeyword",
            Self::AssertKeyword => "AssertKeyword",
            Self::AnyKeyword => "AnyKeyword",
            Self::AsyncKeyword => "AsyncKeyword",
            Self::AwaitKeyword => "AwaitKeyword",
            Self::BooleanKeyword => "BooleanKeyword",
            Self::ConstructorKeyword => "ConstructorKeyword",
            Self::DeclareKeyword => "DeclareKeyword",
            Self::GetKeyword => "GetKeyword",
            Self::ImmediateKeyword => "ImmediateKeyword",
            Self::InferKeyword => "InferKeyword",
            Self::IntrinsicKeyword => "IntrinsicKeyword",
            Self::IsKeyword => "IsKeyword",
            Self::KeyOfKeyword => "KeyOfKeyword",
            Self::ModuleKeyword => "ModuleKeyword",
            Self::NamespaceKeyword => "NamespaceKeyword",
            Self::NeverKeyword => "NeverKeyword",
            Self::OutKeyword => "OutKeyword",
            Self::ReadonlyKeyword => "ReadonlyKeyword",
            Self::RequireKeyword => "RequireKeyword",
            Self::NumberKeyword => "NumberKeyword",
            Self::ObjectKeyword => "ObjectKeyword",
            Self::SatisfiesKeyword => "SatisfiesKeyword",
            Self::SetKeyword => "SetKeyword",
            Self::StringKeyword => "StringKeyword",
            Self::SymbolKeyword => "SymbolKeyword",
            Self::TypeKeyword => "TypeKeyword",
            Self::UndefinedKeyword => "UndefinedKeyword",
            Self::UniqueKeyword => "UniqueKeyword",
            Self::UnknownKeyword => "UnknownKeyword",
            Self::UsingKeyword => "UsingKeyword",
            Self::FromKeyword => "FromKeyword",
            Self::GlobalKeyword => "GlobalKeyword",
            Self::BigIntKeyword => "BigIntKeyword",
            Self::OverrideKeyword => "OverrideKeyword",
            Self::OfKeyword => "OfKeyword",
            Self::DeferKeyword => "DeferKeyword",
            Self::QualifiedName => "QualifiedName",
            Self::ComputedPropertyName => "ComputedPropertyName",
            Self::TypeParameter => "TypeParameter",
            Self::Parameter => "Parameter",
            Self::Decorator => "Decorator",
            Self::PropertySignature => "PropertySignature",
            Self::PropertyDeclaration => "PropertyDeclaration",
            Self::MethodSignature => "MethodSignature",
            Self::MethodDeclaration => "MethodDeclaration",
            Self::ClassStaticBlockDeclaration => "ClassStaticBlockDeclaration",
            Self::Constructor => "Constructor",
            Self::GetAccessor => "GetAccessor",
            Self::SetAccessor => "SetAccessor",
            Self::CallSignature => "CallSignature",
            Self::ConstructSignature => "ConstructSignature",
            Self::IndexSignature => "IndexSignature",
            Self::TypePredicate => "TypePredicate",
            Self::TypeReference => "TypeReference",
            Self::FunctionType => "FunctionType",
            Self::ConstructorType => "ConstructorType",
            Self::TypeQuery => "TypeQuery",
            Self::TypeLiteral => "TypeLiteral",
            Self::ArrayType => "ArrayType",
            Self::TupleType => "TupleType",
            Self::OptionalType => "OptionalType",
            Self::RestType => "RestType",
            Self::UnionType => "UnionType",
            Self::IntersectionType => "IntersectionType",
            Self::ConditionalType => "ConditionalType",
            Self::InferType => "InferType",
            Self::ParenthesizedType => "ParenthesizedType",
            Self::ThisType => "ThisType",
            Self::TypeOperator => "TypeOperator",
            Self::IndexedAccessType => "IndexedAccessType",
            Self::MappedType => "MappedType",
            Self::LiteralType => "LiteralType",
            Self::NamedTupleMember => "NamedTupleMember",
            Self::TemplateLiteralType => "TemplateLiteralType",
            Self::TemplateLiteralTypeSpan => "TemplateLiteralTypeSpan",
            Self::ImportType => "ImportType",
            Self::ObjectBindingPattern => "ObjectBindingPattern",
            Self::ArrayBindingPattern => "ArrayBindingPattern",
            Self::BindingElement => "BindingElement",
            Self::ArrayLiteralExpression => "ArrayLiteralExpression",
            Self::ObjectLiteralExpression => "ObjectLiteralExpression",
            Self::PropertyAccessExpression => "PropertyAccessExpression",
            Self::ElementAccessExpression => "ElementAccessExpression",
            Self::CallExpression => "CallExpression",
            Self::NewExpression => "NewExpression",
            Self::TaggedTemplateExpression => "TaggedTemplateExpression",
            Self::TypeAssertionExpression => "TypeAssertionExpression",
            Self::ParenthesizedExpression => "ParenthesizedExpression",
            Self::FunctionExpression => "FunctionExpression",
            Self::ArrowFunction => "ArrowFunction",
            Self::DeleteExpression => "DeleteExpression",
            Self::TypeOfExpression => "TypeOfExpression",
            Self::VoidExpression => "VoidExpression",
            Self::AwaitExpression => "AwaitExpression",
            Self::PrefixUnaryExpression => "PrefixUnaryExpression",
            Self::PostfixUnaryExpression => "PostfixUnaryExpression",
            Self::BinaryExpression => "BinaryExpression",
            Self::ConditionalExpression => "ConditionalExpression",
            Self::TemplateExpression => "TemplateExpression",
            Self::YieldExpression => "YieldExpression",
            Self::SpreadElement => "SpreadElement",
            Self::ClassExpression => "ClassExpression",
            Self::OmittedExpression => "OmittedExpression",
            Self::ExpressionWithTypeArguments => "ExpressionWithTypeArguments",
            Self::AsExpression => "AsExpression",
            Self::NonNullExpression => "NonNullExpression",
            Self::MetaProperty => "MetaProperty",
            Self::SyntheticExpression => "SyntheticExpression",
            Self::SatisfiesExpression => "SatisfiesExpression",
            Self::TemplateSpan => "TemplateSpan",
            Self::SemicolonClassElement => "SemicolonClassElement",
            Self::Block => "Block",
            Self::EmptyStatement => "EmptyStatement",
            Self::VariableStatement => "VariableStatement",
            Self::ExpressionStatement => "ExpressionStatement",
            Self::IfStatement => "IfStatement",
            Self::DoStatement => "DoStatement",
            Self::WhileStatement => "WhileStatement",
            Self::ForStatement => "ForStatement",
            Self::ForInStatement => "ForInStatement",
            Self::ForOfStatement => "ForOfStatement",
            Self::ContinueStatement => "ContinueStatement",
            Self::BreakStatement => "BreakStatement",
            Self::ReturnStatement => "ReturnStatement",
            Self::WithStatement => "WithStatement",
            Self::SwitchStatement => "SwitchStatement",
            Self::LabeledStatement => "LabeledStatement",
            Self::ThrowStatement => "ThrowStatement",
            Self::TryStatement => "TryStatement",
            Self::DebuggerStatement => "DebuggerStatement",
            Self::VariableDeclaration => "VariableDeclaration",
            Self::VariableDeclarationList => "VariableDeclarationList",
            Self::FunctionDeclaration => "FunctionDeclaration",
            Self::ClassDeclaration => "ClassDeclaration",
            Self::InterfaceDeclaration => "InterfaceDeclaration",
            Self::TypeAliasDeclaration => "TypeAliasDeclaration",
            Self::EnumDeclaration => "EnumDeclaration",
            Self::ModuleDeclaration => "ModuleDeclaration",
            Self::ModuleBlock => "ModuleBlock",
            Self::CaseBlock => "CaseBlock",
            Self::NamespaceExportDeclaration => "NamespaceExportDeclaration",
            Self::ImportEqualsDeclaration => "ImportEqualsDeclaration",
            Self::ImportDeclaration => "ImportDeclaration",
            Self::ImportClause => "ImportClause",
            Self::NamespaceImport => "NamespaceImport",
            Self::NamedImports => "NamedImports",
            Self::ImportSpecifier => "ImportSpecifier",
            Self::ExportAssignment => "ExportAssignment",
            Self::ExportDeclaration => "ExportDeclaration",
            Self::NamedExports => "NamedExports",
            Self::NamespaceExport => "NamespaceExport",
            Self::ExportSpecifier => "ExportSpecifier",
            Self::MissingDeclaration => "MissingDeclaration",
            Self::ExternalModuleReference => "ExternalModuleReference",
            Self::JsxElement => "JsxElement",
            Self::JsxSelfClosingElement => "JsxSelfClosingElement",
            Self::JsxOpeningElement => "JsxOpeningElement",
            Self::JsxClosingElement => "JsxClosingElement",
            Self::JsxFragment => "JsxFragment",
            Self::JsxOpeningFragment => "JsxOpeningFragment",
            Self::JsxClosingFragment => "JsxClosingFragment",
            Self::JsxAttribute => "JsxAttribute",
            Self::JsxAttributes => "JsxAttributes",
            Self::JsxSpreadAttribute => "JsxSpreadAttribute",
            Self::JsxExpression => "JsxExpression",
            Self::JsxNamespacedName => "JsxNamespacedName",
            Self::CaseClause => "CaseClause",
            Self::DefaultClause => "DefaultClause",
            Self::HeritageClause => "HeritageClause",
            Self::CatchClause => "CatchClause",
            Self::ImportAttributes => "ImportAttributes",
            Self::ImportAttribute => "ImportAttribute",
            Self::PropertyAssignment => "PropertyAssignment",
            Self::ShorthandPropertyAssignment => "ShorthandPropertyAssignment",
            Self::SpreadAssignment => "SpreadAssignment",
            Self::EnumMember => "EnumMember",
            Self::SourceFile => "SourceFile",
            Self::JSDocTypeExpression => "JSDocTypeExpression",
            Self::JSDocNameReference => "JSDocNameReference",
            Self::JSDocAllType => "JSDocAllType",
            Self::JSDocNullableType => "JSDocNullableType",
            Self::JSDocNonNullableType => "JSDocNonNullableType",
            Self::JSDocOptionalType => "JSDocOptionalType",
            Self::JSDocVariadicType => "JSDocVariadicType",
            Self::JSDoc => "JSDoc",
            Self::JSDocText => "JSDocText",
            Self::JSDocTypeLiteral => "JSDocTypeLiteral",
            Self::JSDocSignature => "JSDocSignature",
            Self::JSDocLink => "JSDocLink",
            Self::JSDocLinkCode => "JSDocLinkCode",
            Self::JSDocLinkPlain => "JSDocLinkPlain",
            Self::JSDocUnknownTag => "JSDocUnknownTag",
            Self::JSDocAugmentsTag => "JSDocAugmentsTag",
            Self::JSDocImplementsTag => "JSDocImplementsTag",
            Self::JSDocDeprecatedTag => "JSDocDeprecatedTag",
            Self::JSDocPublicTag => "JSDocPublicTag",
            Self::JSDocPrivateTag => "JSDocPrivateTag",
            Self::JSDocProtectedTag => "JSDocProtectedTag",
            Self::JSDocReadonlyTag => "JSDocReadonlyTag",
            Self::JSDocOverrideTag => "JSDocOverrideTag",
            Self::JSDocCallbackTag => "JSDocCallbackTag",
            Self::JSDocOverloadTag => "JSDocOverloadTag",
            Self::JSDocParameterTag => "JSDocParameterTag",
            Self::JSDocReturnTag => "JSDocReturnTag",
            Self::JSDocThisTag => "JSDocThisTag",
            Self::JSDocTypeTag => "JSDocTypeTag",
            Self::JSDocTemplateTag => "JSDocTemplateTag",
            Self::JSDocTypedefTag => "JSDocTypedefTag",
            Self::JSDocSeeTag => "JSDocSeeTag",
            Self::JSDocPropertyTag => "JSDocPropertyTag",
            Self::JSDocThrowsTag => "JSDocThrowsTag",
            Self::JSDocSatisfiesTag => "JSDocSatisfiesTag",
            Self::JSDocImportTag => "JSDocImportTag",
            Self::SyntaxList => "SyntaxList",
            Self::JSTypeAliasDeclaration => "JSTypeAliasDeclaration",
            Self::JSImportDeclaration => "JSImportDeclaration",
            Self::NotEmittedStatement => "NotEmittedStatement",
            Self::PartiallyEmittedExpression => "PartiallyEmittedExpression",
            Self::SyntheticReferenceExpression => "SyntheticReferenceExpression",
            Self::NotEmittedTypeElement => "NotEmittedTypeElement",
        }
    }
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstAssignment: Self = Self::EqualsToken;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastAssignment: Self = Self::CaretEqualsToken;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstCompoundAssignment: Self = Self::PlusEqualsToken;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastCompoundAssignment: Self = Self::CaretEqualsToken;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstReservedWord: Self = Self::BreakKeyword;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastReservedWord: Self = Self::WithKeyword;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstKeyword: Self = Self::BreakKeyword;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastKeyword: Self = Self::DeferKeyword;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstFutureReservedWord: Self = Self::ImplementsKeyword;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastFutureReservedWord: Self = Self::YieldKeyword;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstTypeNode: Self = Self::TypePredicate;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastTypeNode: Self = Self::ImportType;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstPunctuation: Self = Self::OpenBraceToken;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastPunctuation: Self = Self::CaretEqualsToken;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstToken: Self = Self::Unknown;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastToken: Self = Self::DeferKeyword;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstLiteralToken: Self = Self::NumericLiteral;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastLiteralToken: Self = Self::NoSubstitutionTemplateLiteral;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstTemplateToken: Self = Self::NoSubstitutionTemplateLiteral;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastTemplateToken: Self = Self::TemplateTail;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstBinaryOperator: Self = Self::LessThanToken;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastBinaryOperator: Self = Self::CaretEqualsToken;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstStatement: Self = Self::VariableStatement;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastStatement: Self = Self::DebuggerStatement;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstNode: Self = Self::QualifiedName;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstJSDocNode: Self = Self::JSDocTypeExpression;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastJSDocNode: Self = Self::JSDocImportTag;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstJSDocTagNode: Self = Self::JSDocUnknownTag;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastJSDocTagNode: Self = Self::JSDocImportTag;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstContextualKeyword: Self = Self::AbstractKeyword;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastContextualKeyword: Self = Self::DeferKeyword;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastUnaryOperator: Self = Self::TildeToken;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const FirstTriviaToken: Self = Self::SingleLineCommentTrivia;
    #[allow(non_upper_case_globals)] // Preserve upstream marker names.
    pub const LastTriviaToken: Self = Self::ConflictMarkerTrivia;
    pub fn is_trivia_kind(self) -> bool {
        matches!(
            self,
            Self::SingleLineCommentTrivia
                | Self::MultiLineCommentTrivia
                | Self::NewLineTrivia
                | Self::WhitespaceTrivia
                | Self::ConflictMarkerTrivia
        )
    }
    pub fn is_literal_kind(self) -> bool {
        matches!(
            self,
            Self::NumericLiteral
                | Self::BigIntLiteral
                | Self::StringLiteral
                | Self::JsxText
                | Self::JsxTextAllWhiteSpaces
                | Self::RegularExpressionLiteral
                | Self::NoSubstitutionTemplateLiteral
        )
    }
    pub fn is_pseudo_literal_kind(self) -> bool {
        matches!(
            self,
            Self::TemplateHead | Self::TemplateMiddle | Self::TemplateTail
        )
    }
    pub fn is_punctuation_kind(self) -> bool {
        matches!(
            self,
            Self::OpenBraceToken
                | Self::CloseBraceToken
                | Self::OpenParenToken
                | Self::CloseParenToken
                | Self::OpenBracketToken
                | Self::CloseBracketToken
                | Self::DotToken
                | Self::DotDotDotToken
                | Self::SemicolonToken
                | Self::CommaToken
                | Self::QuestionDotToken
                | Self::LessThanToken
                | Self::LessThanSlashToken
                | Self::GreaterThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanEqualsToken
                | Self::EqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::EqualsEqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::EqualsGreaterThanToken
                | Self::PlusToken
                | Self::MinusToken
                | Self::AsteriskToken
                | Self::AsteriskAsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusPlusToken
                | Self::MinusMinusToken
                | Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::AmpersandToken
                | Self::BarToken
                | Self::CaretToken
                | Self::ExclamationToken
                | Self::TildeToken
                | Self::AmpersandAmpersandToken
                | Self::BarBarToken
                | Self::QuestionToken
                | Self::ColonToken
                | Self::AtToken
                | Self::QuestionQuestionToken
                | Self::BacktickToken
                | Self::HashToken
                | Self::EqualsToken
                | Self::PlusEqualsToken
                | Self::MinusEqualsToken
                | Self::AsteriskEqualsToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::SlashEqualsToken
                | Self::PercentEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::AmpersandEqualsToken
                | Self::BarEqualsToken
                | Self::BarBarEqualsToken
                | Self::AmpersandAmpersandEqualsToken
                | Self::QuestionQuestionEqualsToken
                | Self::CaretEqualsToken
        )
    }
    pub fn is_keyword_kind(self) -> bool {
        matches!(
            self,
            Self::BreakKeyword
                | Self::CaseKeyword
                | Self::CatchKeyword
                | Self::ClassKeyword
                | Self::ConstKeyword
                | Self::ContinueKeyword
                | Self::DebuggerKeyword
                | Self::DefaultKeyword
                | Self::DeleteKeyword
                | Self::DoKeyword
                | Self::ElseKeyword
                | Self::EnumKeyword
                | Self::ExportKeyword
                | Self::ExtendsKeyword
                | Self::FalseKeyword
                | Self::FinallyKeyword
                | Self::ForKeyword
                | Self::FunctionKeyword
                | Self::IfKeyword
                | Self::ImportKeyword
                | Self::InKeyword
                | Self::InstanceOfKeyword
                | Self::NewKeyword
                | Self::NullKeyword
                | Self::ReturnKeyword
                | Self::SuperKeyword
                | Self::SwitchKeyword
                | Self::ThisKeyword
                | Self::ThrowKeyword
                | Self::TrueKeyword
                | Self::TryKeyword
                | Self::TypeOfKeyword
                | Self::VarKeyword
                | Self::VoidKeyword
                | Self::WhileKeyword
                | Self::WithKeyword
                | Self::ImplementsKeyword
                | Self::InterfaceKeyword
                | Self::LetKeyword
                | Self::PackageKeyword
                | Self::PrivateKeyword
                | Self::ProtectedKeyword
                | Self::PublicKeyword
                | Self::StaticKeyword
                | Self::YieldKeyword
                | Self::AbstractKeyword
                | Self::AccessorKeyword
                | Self::AsKeyword
                | Self::AssertsKeyword
                | Self::AssertKeyword
                | Self::AnyKeyword
                | Self::AsyncKeyword
                | Self::AwaitKeyword
                | Self::BooleanKeyword
                | Self::ConstructorKeyword
                | Self::DeclareKeyword
                | Self::GetKeyword
                | Self::ImmediateKeyword
                | Self::InferKeyword
                | Self::IntrinsicKeyword
                | Self::IsKeyword
                | Self::KeyOfKeyword
                | Self::ModuleKeyword
                | Self::NamespaceKeyword
                | Self::NeverKeyword
                | Self::OutKeyword
                | Self::ReadonlyKeyword
                | Self::RequireKeyword
                | Self::NumberKeyword
                | Self::ObjectKeyword
                | Self::SatisfiesKeyword
                | Self::SetKeyword
                | Self::StringKeyword
                | Self::SymbolKeyword
                | Self::TypeKeyword
                | Self::UndefinedKeyword
                | Self::UniqueKeyword
                | Self::UnknownKeyword
                | Self::UsingKeyword
                | Self::FromKeyword
                | Self::GlobalKeyword
                | Self::BigIntKeyword
                | Self::OverrideKeyword
                | Self::OfKeyword
                | Self::DeferKeyword
        )
    }
    pub fn is_modifier_kind(self) -> bool {
        matches!(
            self,
            Self::AbstractKeyword
                | Self::AccessorKeyword
                | Self::AsyncKeyword
                | Self::ConstKeyword
                | Self::DeclareKeyword
                | Self::DefaultKeyword
                | Self::ExportKeyword
                | Self::InKeyword
                | Self::PrivateKeyword
                | Self::ProtectedKeyword
                | Self::PublicKeyword
                | Self::ReadonlyKeyword
                | Self::OutKeyword
                | Self::OverrideKeyword
                | Self::StaticKeyword
        )
    }
    pub fn is_keyword_type_kind(self) -> bool {
        matches!(
            self,
            Self::AnyKeyword
                | Self::BigIntKeyword
                | Self::BooleanKeyword
                | Self::IntrinsicKeyword
                | Self::NeverKeyword
                | Self::NumberKeyword
                | Self::ObjectKeyword
                | Self::StringKeyword
                | Self::SymbolKeyword
                | Self::UndefinedKeyword
                | Self::UnknownKeyword
                | Self::VoidKeyword
        )
    }
    pub fn is_keyword_expression_kind(self) -> bool {
        matches!(
            self,
            Self::NullKeyword
                | Self::TrueKeyword
                | Self::FalseKeyword
                | Self::ThisKeyword
                | Self::SuperKeyword
                | Self::ImportKeyword
        )
    }
    pub fn is_token_kind(self) -> bool {
        matches!(
            self,
            Self::Unknown
                | Self::EndOfFile
                | Self::SingleLineCommentTrivia
                | Self::MultiLineCommentTrivia
                | Self::NewLineTrivia
                | Self::WhitespaceTrivia
                | Self::ConflictMarkerTrivia
                | Self::NonTextFileMarkerTrivia
                | Self::NumericLiteral
                | Self::BigIntLiteral
                | Self::StringLiteral
                | Self::JsxText
                | Self::JsxTextAllWhiteSpaces
                | Self::RegularExpressionLiteral
                | Self::NoSubstitutionTemplateLiteral
                | Self::TemplateHead
                | Self::TemplateMiddle
                | Self::TemplateTail
                | Self::OpenBraceToken
                | Self::CloseBraceToken
                | Self::OpenParenToken
                | Self::CloseParenToken
                | Self::OpenBracketToken
                | Self::CloseBracketToken
                | Self::DotToken
                | Self::DotDotDotToken
                | Self::SemicolonToken
                | Self::CommaToken
                | Self::QuestionDotToken
                | Self::LessThanToken
                | Self::LessThanSlashToken
                | Self::GreaterThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanEqualsToken
                | Self::EqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::EqualsEqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::EqualsGreaterThanToken
                | Self::PlusToken
                | Self::MinusToken
                | Self::AsteriskToken
                | Self::AsteriskAsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusPlusToken
                | Self::MinusMinusToken
                | Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::AmpersandToken
                | Self::BarToken
                | Self::CaretToken
                | Self::ExclamationToken
                | Self::TildeToken
                | Self::AmpersandAmpersandToken
                | Self::BarBarToken
                | Self::QuestionToken
                | Self::ColonToken
                | Self::AtToken
                | Self::QuestionQuestionToken
                | Self::BacktickToken
                | Self::HashToken
                | Self::EqualsToken
                | Self::PlusEqualsToken
                | Self::MinusEqualsToken
                | Self::AsteriskEqualsToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::SlashEqualsToken
                | Self::PercentEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::AmpersandEqualsToken
                | Self::BarEqualsToken
                | Self::BarBarEqualsToken
                | Self::AmpersandAmpersandEqualsToken
                | Self::QuestionQuestionEqualsToken
                | Self::CaretEqualsToken
                | Self::Identifier
                | Self::PrivateIdentifier
                | Self::JSDocCommentTextToken
                | Self::BreakKeyword
                | Self::CaseKeyword
                | Self::CatchKeyword
                | Self::ClassKeyword
                | Self::ConstKeyword
                | Self::ContinueKeyword
                | Self::DebuggerKeyword
                | Self::DefaultKeyword
                | Self::DeleteKeyword
                | Self::DoKeyword
                | Self::ElseKeyword
                | Self::EnumKeyword
                | Self::ExportKeyword
                | Self::ExtendsKeyword
                | Self::FalseKeyword
                | Self::FinallyKeyword
                | Self::ForKeyword
                | Self::FunctionKeyword
                | Self::IfKeyword
                | Self::ImportKeyword
                | Self::InKeyword
                | Self::InstanceOfKeyword
                | Self::NewKeyword
                | Self::NullKeyword
                | Self::ReturnKeyword
                | Self::SuperKeyword
                | Self::SwitchKeyword
                | Self::ThisKeyword
                | Self::ThrowKeyword
                | Self::TrueKeyword
                | Self::TryKeyword
                | Self::TypeOfKeyword
                | Self::VarKeyword
                | Self::VoidKeyword
                | Self::WhileKeyword
                | Self::WithKeyword
                | Self::ImplementsKeyword
                | Self::InterfaceKeyword
                | Self::LetKeyword
                | Self::PackageKeyword
                | Self::PrivateKeyword
                | Self::ProtectedKeyword
                | Self::PublicKeyword
                | Self::StaticKeyword
                | Self::YieldKeyword
                | Self::AbstractKeyword
                | Self::AccessorKeyword
                | Self::AsKeyword
                | Self::AssertsKeyword
                | Self::AssertKeyword
                | Self::AnyKeyword
                | Self::AsyncKeyword
                | Self::AwaitKeyword
                | Self::BooleanKeyword
                | Self::ConstructorKeyword
                | Self::DeclareKeyword
                | Self::GetKeyword
                | Self::ImmediateKeyword
                | Self::InferKeyword
                | Self::IntrinsicKeyword
                | Self::IsKeyword
                | Self::KeyOfKeyword
                | Self::ModuleKeyword
                | Self::NamespaceKeyword
                | Self::NeverKeyword
                | Self::OutKeyword
                | Self::ReadonlyKeyword
                | Self::RequireKeyword
                | Self::NumberKeyword
                | Self::ObjectKeyword
                | Self::SatisfiesKeyword
                | Self::SetKeyword
                | Self::StringKeyword
                | Self::SymbolKeyword
                | Self::TypeKeyword
                | Self::UndefinedKeyword
                | Self::UniqueKeyword
                | Self::UnknownKeyword
                | Self::UsingKeyword
                | Self::FromKeyword
                | Self::GlobalKeyword
                | Self::BigIntKeyword
                | Self::OverrideKeyword
                | Self::OfKeyword
                | Self::DeferKeyword
        )
    }
    pub fn is_jsx_token_kind(self) -> bool {
        matches!(
            self,
            Self::LessThanSlashToken
                | Self::EndOfFile
                | Self::ConflictMarkerTrivia
                | Self::JsxText
                | Self::JsxTextAllWhiteSpaces
                | Self::OpenBraceToken
                | Self::LessThanToken
        )
    }
    pub fn is_js_doc_node_kind(self) -> bool {
        matches!(
            self,
            Self::JSDocTypeExpression
                | Self::JSDocNameReference
                | Self::JSDocAllType
                | Self::JSDocNullableType
                | Self::JSDocNonNullableType
                | Self::JSDocOptionalType
                | Self::JSDocVariadicType
                | Self::JSDoc
                | Self::JSDocText
                | Self::JSDocTypeLiteral
                | Self::JSDocSignature
                | Self::JSDocLink
                | Self::JSDocLinkCode
                | Self::JSDocLinkPlain
                | Self::JSDocUnknownTag
                | Self::JSDocAugmentsTag
                | Self::JSDocImplementsTag
                | Self::JSDocDeprecatedTag
                | Self::JSDocPublicTag
                | Self::JSDocPrivateTag
                | Self::JSDocProtectedTag
                | Self::JSDocReadonlyTag
                | Self::JSDocOverrideTag
                | Self::JSDocCallbackTag
                | Self::JSDocOverloadTag
                | Self::JSDocParameterTag
                | Self::JSDocReturnTag
                | Self::JSDocThisTag
                | Self::JSDocTypeTag
                | Self::JSDocTemplateTag
                | Self::JSDocTypedefTag
                | Self::JSDocSeeTag
                | Self::JSDocPropertyTag
                | Self::JSDocThrowsTag
                | Self::JSDocSatisfiesTag
                | Self::JSDocImportTag
        )
    }
    pub fn is_import_phase_modifier_kind(self) -> bool {
        matches!(self, Self::TypeKeyword | Self::DeferKeyword)
    }
    pub fn is_postfix_unary_operator(self) -> bool {
        matches!(self, Self::PlusPlusToken | Self::MinusMinusToken)
    }
    pub fn is_prefix_unary_operator(self) -> bool {
        matches!(
            self,
            Self::PlusToken
                | Self::MinusToken
                | Self::TildeToken
                | Self::ExclamationToken
                | Self::PlusPlusToken
                | Self::MinusMinusToken
        )
    }
    pub fn is_assignment_operator(self) -> bool {
        matches!(
            self,
            Self::EqualsToken
                | Self::PlusEqualsToken
                | Self::MinusEqualsToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::AsteriskEqualsToken
                | Self::SlashEqualsToken
                | Self::PercentEqualsToken
                | Self::AmpersandEqualsToken
                | Self::BarEqualsToken
                | Self::CaretEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::BarBarEqualsToken
                | Self::AmpersandAmpersandEqualsToken
                | Self::QuestionQuestionEqualsToken
        )
    }
    pub fn is_binary_operator(self) -> bool {
        matches!(
            self,
            Self::QuestionQuestionToken
                | Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::MinusToken
                | Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::LessThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanToken
                | Self::GreaterThanEqualsToken
                | Self::InstanceOfKeyword
                | Self::InKeyword
                | Self::EqualsEqualsToken
                | Self::EqualsEqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::AmpersandToken
                | Self::BarToken
                | Self::CaretToken
                | Self::AmpersandAmpersandToken
                | Self::BarBarToken
                | Self::EqualsToken
                | Self::PlusEqualsToken
                | Self::MinusEqualsToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::AsteriskEqualsToken
                | Self::SlashEqualsToken
                | Self::PercentEqualsToken
                | Self::AmpersandEqualsToken
                | Self::BarEqualsToken
                | Self::CaretEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::BarBarEqualsToken
                | Self::AmpersandAmpersandEqualsToken
                | Self::QuestionQuestionEqualsToken
                | Self::CommaToken
        )
    }
    pub fn is_exponentiation_operator(self) -> bool {
        matches!(self, Self::AsteriskAsteriskToken)
    }
    pub fn is_multiplicative_operator(self) -> bool {
        matches!(
            self,
            Self::AsteriskToken | Self::SlashToken | Self::PercentToken
        )
    }
    pub fn is_multiplicative_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::SlashToken
                | Self::PercentToken
        )
    }
    pub fn is_additive_operator(self) -> bool {
        matches!(self, Self::PlusToken | Self::MinusToken)
    }
    pub fn is_additive_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::MinusToken
        )
    }
    pub fn is_shift_operator(self) -> bool {
        matches!(
            self,
            Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
        )
    }
    pub fn is_shift_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::MinusToken
                | Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
        )
    }
    pub fn is_relational_operator(self) -> bool {
        matches!(
            self,
            Self::LessThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanToken
                | Self::GreaterThanEqualsToken
                | Self::InstanceOfKeyword
                | Self::InKeyword
        )
    }
    pub fn is_relational_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::MinusToken
                | Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::LessThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanToken
                | Self::GreaterThanEqualsToken
                | Self::InstanceOfKeyword
                | Self::InKeyword
        )
    }
    pub fn is_equality_operator(self) -> bool {
        matches!(
            self,
            Self::EqualsEqualsToken
                | Self::EqualsEqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
        )
    }
    pub fn is_equality_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::MinusToken
                | Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::LessThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanToken
                | Self::GreaterThanEqualsToken
                | Self::InstanceOfKeyword
                | Self::InKeyword
                | Self::EqualsEqualsToken
                | Self::EqualsEqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
        )
    }
    pub fn is_bitwise_operator(self) -> bool {
        matches!(
            self,
            Self::AmpersandToken | Self::BarToken | Self::CaretToken
        )
    }
    pub fn is_bitwise_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::MinusToken
                | Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::LessThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanToken
                | Self::GreaterThanEqualsToken
                | Self::InstanceOfKeyword
                | Self::InKeyword
                | Self::EqualsEqualsToken
                | Self::EqualsEqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::AmpersandToken
                | Self::BarToken
                | Self::CaretToken
        )
    }
    pub fn is_logical_operator(self) -> bool {
        matches!(self, Self::AmpersandAmpersandToken | Self::BarBarToken)
    }
    pub fn is_logical_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::MinusToken
                | Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::LessThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanToken
                | Self::GreaterThanEqualsToken
                | Self::InstanceOfKeyword
                | Self::InKeyword
                | Self::EqualsEqualsToken
                | Self::EqualsEqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::AmpersandToken
                | Self::BarToken
                | Self::CaretToken
                | Self::AmpersandAmpersandToken
                | Self::BarBarToken
        )
    }
    pub fn is_compound_assignment_operator(self) -> bool {
        matches!(
            self,
            Self::PlusEqualsToken
                | Self::MinusEqualsToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::AsteriskEqualsToken
                | Self::SlashEqualsToken
                | Self::PercentEqualsToken
                | Self::AmpersandEqualsToken
                | Self::BarEqualsToken
                | Self::CaretEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::BarBarEqualsToken
                | Self::AmpersandAmpersandEqualsToken
                | Self::QuestionQuestionEqualsToken
        )
    }
    pub fn is_assignment_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::QuestionQuestionToken
                | Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::SlashToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::MinusToken
                | Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::LessThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanToken
                | Self::GreaterThanEqualsToken
                | Self::InstanceOfKeyword
                | Self::InKeyword
                | Self::EqualsEqualsToken
                | Self::EqualsEqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::AmpersandToken
                | Self::BarToken
                | Self::CaretToken
                | Self::AmpersandAmpersandToken
                | Self::BarBarToken
                | Self::EqualsToken
                | Self::PlusEqualsToken
                | Self::MinusEqualsToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::AsteriskEqualsToken
                | Self::SlashEqualsToken
                | Self::PercentEqualsToken
                | Self::AmpersandEqualsToken
                | Self::BarEqualsToken
                | Self::CaretEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::BarBarEqualsToken
                | Self::AmpersandAmpersandEqualsToken
                | Self::QuestionQuestionEqualsToken
        )
    }
    pub fn is_logical_or_coalescing_assignment_operator(self) -> bool {
        matches!(
            self,
            Self::AmpersandAmpersandEqualsToken
                | Self::BarBarEqualsToken
                | Self::QuestionQuestionEqualsToken
        )
    }
}
