// Generated by cargo xtask gen from the pinned SchemaAPI; do not edit.
// Upstream: 1f70213d4922b434345f639b441681e470c7cfc1
// upstream: tsc/internal/ast/ast_generated.go

#[allow(clippy::wildcard_imports)] // Generated methods consume the complete schema API.
use crate::*;

/// Propagation delegates to the owner's pinned caches and exclusion rules.
pub trait SubtreeContext {
    fn propagate_node(&mut self, node: Option<NodeId>) -> u32;
    fn propagate_list(&mut self, list: Option<NodeListId>) -> u32;
    fn propagate_modifiers(&mut self, list: Option<NodeListId>) -> u32;
}
impl QualifiedNameData {
    // upstream: tsc/internal/ast/ast_generated.go:QualifiedName.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.left) | context.propagate_node(self.right)
    }
}
impl ComputedPropertyNameData {
    // upstream: tsc/internal/ast/ast_generated.go:ComputedPropertyName.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
    }
}
impl IfStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:IfStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
            | context.propagate_node(self.then_statement)
            | context.propagate_node(self.else_statement)
    }
}
impl DoStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:DoStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.statement) | context.propagate_node(self.expression)
    }
}
impl WhileStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:WhileStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression) | context.propagate_node(self.statement)
    }
}
impl ForStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:ForStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.initializer)
            | context.propagate_node(self.condition)
            | context.propagate_node(self.incrementor)
            | context.propagate_node(self.statement)
    }
}
impl WithStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:WithStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression) | context.propagate_node(self.statement)
    }
}
impl SwitchStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:SwitchStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression) | context.propagate_node(self.case_block)
    }
}
impl CaseBlockData {
    // upstream: tsc/internal/ast/ast_generated.go:CaseBlock.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_list(self.clauses)
    }
}
impl CaseOrDefaultClauseData {
    // upstream: tsc/internal/ast/ast_generated.go:CaseOrDefaultClause.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression) | context.propagate_list(self.statements)
    }
}
impl ThrowStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:ThrowStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
    }
}
impl TryStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:TryStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.try_block)
            | context.propagate_node(self.catch_clause)
            | context.propagate_node(self.finally_block)
    }
}
impl LabeledStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:LabeledStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.label) | context.propagate_node(self.statement)
    }
}
impl ExpressionStatementData {
    // upstream: tsc/internal/ast/ast_generated.go:ExpressionStatement.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
    }
}
impl BlockData {
    // upstream: tsc/internal/ast/ast_generated.go:Block.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_list(self.statements)
    }
}
impl ModuleBlockData {
    // upstream: tsc/internal/ast/ast_generated.go:ModuleBlock.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_list(self.statements)
    }
}
impl ImportDeclarationData {
    // upstream: tsc/internal/ast/ast_generated.go:ImportDeclaration.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_modifiers(self.modifiers)
            | context.propagate_node(self.import_clause)
            | context.propagate_node(self.module_specifier)
            | context.propagate_node(self.attributes)
    }
}
impl ExternalModuleReferenceData {
    // upstream: tsc/internal/ast/ast_generated.go:ExternalModuleReference.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
    }
}
impl NamespaceImportData {
    // upstream: tsc/internal/ast/ast_generated.go:NamespaceImport.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.name)
    }
}
impl NamedImportsData {
    // upstream: tsc/internal/ast/ast_generated.go:NamedImports.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_list(self.elements)
    }
}
impl NamespaceExportData {
    // upstream: tsc/internal/ast/ast_generated.go:NamespaceExport.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.name)
    }
}
impl NamedExportsData {
    // upstream: tsc/internal/ast/ast_generated.go:NamedExports.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_list(self.elements)
    }
}
impl PrefixUnaryExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:PrefixUnaryExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.operand)
    }
}
impl PostfixUnaryExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:PostfixUnaryExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.operand)
    }
}
impl ConditionalExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:ConditionalExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.condition)
            | context.propagate_node(self.question_token)
            | context.propagate_node(self.when_true)
            | context.propagate_node(self.colon_token)
            | context.propagate_node(self.when_false)
    }
}
impl ElementAccessExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:ElementAccessExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
            | context.propagate_node(self.question_dot_token)
            | context.propagate_node(self.argument_expression)
    }
}
impl TemplateExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:TemplateExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.head) | context.propagate_list(self.template_spans)
    }
}
impl TemplateSpanData {
    // upstream: tsc/internal/ast/ast_generated.go:TemplateSpan.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression) | context.propagate_node(self.literal)
    }
}
impl ParenthesizedExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:ParenthesizedExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
    }
}
impl ArrayLiteralExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:ArrayLiteralExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_list(self.elements)
    }
}
impl ObjectLiteralExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:ObjectLiteralExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_list(self.properties)
    }
}
impl DeleteExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:DeleteExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
    }
}
impl TypeOfExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:TypeOfExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
    }
}
impl VoidExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:VoidExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
    }
}
impl ImportAttributeData {
    // upstream: tsc/internal/ast/ast_generated.go:ImportAttribute.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.name) | context.propagate_node(self.value)
    }
}
impl ImportAttributesData {
    // upstream: tsc/internal/ast/ast_generated.go:ImportAttributes.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_list(self.attributes)
    }
}
impl PartiallyEmittedExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:PartiallyEmittedExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression)
    }
}
impl SyntheticReferenceExpressionData {
    // upstream: tsc/internal/ast/ast_generated.go:SyntheticReferenceExpression.computeSubtreeFacts
    pub fn compute_subtree_facts(&self, context: &mut impl SubtreeContext) -> u32 {
        context.propagate_node(self.expression) | context.propagate_node(self.this_arg)
    }
}
impl NodeData {
    pub fn compute_subtree_facts_generated(
        &self,
        context: &mut impl SubtreeContext,
    ) -> Option<u32> {
        match self {
            Self::QualifiedName(data) => Some(data.compute_subtree_facts(context)),
            Self::ComputedPropertyName(data) => Some(data.compute_subtree_facts(context)),
            Self::IfStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::DoStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::WhileStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::ForStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::WithStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::SwitchStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::CaseBlock(data) => Some(data.compute_subtree_facts(context)),
            Self::CaseOrDefaultClause(data) => Some(data.compute_subtree_facts(context)),
            Self::ThrowStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::TryStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::LabeledStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::ExpressionStatement(data) => Some(data.compute_subtree_facts(context)),
            Self::Block(data) => Some(data.compute_subtree_facts(context)),
            Self::ModuleBlock(data) => Some(data.compute_subtree_facts(context)),
            Self::ImportDeclaration(data) => Some(data.compute_subtree_facts(context)),
            Self::ExternalModuleReference(data) => Some(data.compute_subtree_facts(context)),
            Self::NamespaceImport(data) => Some(data.compute_subtree_facts(context)),
            Self::NamedImports(data) => Some(data.compute_subtree_facts(context)),
            Self::NamespaceExport(data) => Some(data.compute_subtree_facts(context)),
            Self::NamedExports(data) => Some(data.compute_subtree_facts(context)),
            Self::PrefixUnaryExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::PostfixUnaryExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::ConditionalExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::ElementAccessExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::TemplateExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::TemplateSpan(data) => Some(data.compute_subtree_facts(context)),
            Self::ParenthesizedExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::ArrayLiteralExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::ObjectLiteralExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::DeleteExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::TypeOfExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::VoidExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::ImportAttribute(data) => Some(data.compute_subtree_facts(context)),
            Self::ImportAttributes(data) => Some(data.compute_subtree_facts(context)),
            Self::PartiallyEmittedExpression(data) => Some(data.compute_subtree_facts(context)),
            Self::SyntheticReferenceExpression(data) => Some(data.compute_subtree_facts(context)),
            _ => None,
        }
    }
}
impl NodeData {
    pub fn uses_subtree_cache(&self) -> bool {
        matches!(
            self,
            Self::QualifiedName(_)
                | Self::ComputedPropertyName(_)
                | Self::Decorator(_)
                | Self::IfStatement(_)
                | Self::DoStatement(_)
                | Self::WhileStatement(_)
                | Self::ForStatement(_)
                | Self::ForInOrOfStatement(_)
                | Self::ReturnStatement(_)
                | Self::WithStatement(_)
                | Self::SwitchStatement(_)
                | Self::CaseBlock(_)
                | Self::CaseOrDefaultClause(_)
                | Self::ThrowStatement(_)
                | Self::TryStatement(_)
                | Self::CatchClause(_)
                | Self::Block(_)
                | Self::VariableStatement(_)
                | Self::VariableDeclaration(_)
                | Self::VariableDeclarationList(_)
                | Self::BindingPattern(_)
                | Self::ParameterDeclaration(_)
                | Self::BindingElement(_)
                | Self::FunctionDeclaration(_)
                | Self::ClassDeclaration(_)
                | Self::ClassExpression(_)
                | Self::HeritageClause(_)
                | Self::EnumMember(_)
                | Self::EnumDeclaration(_)
                | Self::ModuleBlock(_)
                | Self::ImportDeclaration(_)
                | Self::NamedImports(_)
                | Self::ExportAssignment(_)
                | Self::NamedExports(_)
                | Self::ExportSpecifier(_)
                | Self::ConstructorDeclaration(_)
                | Self::GetAccessorDeclaration(_)
                | Self::SetAccessorDeclaration(_)
                | Self::MethodDeclaration(_)
                | Self::PropertyDeclaration(_)
                | Self::ClassStaticBlockDeclaration(_)
                | Self::BinaryExpression(_)
                | Self::ArrowFunction(_)
                | Self::FunctionExpression(_)
                | Self::ConditionalExpression(_)
                | Self::PropertyAccessExpression(_)
                | Self::ElementAccessExpression(_)
                | Self::CallExpression(_)
                | Self::NewExpression(_)
                | Self::MetaProperty(_)
                | Self::TemplateExpression(_)
                | Self::TaggedTemplateExpression(_)
                | Self::ArrayLiteralExpression(_)
                | Self::ObjectLiteralExpression(_)
                | Self::PropertyAssignment(_)
                | Self::ShorthandPropertyAssignment(_)
                | Self::ExpressionWithTypeArguments(_)
                | Self::ImportAttribute(_)
                | Self::ImportAttributes(_)
                | Self::JsxElement(_)
                | Self::JsxAttributes(_)
                | Self::JsxNamespacedName(_)
                | Self::JsxOpeningElement(_)
                | Self::JsxSelfClosingElement(_)
                | Self::JsxFragment(_)
                | Self::JsxAttribute(_)
                | Self::SourceFile(_)
                | Self::ModuleDeclaration(_)
                | Self::ImportEqualsDeclaration(_)
                | Self::ExportDeclaration(_)
                | Self::ImportClause(_)
                | Self::ImportSpecifier(_)
        )
    }
    pub fn is_type_syntax(&self) -> bool {
        matches!(
            self,
            Self::InterfaceDeclaration(_)
                | Self::TypeAliasDeclaration(_)
                | Self::NamespaceExportDeclaration(_)
                | Self::CallSignatureDeclaration(_)
                | Self::ConstructSignatureDeclaration(_)
                | Self::IndexSignatureDeclaration(_)
                | Self::MethodSignatureDeclaration(_)
                | Self::PropertySignatureDeclaration(_)
                | Self::KeywordTypeNode(_)
                | Self::UnionTypeNode(_)
                | Self::IntersectionTypeNode(_)
                | Self::ConditionalTypeNode(_)
                | Self::TypeOperatorNode(_)
                | Self::InferTypeNode(_)
                | Self::ArrayTypeNode(_)
                | Self::IndexedAccessTypeNode(_)
                | Self::TypeReferenceNode(_)
                | Self::LiteralTypeNode(_)
                | Self::ThisTypeNode(_)
                | Self::TypePredicateNode(_)
                | Self::TypeQueryNode(_)
                | Self::MappedTypeNode(_)
                | Self::TypeLiteralNode(_)
                | Self::TupleTypeNode(_)
                | Self::NamedTupleMember(_)
                | Self::OptionalTypeNode(_)
                | Self::RestTypeNode(_)
                | Self::ParenthesizedTypeNode(_)
                | Self::FunctionTypeNode(_)
                | Self::ConstructorTypeNode(_)
                | Self::TemplateLiteralTypeNode(_)
                | Self::TemplateLiteralTypeSpan(_)
                | Self::JSDocTypeExpression(_)
                | Self::JSDocNonNullableType(_)
                | Self::JSDocNullableType(_)
                | Self::JSDocAllType(_)
                | Self::JSDocVariadicType(_)
                | Self::JSDocOptionalType(_)
                | Self::JSDocSignature(_)
                | Self::JSDocNameReference(_)
                | Self::ImportTypeNode(_)
                | Self::TypeParameterDeclaration(_)
                | Self::JSDocTypeLiteral(_)
        )
    }
}
