#!/usr/bin/env python3
"""Generate crates/ts_jsstring/src/js_case_generated.rs from the pinned Go casing tables.

Reads upstream/tsc/internal/stringutil/js_case_generated.go (itself generated from
Unicode 15.1.0 by upstream's generate-unicode-data.mts) and emits the same three
tables as Rust constants: the special-casing map (sorted by code point for binary
search) and the Cased and Case_Ignorable range tables with Go's stride encoding.
No data is invented here; rerun after a pin bump and commit the result.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "upstream/tsc/internal/stringutil/js_case_generated.go"
DST = ROOT / "crates/ts_jsstring/src/js_case_generated.rs"

ENTRY = re.compile(
    r'^\s*0x([0-9A-Fa-f]+):\s*\{lower: "([^"]*)", upper: "([^"]*)"'
    r'(?:, conditionalLower: "([^"]*)")?, condition: specialCasingCondition(\w+)\},\s*$'
)
RANGE = re.compile(r"^\s*\{0x([0-9A-Fa-f]+), 0x([0-9A-Fa-f]+), (\d+)\},\s*$")


def go_string(literal: str) -> str:
    def repl(m):
        return chr(int(m.group(1) or m.group(2), 16))

    return re.sub(r"\\u([0-9A-Fa-f]{4})|\\U([0-9A-Fa-f]{8})", repl, literal)


def rust_string(s: str) -> str:
    return '"' + "".join(f"\\u{{{ord(c):X}}}" for c in s) + '"'


def main() -> int:
    text = SRC.read_text()
    lines = text.splitlines()
    entries, tables, current = [], {}, None
    for line in lines:
        if line.startswith("var specialCasingMappings = "):
            current = "special"
            continue
        m = re.match(r"^var (unicode\w+Ranges) = &unicode\.RangeTable\{", line)
        if m:
            current = m.group(1)
            tables[current] = []
            continue
        if current == "special":
            m = ENTRY.match(line)
            if m:
                cp, lower, upper, cond_lower, cond = m.groups()
                entries.append((int(cp, 16), go_string(lower), go_string(upper), go_string(cond_lower or ""), cond))
            elif line.startswith("}"):
                current = None
        elif current:
            m = RANGE.match(line)
            if m:
                tables[current].append(tuple(int(x, 16) if i < 2 else int(x) for i, x in enumerate(m.groups())))
            elif line.startswith("}"):
                current = None
    if not entries or set(tables) != {"unicodeCasedRanges", "unicodeCaseIgnorableRanges"}:
        print(f"unexpected table layout in {SRC}", file=sys.stderr)
        return 1
    entries.sort()
    if len({e[0] for e in entries}) != len(entries):
        print("duplicate code points", file=sys.stderr)
        return 1
    conds = {c for *_, c in entries}
    if conds - {"None", "FinalSigma"}:
        print(f"unknown conditions {conds}", file=sys.stderr)
        return 1
    out = [
        "// Generated by scripts/gen-js-case.py from upstream/tsc/internal/stringutil/js_case_generated.go",
        "// (Unicode 15.1.0 tables of the pinned checkout). Do not edit; rerun the script after a pin bump.",
        "//! port: tsc/internal/stringutil/js_case_generated.go",
        "",
        "#[derive(Clone, Copy, PartialEq, Eq, Debug)]",
        "pub(crate) enum Condition {",
        "    None,",
        "    FinalSigma,",
        "}",
        "",
        "pub(crate) struct SpecialCasing {",
        "    pub(crate) code_point: u32,",
        "    pub(crate) lower: &'static str,",
        "    pub(crate) upper: &'static str,",
        "    pub(crate) conditional_lower: &'static str,",
        "    pub(crate) condition: Condition,",
        "}",
        "",
        "/// Sorted by code point; look up with `binary_search_by_key`.",
        "#[rustfmt::skip]",
        "pub(crate) static SPECIAL_CASING: &[SpecialCasing] = &[",
    ]
    for cp, lower, upper, cond_lower, cond in entries:
        out.append(
            f"    SpecialCasing {{ code_point: 0x{cp:X}, lower: {rust_string(lower)}, upper: {rust_string(upper)}, "
            f"conditional_lower: {rust_string(cond_lower)}, condition: Condition::{cond} }},"
        )
    out.append("];")
    for go_name, rust_name in (("unicodeCasedRanges", "CASED_RANGES"), ("unicodeCaseIgnorableRanges", "CASE_IGNORABLE_RANGES")):
        out += ["", f"/// Go `unicode.RangeTable` ranges as `(lo, hi, stride)`, in table order.", "#[rustfmt::skip]", f"pub(crate) static {rust_name}: &[(u32, u32, u32)] = &["]
        out += [f"    (0x{lo:X}, 0x{hi:X}, {stride})," for lo, hi, stride in tables[go_name]]
        out.append("];")
    DST.write_text("\n".join(out) + "\n")
    print(f"{DST}: {len(entries)} special-casing entries, {len(tables['unicodeCasedRanges'])} cased ranges, {len(tables['unicodeCaseIgnorableRanges'])} case-ignorable ranges")
    return 0


if __name__ == "__main__":
    sys.exit(main())
