#!/usr/bin/env python3
"""Generate immutable Rust option metadata from access-only pinned Go declarations."""
import argparse
import hashlib
import json
import shutil
from s04_common import command, strict_json_loads
from s06_build import ROOT, oracle_export


def rust_string(text):
    return json.dumps(text,ensure_ascii=False)


def declaration(row):
    kinds={v:v[0].upper()+v[1:] for v in ['string','number','boolean','object','list','listOrElement','enum']}
    enums=[]
    for item in row['enum'] or []:
        value=item['value']
        val=('EnumValue::String('+rust_string(value)+')') if isinstance(value,str) else f'EnumValue::Number({value})'
        enums.append('('+rust_string(item['key'])+','+val+')')
    properties={
        'name':rust_string(row['name']),'short_name':rust_string(row['short_name']),
        'kind':'OptionKind::'+kinds[row['kind']],
        'enum_values':'&['+','.join(enums)+']',
        'deprecated_keys':'&['+','.join(map(rust_string,row['deprecated'] or []))+']',
        'element':'Some(&'+declaration(row['element'])+')' if row['element'] else 'None',
        'extra_validation':rust_string(row['extra_validation']), 'min_value':str(row['min_value']),
    }
    for field,key in [('is_file_path','is_file_path'),('is_tsconfig_only','is_tsconfig_only'),('is_command_line_only','is_command_line_only'),('allow_config_dir_template','template'),('preserve_falsy','preserve_falsy')]:
        properties[field]=str(row[key]).lower()
    return 'OptionDeclaration {'+','.join(key+':'+value for key,value in properties.items())+'}'


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--write',action='store_true');args=parser.parse_args()
    adapter=ROOT/'tools/s07/options/declarations_test.go'
    with oracle_export() as (checkout,env,pin):
        package=checkout/'tsc/internal/tsoptions'
        hashes={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(package.glob('*.go')) if not p.name.endswith('_test.go')}
        shutil.copyfile(adapter,package/'s07_declarations_test.go')
        output=checkout/'declarations.json';env['S07_DECLARATIONS_OUTPUT']=str(output)
        repo_path=f'-gcflags=github.com/microsoft/TypeScript/tsc/internal/repo=-trimpath={checkout}/s07-unmatched-prefix'
        command(['go','test','-trimpath','-mod=readonly',repo_path,'./internal/tsoptions','-run','^TestS07Declarations$','-count=1'],cwd=checkout/'tsc',env=env)
        data=output.read_bytes();groups=strict_json_loads(data)
    rust='// Generated by scripts/s07_option_declarations.py from '+pin+'. Do not edit.\nuse super::{EnumValue, OptionDeclaration, OptionKind};\n'
    for name,rows in sorted(groups.items()):
        rust+='#[rustfmt::skip]\npub static '+name.upper()+'_OPTIONS: &[OptionDeclaration] = &[\n'+',\n'.join(map(declaration,rows))+'\n];\n'
    manifest={'pin':pin,'source_sha256':hashes,'adapter_sha256':hashlib.sha256(adapter.read_bytes()).hexdigest(),'generator_sha256':hashlib.sha256(__import__('pathlib').Path(__file__).read_bytes()).hexdigest(),'observations_sha256':hashlib.sha256(data).hexdigest(),'counts':{k:len(v) for k,v in groups.items()}}
    artifacts=[(ROOT/'data/s07/option-declarations.json',data),(ROOT/'data/s07/option-declarations-manifest.json',(json.dumps(manifest,sort_keys=True,separators=(',',':'))+'\n').encode()),(ROOT/'crates/ts_tsoptions/src/option_declarations_generated.rs',rust.encode())]
    for path,raw in artifacts:
        if args.write:path.write_bytes(raw)
        elif not path.exists() or path.read_bytes()!=raw:raise ValueError('option metadata changed: '+str(path))
    print(manifest['counts'])


if __name__=='__main__':main()
