//! Type facts used by flow narrowing, from the pinned checker.go.
// Source: tsc/internal/checker/checker.go:TypeFacts
pub type TypeFacts = u32;

pub const NONE: TypeFacts = 0;
pub const TYPEOF_EQ_STRING: TypeFacts = 1 << 0;
pub const TYPEOF_EQ_NUMBER: TypeFacts = 1 << 1;
pub const TYPEOF_EQ_BIG_INT: TypeFacts = 1 << 2;
pub const TYPEOF_EQ_BOOLEAN: TypeFacts = 1 << 3;
pub const TYPEOF_EQ_SYMBOL: TypeFacts = 1 << 4;
pub const TYPEOF_EQ_OBJECT: TypeFacts = 1 << 5;
pub const TYPEOF_EQ_FUNCTION: TypeFacts = 1 << 6;
pub const TYPEOF_EQ_HOST_OBJECT: TypeFacts = 1 << 7;
pub const TYPEOF_NE_STRING: TypeFacts = 1 << 8;
pub const TYPEOF_NE_NUMBER: TypeFacts = 1 << 9;
pub const TYPEOF_NE_BIG_INT: TypeFacts = 1 << 10;
pub const TYPEOF_NE_BOOLEAN: TypeFacts = 1 << 11;
pub const TYPEOF_NE_SYMBOL: TypeFacts = 1 << 12;
pub const TYPEOF_NE_OBJECT: TypeFacts = 1 << 13;
pub const TYPEOF_NE_FUNCTION: TypeFacts = 1 << 14;
pub const TYPEOF_NE_HOST_OBJECT: TypeFacts = 1 << 15;
pub const EQ_UNDEFINED: TypeFacts = 1 << 16;
pub const EQ_NULL: TypeFacts = 1 << 17;
pub const EQ_UNDEFINED_OR_NULL: TypeFacts = 1 << 18;
pub const NE_UNDEFINED: TypeFacts = 1 << 19;
pub const NE_NULL: TypeFacts = 1 << 20;
pub const NE_UNDEFINED_OR_NULL: TypeFacts = 1 << 21;
pub const TRUTHY: TypeFacts = 1 << 22;
pub const FALSY: TypeFacts = 1 << 23;
pub const IS_UNDEFINED: TypeFacts = 1 << 24;
pub const IS_NULL: TypeFacts = 1 << 25;
pub const IS_UNDEFINED_OR_NULL: TypeFacts = IS_UNDEFINED | IS_NULL;
pub const ALL: TypeFacts = (1 << 27) - 1;
pub const BASE_STRING_STRICT_FACTS: TypeFacts = TYPEOF_EQ_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_OBJECT
    | TYPEOF_NE_FUNCTION
    | TYPEOF_NE_HOST_OBJECT
    | NE_UNDEFINED
    | NE_NULL
    | NE_UNDEFINED_OR_NULL;
pub const BASE_STRING_FACTS: TypeFacts =
    BASE_STRING_STRICT_FACTS | EQ_UNDEFINED | EQ_NULL | EQ_UNDEFINED_OR_NULL | FALSY;
pub const STRING_STRICT_FACTS: TypeFacts = BASE_STRING_STRICT_FACTS | TRUTHY | FALSY;
pub const STRING_FACTS: TypeFacts = BASE_STRING_FACTS | TRUTHY;
pub const EMPTY_STRING_STRICT_FACTS: TypeFacts = BASE_STRING_STRICT_FACTS | FALSY;
pub const EMPTY_STRING_FACTS: TypeFacts = BASE_STRING_FACTS;
pub const NON_EMPTY_STRING_STRICT_FACTS: TypeFacts = BASE_STRING_STRICT_FACTS | TRUTHY;
pub const NON_EMPTY_STRING_FACTS: TypeFacts = BASE_STRING_FACTS | TRUTHY;
pub const BASE_NUMBER_STRICT_FACTS: TypeFacts = TYPEOF_EQ_NUMBER
    | TYPEOF_NE_STRING
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_OBJECT
    | TYPEOF_NE_FUNCTION
    | TYPEOF_NE_HOST_OBJECT
    | NE_UNDEFINED
    | NE_NULL
    | NE_UNDEFINED_OR_NULL;
pub const BASE_NUMBER_FACTS: TypeFacts =
    BASE_NUMBER_STRICT_FACTS | EQ_UNDEFINED | EQ_NULL | EQ_UNDEFINED_OR_NULL | FALSY;
pub const NUMBER_STRICT_FACTS: TypeFacts = BASE_NUMBER_STRICT_FACTS | TRUTHY | FALSY;
pub const NUMBER_FACTS: TypeFacts = BASE_NUMBER_FACTS | TRUTHY;
pub const ZERO_NUMBER_STRICT_FACTS: TypeFacts = BASE_NUMBER_STRICT_FACTS | FALSY;
pub const ZERO_NUMBER_FACTS: TypeFacts = BASE_NUMBER_FACTS;
pub const NON_ZERO_NUMBER_STRICT_FACTS: TypeFacts = BASE_NUMBER_STRICT_FACTS | TRUTHY;
pub const NON_ZERO_NUMBER_FACTS: TypeFacts = BASE_NUMBER_FACTS | TRUTHY;
pub const BASE_BIG_INT_STRICT_FACTS: TypeFacts = TYPEOF_EQ_BIG_INT
    | TYPEOF_NE_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_OBJECT
    | TYPEOF_NE_FUNCTION
    | TYPEOF_NE_HOST_OBJECT
    | NE_UNDEFINED
    | NE_NULL
    | NE_UNDEFINED_OR_NULL;
pub const BASE_BIG_INT_FACTS: TypeFacts =
    BASE_BIG_INT_STRICT_FACTS | EQ_UNDEFINED | EQ_NULL | EQ_UNDEFINED_OR_NULL | FALSY;
pub const BIG_INT_STRICT_FACTS: TypeFacts = BASE_BIG_INT_STRICT_FACTS | TRUTHY | FALSY;
pub const BIG_INT_FACTS: TypeFacts = BASE_BIG_INT_FACTS | TRUTHY;
pub const ZERO_BIG_INT_STRICT_FACTS: TypeFacts = BASE_BIG_INT_STRICT_FACTS | FALSY;
pub const ZERO_BIG_INT_FACTS: TypeFacts = BASE_BIG_INT_FACTS;
pub const NON_ZERO_BIG_INT_STRICT_FACTS: TypeFacts = BASE_BIG_INT_STRICT_FACTS | TRUTHY;
pub const NON_ZERO_BIG_INT_FACTS: TypeFacts = BASE_BIG_INT_FACTS | TRUTHY;
pub const BASE_BOOLEAN_STRICT_FACTS: TypeFacts = TYPEOF_EQ_BOOLEAN
    | TYPEOF_NE_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_OBJECT
    | TYPEOF_NE_FUNCTION
    | TYPEOF_NE_HOST_OBJECT
    | NE_UNDEFINED
    | NE_NULL
    | NE_UNDEFINED_OR_NULL;
pub const BASE_BOOLEAN_FACTS: TypeFacts =
    BASE_BOOLEAN_STRICT_FACTS | EQ_UNDEFINED | EQ_NULL | EQ_UNDEFINED_OR_NULL | FALSY;
pub const BOOLEAN_STRICT_FACTS: TypeFacts = BASE_BOOLEAN_STRICT_FACTS | TRUTHY | FALSY;
pub const BOOLEAN_FACTS: TypeFacts = BASE_BOOLEAN_FACTS | TRUTHY;
pub const FALSE_STRICT_FACTS: TypeFacts = BASE_BOOLEAN_STRICT_FACTS | FALSY;
pub const FALSE_FACTS: TypeFacts = BASE_BOOLEAN_FACTS;
pub const TRUE_STRICT_FACTS: TypeFacts = BASE_BOOLEAN_STRICT_FACTS | TRUTHY;
pub const TRUE_FACTS: TypeFacts = BASE_BOOLEAN_FACTS | TRUTHY;
pub const SYMBOL_STRICT_FACTS: TypeFacts = TYPEOF_EQ_SYMBOL
    | TYPEOF_NE_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_OBJECT
    | TYPEOF_NE_FUNCTION
    | TYPEOF_NE_HOST_OBJECT
    | NE_UNDEFINED
    | NE_NULL
    | NE_UNDEFINED_OR_NULL
    | TRUTHY;
pub const SYMBOL_FACTS: TypeFacts =
    SYMBOL_STRICT_FACTS | EQ_UNDEFINED | EQ_NULL | EQ_UNDEFINED_OR_NULL | FALSY;
pub const OBJECT_STRICT_FACTS: TypeFacts = TYPEOF_EQ_OBJECT
    | TYPEOF_EQ_HOST_OBJECT
    | TYPEOF_NE_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_FUNCTION
    | NE_UNDEFINED
    | NE_NULL
    | NE_UNDEFINED_OR_NULL
    | TRUTHY;
pub const OBJECT_FACTS: TypeFacts =
    OBJECT_STRICT_FACTS | EQ_UNDEFINED | EQ_NULL | EQ_UNDEFINED_OR_NULL | FALSY;
pub const FUNCTION_STRICT_FACTS: TypeFacts = TYPEOF_EQ_FUNCTION
    | TYPEOF_EQ_HOST_OBJECT
    | TYPEOF_NE_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_OBJECT
    | NE_UNDEFINED
    | NE_NULL
    | NE_UNDEFINED_OR_NULL
    | TRUTHY;
pub const FUNCTION_FACTS: TypeFacts =
    FUNCTION_STRICT_FACTS | EQ_UNDEFINED | EQ_NULL | EQ_UNDEFINED_OR_NULL | FALSY;
pub const VOID_FACTS: TypeFacts = TYPEOF_NE_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_OBJECT
    | TYPEOF_NE_FUNCTION
    | TYPEOF_NE_HOST_OBJECT
    | EQ_UNDEFINED
    | EQ_UNDEFINED_OR_NULL
    | NE_NULL
    | FALSY;
pub const UNDEFINED_FACTS: TypeFacts = TYPEOF_NE_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_OBJECT
    | TYPEOF_NE_FUNCTION
    | TYPEOF_NE_HOST_OBJECT
    | EQ_UNDEFINED
    | EQ_UNDEFINED_OR_NULL
    | NE_NULL
    | FALSY
    | IS_UNDEFINED;
pub const NULL_FACTS: TypeFacts = TYPEOF_EQ_OBJECT
    | TYPEOF_NE_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_FUNCTION
    | TYPEOF_NE_HOST_OBJECT
    | EQ_NULL
    | EQ_UNDEFINED_OR_NULL
    | NE_UNDEFINED
    | FALSY
    | IS_NULL;
pub const EMPTY_OBJECT_STRICT_FACTS: TypeFacts =
    ALL & !(EQ_UNDEFINED | EQ_NULL | EQ_UNDEFINED_OR_NULL | IS_UNDEFINED_OR_NULL);
pub const EMPTY_OBJECT_FACTS: TypeFacts = ALL & !IS_UNDEFINED_OR_NULL;
pub const UNKNOWN_FACTS: TypeFacts = ALL & !IS_UNDEFINED_OR_NULL;
pub const ALL_TYPEOF_NE: TypeFacts = TYPEOF_NE_STRING
    | TYPEOF_NE_NUMBER
    | TYPEOF_NE_BIG_INT
    | TYPEOF_NE_BOOLEAN
    | TYPEOF_NE_SYMBOL
    | TYPEOF_NE_OBJECT
    | TYPEOF_NE_FUNCTION
    | NE_UNDEFINED;
pub const OR_FACTS_MASK: TypeFacts = TYPEOF_EQ_FUNCTION | TYPEOF_NE_OBJECT;
pub const AND_FACTS_MASK: TypeFacts = ALL & !OR_FACTS_MASK;
