[package]
name = "ts_printer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ts_arena = { version = "0.1.0", path = "../ts_arena" }
ts_ast = { version = "0.1.0", path = "../ts_ast" }
ts_core = { version = "0.1.0", path = "../ts_core" }
ts_jsstring = { version = "0.1.0", path = "../ts_jsstring" }
ts_scanner = { version = "0.1.0", path = "../ts_scanner" }

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
