// Generated by tools/s07/binder/generate_syntax.py; access-only observer.
package ast

type S07SyntaxField struct {
	Name, Kind string
	Value      any
}

func S07SyntaxFields(node *Node) (string, []S07SyntaxField) {
	switch data := node.data.(type) {
	case *Token:
		_ = data
		return "Token", []S07SyntaxField{}
	case *Identifier:
		return "Identifier", []S07SyntaxField{
			{"Text", "text", data.Text},
		}
	case *PrivateIdentifier:
		return "PrivateIdentifier", []S07SyntaxField{
			{"Text", "text", data.Text},
		}
	case *QualifiedName:
		return "QualifiedName", []S07SyntaxField{
			{"Left", "node", data.Left},
			{"Right", "node", data.Right},
		}
	case *ComputedPropertyName:
		return "ComputedPropertyName", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *Decorator:
		return "Decorator", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *EmptyStatement:
		_ = data
		return "EmptyStatement", []S07SyntaxField{}
	case *IfStatement:
		return "IfStatement", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"ThenStatement", "node", data.ThenStatement},
			{"ElseStatement", "node", data.ElseStatement},
		}
	case *DoStatement:
		return "DoStatement", []S07SyntaxField{
			{"Statement", "node", data.Statement},
			{"Expression", "node", data.Expression},
		}
	case *WhileStatement:
		return "WhileStatement", []S07SyntaxField{
			{"Statement", "node", data.Statement},
			{"Expression", "node", data.Expression},
		}
	case *ForStatement:
		return "ForStatement", []S07SyntaxField{
			{"Statement", "node", data.Statement},
			{"Initializer", "node", data.Initializer},
			{"Condition", "node", data.Condition},
			{"Incrementor", "node", data.Incrementor},
		}
	case *ForInOrOfStatement:
		return "ForInOrOfStatement", []S07SyntaxField{
			{"AwaitModifier", "node", data.AwaitModifier},
			{"Initializer", "node", data.Initializer},
			{"Expression", "node", data.Expression},
			{"Statement", "node", data.Statement},
		}
	case *BreakStatement:
		return "BreakStatement", []S07SyntaxField{
			{"Label", "node", data.Label},
		}
	case *ContinueStatement:
		return "ContinueStatement", []S07SyntaxField{
			{"Label", "node", data.Label},
		}
	case *ReturnStatement:
		return "ReturnStatement", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *WithStatement:
		return "WithStatement", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"Statement", "node", data.Statement},
		}
	case *SwitchStatement:
		return "SwitchStatement", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"CaseBlock", "node", data.CaseBlock},
		}
	case *CaseBlock:
		return "CaseBlock", []S07SyntaxField{
			{"Clauses", "list", data.Clauses},
		}
	case *CaseOrDefaultClause:
		return "CaseOrDefaultClause", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"Statements", "list", data.Statements},
		}
	case *ThrowStatement:
		return "ThrowStatement", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *TryStatement:
		return "TryStatement", []S07SyntaxField{
			{"TryBlock", "node", data.TryBlock},
			{"CatchClause", "node", data.CatchClause},
			{"FinallyBlock", "node", data.FinallyBlock},
		}
	case *CatchClause:
		return "CatchClause", []S07SyntaxField{
			{"VariableDeclaration", "node", data.VariableDeclaration},
			{"Block", "node", data.Block},
		}
	case *DebuggerStatement:
		_ = data
		return "DebuggerStatement", []S07SyntaxField{}
	case *LabeledStatement:
		return "LabeledStatement", []S07SyntaxField{
			{"Label", "node", data.Label},
			{"Statement", "node", data.Statement},
		}
	case *ExpressionStatement:
		return "ExpressionStatement", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *Block:
		return "Block", []S07SyntaxField{
			{"Statements", "list", data.Statements},
			{"MultiLine", "bool", data.MultiLine},
		}
	case *VariableStatement:
		return "VariableStatement", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"DeclarationList", "node", data.DeclarationList},
		}
	case *VariableDeclaration:
		return "VariableDeclaration", []S07SyntaxField{
			{"name", "node", data.name},
			{"ExclamationToken", "node", data.ExclamationToken},
			{"Type", "node", data.Type},
			{"Initializer", "node", data.Initializer},
		}
	case *VariableDeclarationList:
		return "VariableDeclarationList", []S07SyntaxField{
			{"Declarations", "list", data.Declarations},
		}
	case *BindingPattern:
		return "BindingPattern", []S07SyntaxField{
			{"Elements", "list", data.Elements},
		}
	case *ParameterDeclaration:
		return "ParameterDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"DotDotDotToken", "node", data.DotDotDotToken},
			{"name", "node", data.name},
			{"QuestionToken", "node", data.QuestionToken},
			{"Type", "node", data.Type},
			{"Initializer", "node", data.Initializer},
		}
	case *BindingElement:
		return "BindingElement", []S07SyntaxField{
			{"DotDotDotToken", "node", data.DotDotDotToken},
			{"PropertyName", "node", data.PropertyName},
			{"name", "node", data.name},
			{"Initializer", "node", data.Initializer},
		}
	case *MissingDeclaration:
		return "MissingDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
		}
	case *FunctionDeclaration:
		return "FunctionDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
			{"AsteriskToken", "node", data.AsteriskToken},
			{"Body", "node", data.Body},
			{"name", "node", data.name},
		}
	case *ClassDeclaration:
		return "ClassDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"TypeParameters", "list", data.TypeParameters},
			{"HeritageClauses", "list", data.HeritageClauses},
			{"Members", "list", data.Members},
		}
	case *ClassExpression:
		return "ClassExpression", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"TypeParameters", "list", data.TypeParameters},
			{"HeritageClauses", "list", data.HeritageClauses},
			{"Members", "list", data.Members},
		}
	case *HeritageClause:
		return "HeritageClause", []S07SyntaxField{
			{"Token", "kind", data.Token},
			{"Types", "list", data.Types},
		}
	case *InterfaceDeclaration:
		return "InterfaceDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"TypeParameters", "list", data.TypeParameters},
			{"HeritageClauses", "list", data.HeritageClauses},
			{"Members", "list", data.Members},
		}
	case *TypeAliasDeclaration:
		return "TypeAliasDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"TypeParameters", "list", data.TypeParameters},
			{"Type", "node", data.Type},
		}
	case *EnumMember:
		return "EnumMember", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"PostfixToken", "node", data.PostfixToken},
			{"Initializer", "node", data.Initializer},
		}
	case *EnumDeclaration:
		return "EnumDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"Members", "list", data.Members},
		}
	case *ModuleBlock:
		return "ModuleBlock", []S07SyntaxField{
			{"Statements", "list", data.Statements},
		}
	case *NotEmittedStatement:
		_ = data
		return "NotEmittedStatement", []S07SyntaxField{}
	case *NotEmittedTypeElement:
		_ = data
		return "NotEmittedTypeElement", []S07SyntaxField{}
	case *ImportDeclaration:
		return "ImportDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"ImportClause", "node", data.ImportClause},
			{"ModuleSpecifier", "node", data.ModuleSpecifier},
			{"Attributes", "node", data.Attributes},
		}
	case *ExternalModuleReference:
		return "ExternalModuleReference", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *NamespaceImport:
		return "NamespaceImport", []S07SyntaxField{
			{"name", "node", data.name},
		}
	case *NamedImports:
		return "NamedImports", []S07SyntaxField{
			{"Elements", "list", data.Elements},
		}
	case *ExportAssignment:
		return "ExportAssignment", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"IsExportEquals", "bool", data.IsExportEquals},
			{"Type", "node", data.Type},
			{"Expression", "node", data.Expression},
		}
	case *NamespaceExportDeclaration:
		return "NamespaceExportDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
		}
	case *NamespaceExport:
		return "NamespaceExport", []S07SyntaxField{
			{"name", "node", data.name},
		}
	case *NamedExports:
		return "NamedExports", []S07SyntaxField{
			{"Elements", "list", data.Elements},
		}
	case *ExportSpecifier:
		return "ExportSpecifier", []S07SyntaxField{
			{"IsTypeOnly", "bool", data.IsTypeOnly},
			{"PropertyName", "node", data.PropertyName},
			{"name", "node", data.name},
		}
	case *CallSignatureDeclaration:
		return "CallSignatureDeclaration", []S07SyntaxField{
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
		}
	case *ConstructSignatureDeclaration:
		return "ConstructSignatureDeclaration", []S07SyntaxField{
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
		}
	case *ConstructorDeclaration:
		return "ConstructorDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
			{"AsteriskToken", "node", data.AsteriskToken},
			{"Body", "node", data.Body},
		}
	case *GetAccessorDeclaration:
		return "GetAccessorDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"PostfixToken", "node", data.PostfixToken},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
			{"AsteriskToken", "node", data.AsteriskToken},
			{"Body", "node", data.Body},
		}
	case *SetAccessorDeclaration:
		return "SetAccessorDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"PostfixToken", "node", data.PostfixToken},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
			{"AsteriskToken", "node", data.AsteriskToken},
			{"Body", "node", data.Body},
		}
	case *IndexSignatureDeclaration:
		return "IndexSignatureDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
		}
	case *MethodSignatureDeclaration:
		return "MethodSignatureDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"PostfixToken", "node", data.PostfixToken},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
		}
	case *MethodDeclaration:
		return "MethodDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"PostfixToken", "node", data.PostfixToken},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
			{"AsteriskToken", "node", data.AsteriskToken},
			{"Body", "node", data.Body},
		}
	case *PropertySignatureDeclaration:
		return "PropertySignatureDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"PostfixToken", "node", data.PostfixToken},
			{"Type", "node", data.Type},
			{"Initializer", "node", data.Initializer},
		}
	case *PropertyDeclaration:
		return "PropertyDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"PostfixToken", "node", data.PostfixToken},
			{"Type", "node", data.Type},
			{"Initializer", "node", data.Initializer},
		}
	case *SemicolonClassElement:
		_ = data
		return "SemicolonClassElement", []S07SyntaxField{}
	case *ClassStaticBlockDeclaration:
		return "ClassStaticBlockDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"Body", "node", data.Body},
		}
	case *OmittedExpression:
		_ = data
		return "OmittedExpression", []S07SyntaxField{}
	case *KeywordExpression:
		_ = data
		return "KeywordExpression", []S07SyntaxField{}
	case *StringLiteral:
		return "StringLiteral", []S07SyntaxField{
			{"Text", "text", data.Text},
			{"TokenFlags", "number", data.TokenFlags},
		}
	case *NumericLiteral:
		return "NumericLiteral", []S07SyntaxField{
			{"Text", "text", data.Text},
			{"TokenFlags", "number", data.TokenFlags},
		}
	case *BigIntLiteral:
		return "BigIntLiteral", []S07SyntaxField{
			{"Text", "text", data.Text},
			{"TokenFlags", "number", data.TokenFlags},
		}
	case *RegularExpressionLiteral:
		return "RegularExpressionLiteral", []S07SyntaxField{
			{"Text", "text", data.Text},
			{"TokenFlags", "number", data.TokenFlags},
		}
	case *NoSubstitutionTemplateLiteral:
		return "NoSubstitutionTemplateLiteral", []S07SyntaxField{
			{"Text", "text", data.Text},
			{"TokenFlags", "number", data.TokenFlags},
			{"RawText", "text", data.RawText},
			{"TemplateFlags", "number", data.TemplateFlags},
		}
	case *BinaryExpression:
		return "BinaryExpression", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"Left", "node", data.Left},
			{"Type", "node", data.Type},
			{"OperatorToken", "node", data.OperatorToken},
			{"Right", "node", data.Right},
		}
	case *PrefixUnaryExpression:
		return "PrefixUnaryExpression", []S07SyntaxField{
			{"Operator", "kind", data.Operator},
			{"Operand", "node", data.Operand},
		}
	case *PostfixUnaryExpression:
		return "PostfixUnaryExpression", []S07SyntaxField{
			{"Operand", "node", data.Operand},
			{"Operator", "kind", data.Operator},
		}
	case *YieldExpression:
		return "YieldExpression", []S07SyntaxField{
			{"AsteriskToken", "node", data.AsteriskToken},
			{"Expression", "node", data.Expression},
		}
	case *ArrowFunction:
		return "ArrowFunction", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
			{"AsteriskToken", "node", data.AsteriskToken},
			{"Body", "node", data.Body},
			{"EqualsGreaterThanToken", "node", data.EqualsGreaterThanToken},
		}
	case *FunctionExpression:
		return "FunctionExpression", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
			{"AsteriskToken", "node", data.AsteriskToken},
			{"Body", "node", data.Body},
			{"name", "node", data.name},
		}
	case *AsExpression:
		return "AsExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"Type", "node", data.Type},
		}
	case *SatisfiesExpression:
		return "SatisfiesExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"Type", "node", data.Type},
		}
	case *ConditionalExpression:
		return "ConditionalExpression", []S07SyntaxField{
			{"Condition", "node", data.Condition},
			{"QuestionToken", "node", data.QuestionToken},
			{"WhenTrue", "node", data.WhenTrue},
			{"ColonToken", "node", data.ColonToken},
			{"WhenFalse", "node", data.WhenFalse},
		}
	case *PropertyAccessExpression:
		return "PropertyAccessExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"QuestionDotToken", "node", data.QuestionDotToken},
			{"name", "node", data.name},
		}
	case *ElementAccessExpression:
		return "ElementAccessExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"QuestionDotToken", "node", data.QuestionDotToken},
			{"ArgumentExpression", "node", data.ArgumentExpression},
		}
	case *CallExpression:
		return "CallExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"QuestionDotToken", "node", data.QuestionDotToken},
			{"TypeArguments", "list", data.TypeArguments},
			{"Arguments", "list", data.Arguments},
		}
	case *NewExpression:
		return "NewExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"TypeArguments", "list", data.TypeArguments},
			{"Arguments", "list", data.Arguments},
		}
	case *MetaProperty:
		return "MetaProperty", []S07SyntaxField{
			{"KeywordToken", "kind", data.KeywordToken},
			{"name", "node", data.name},
		}
	case *NonNullExpression:
		return "NonNullExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *SpreadElement:
		return "SpreadElement", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *TemplateExpression:
		return "TemplateExpression", []S07SyntaxField{
			{"Head", "node", data.Head},
			{"TemplateSpans", "list", data.TemplateSpans},
		}
	case *TemplateSpan:
		return "TemplateSpan", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"Literal", "node", data.Literal},
		}
	case *TaggedTemplateExpression:
		return "TaggedTemplateExpression", []S07SyntaxField{
			{"Tag", "node", data.Tag},
			{"QuestionDotToken", "node", data.QuestionDotToken},
			{"TypeArguments", "list", data.TypeArguments},
			{"Template", "node", data.Template},
		}
	case *ParenthesizedExpression:
		return "ParenthesizedExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *ArrayLiteralExpression:
		return "ArrayLiteralExpression", []S07SyntaxField{
			{"Elements", "list", data.Elements},
			{"MultiLine", "bool", data.MultiLine},
		}
	case *ObjectLiteralExpression:
		return "ObjectLiteralExpression", []S07SyntaxField{
			{"Properties", "list", data.Properties},
			{"MultiLine", "bool", data.MultiLine},
		}
	case *SpreadAssignment:
		return "SpreadAssignment", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *PropertyAssignment:
		return "PropertyAssignment", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"PostfixToken", "node", data.PostfixToken},
			{"Type", "node", data.Type},
			{"Initializer", "node", data.Initializer},
		}
	case *ShorthandPropertyAssignment:
		return "ShorthandPropertyAssignment", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"PostfixToken", "node", data.PostfixToken},
			{"Type", "node", data.Type},
			{"EqualsToken", "node", data.EqualsToken},
			{"ObjectAssignmentInitializer", "node", data.ObjectAssignmentInitializer},
		}
	case *DeleteExpression:
		return "DeleteExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *TypeOfExpression:
		return "TypeOfExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *VoidExpression:
		return "VoidExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *AwaitExpression:
		return "AwaitExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *TypeAssertion:
		return "TypeAssertion", []S07SyntaxField{
			{"Type", "node", data.Type},
			{"Expression", "node", data.Expression},
		}
	case *KeywordTypeNode:
		_ = data
		return "KeywordTypeNode", []S07SyntaxField{}
	case *UnionTypeNode:
		return "UnionTypeNode", []S07SyntaxField{
			{"Types", "list", data.Types},
		}
	case *IntersectionTypeNode:
		return "IntersectionTypeNode", []S07SyntaxField{
			{"Types", "list", data.Types},
		}
	case *ConditionalTypeNode:
		return "ConditionalTypeNode", []S07SyntaxField{
			{"CheckType", "node", data.CheckType},
			{"ExtendsType", "node", data.ExtendsType},
			{"TrueType", "node", data.TrueType},
			{"FalseType", "node", data.FalseType},
		}
	case *TypeOperatorNode:
		return "TypeOperatorNode", []S07SyntaxField{
			{"Operator", "kind", data.Operator},
			{"Type", "node", data.Type},
		}
	case *InferTypeNode:
		return "InferTypeNode", []S07SyntaxField{
			{"TypeParameter", "node", data.TypeParameter},
		}
	case *ArrayTypeNode:
		return "ArrayTypeNode", []S07SyntaxField{
			{"ElementType", "node", data.ElementType},
		}
	case *IndexedAccessTypeNode:
		return "IndexedAccessTypeNode", []S07SyntaxField{
			{"ObjectType", "node", data.ObjectType},
			{"IndexType", "node", data.IndexType},
		}
	case *TypeReferenceNode:
		return "TypeReferenceNode", []S07SyntaxField{
			{"TypeArguments", "list", data.TypeArguments},
			{"TypeName", "node", data.TypeName},
		}
	case *ExpressionWithTypeArguments:
		return "ExpressionWithTypeArguments", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"TypeArguments", "list", data.TypeArguments},
		}
	case *LiteralTypeNode:
		return "LiteralTypeNode", []S07SyntaxField{
			{"Literal", "node", data.Literal},
		}
	case *ThisTypeNode:
		_ = data
		return "ThisTypeNode", []S07SyntaxField{}
	case *TypePredicateNode:
		return "TypePredicateNode", []S07SyntaxField{
			{"AssertsModifier", "node", data.AssertsModifier},
			{"ParameterName", "node", data.ParameterName},
			{"Type", "node", data.Type},
		}
	case *ImportAttribute:
		return "ImportAttribute", []S07SyntaxField{
			{"name", "node", data.name},
			{"Value", "node", data.Value},
		}
	case *ImportAttributes:
		return "ImportAttributes", []S07SyntaxField{
			{"Token", "kind", data.Token},
			{"Attributes", "list", data.Attributes},
			{"MultiLine", "bool", data.MultiLine},
		}
	case *TypeQueryNode:
		return "TypeQueryNode", []S07SyntaxField{
			{"TypeArguments", "list", data.TypeArguments},
			{"ExprName", "node", data.ExprName},
		}
	case *MappedTypeNode:
		return "MappedTypeNode", []S07SyntaxField{
			{"ReadonlyToken", "node", data.ReadonlyToken},
			{"TypeParameter", "node", data.TypeParameter},
			{"NameType", "node", data.NameType},
			{"QuestionToken", "node", data.QuestionToken},
			{"Type", "node", data.Type},
			{"Members", "list", data.Members},
		}
	case *TypeLiteralNode:
		return "TypeLiteralNode", []S07SyntaxField{
			{"Members", "list", data.Members},
		}
	case *TupleTypeNode:
		return "TupleTypeNode", []S07SyntaxField{
			{"Elements", "list", data.Elements},
		}
	case *NamedTupleMember:
		return "NamedTupleMember", []S07SyntaxField{
			{"DotDotDotToken", "node", data.DotDotDotToken},
			{"name", "node", data.name},
			{"QuestionToken", "node", data.QuestionToken},
			{"Type", "node", data.Type},
		}
	case *OptionalTypeNode:
		return "OptionalTypeNode", []S07SyntaxField{
			{"Type", "node", data.Type},
		}
	case *RestTypeNode:
		return "RestTypeNode", []S07SyntaxField{
			{"Type", "node", data.Type},
		}
	case *ParenthesizedTypeNode:
		return "ParenthesizedTypeNode", []S07SyntaxField{
			{"Type", "node", data.Type},
		}
	case *FunctionTypeNode:
		return "FunctionTypeNode", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
		}
	case *ConstructorTypeNode:
		return "ConstructorTypeNode", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
		}
	case *TemplateHead:
		return "TemplateHead", []S07SyntaxField{
			{"Text", "text", data.Text},
			{"TokenFlags", "number", data.TokenFlags},
			{"RawText", "text", data.RawText},
			{"TemplateFlags", "number", data.TemplateFlags},
		}
	case *TemplateMiddle:
		return "TemplateMiddle", []S07SyntaxField{
			{"Text", "text", data.Text},
			{"TokenFlags", "number", data.TokenFlags},
			{"RawText", "text", data.RawText},
			{"TemplateFlags", "number", data.TemplateFlags},
		}
	case *TemplateTail:
		return "TemplateTail", []S07SyntaxField{
			{"Text", "text", data.Text},
			{"TokenFlags", "number", data.TokenFlags},
			{"RawText", "text", data.RawText},
			{"TemplateFlags", "number", data.TemplateFlags},
		}
	case *TemplateLiteralTypeNode:
		return "TemplateLiteralTypeNode", []S07SyntaxField{
			{"Head", "node", data.Head},
			{"TemplateSpans", "list", data.TemplateSpans},
		}
	case *TemplateLiteralTypeSpan:
		return "TemplateLiteralTypeSpan", []S07SyntaxField{
			{"Type", "node", data.Type},
			{"Literal", "node", data.Literal},
		}
	case *SyntheticExpression:
		return "SyntheticExpression", []S07SyntaxField{
			{"Type", "opaque", data.Type},
			{"IsSpread", "bool", data.IsSpread},
			{"TupleNameSource", "node", data.TupleNameSource},
		}
	case *PartiallyEmittedExpression:
		return "PartiallyEmittedExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *JsxElement:
		return "JsxElement", []S07SyntaxField{
			{"OpeningElement", "node", data.OpeningElement},
			{"Children", "list", data.Children},
			{"ClosingElement", "node", data.ClosingElement},
		}
	case *JsxAttributes:
		return "JsxAttributes", []S07SyntaxField{
			{"Properties", "list", data.Properties},
		}
	case *JsxNamespacedName:
		return "JsxNamespacedName", []S07SyntaxField{
			{"Namespace", "node", data.Namespace},
			{"name", "node", data.name},
		}
	case *JsxOpeningElement:
		return "JsxOpeningElement", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"TypeArguments", "list", data.TypeArguments},
			{"Attributes", "node", data.Attributes},
		}
	case *JsxSelfClosingElement:
		return "JsxSelfClosingElement", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"TypeArguments", "list", data.TypeArguments},
			{"Attributes", "node", data.Attributes},
		}
	case *JsxFragment:
		return "JsxFragment", []S07SyntaxField{
			{"OpeningFragment", "node", data.OpeningFragment},
			{"Children", "list", data.Children},
			{"ClosingFragment", "node", data.ClosingFragment},
		}
	case *JsxOpeningFragment:
		_ = data
		return "JsxOpeningFragment", []S07SyntaxField{}
	case *JsxClosingFragment:
		_ = data
		return "JsxClosingFragment", []S07SyntaxField{}
	case *JsxAttribute:
		return "JsxAttribute", []S07SyntaxField{
			{"name", "node", data.name},
			{"Initializer", "node", data.Initializer},
		}
	case *JsxSpreadAttribute:
		return "JsxSpreadAttribute", []S07SyntaxField{
			{"Expression", "node", data.Expression},
		}
	case *JsxClosingElement:
		return "JsxClosingElement", []S07SyntaxField{
			{"TagName", "node", data.TagName},
		}
	case *JsxExpression:
		return "JsxExpression", []S07SyntaxField{
			{"DotDotDotToken", "node", data.DotDotDotToken},
			{"Expression", "node", data.Expression},
		}
	case *JsxText:
		return "JsxText", []S07SyntaxField{
			{"Text", "text", data.Text},
			{"TokenFlags", "number", data.TokenFlags},
			{"ContainsOnlyTriviaWhiteSpaces", "bool", data.ContainsOnlyTriviaWhiteSpaces},
		}
	case *SyntaxList:
		return "SyntaxList", []S07SyntaxField{
			{"Children", "nodes", data.Children},
		}
	case *JSDoc:
		return "JSDoc", []S07SyntaxField{
			{"Comment", "list", data.Comment},
			{"Tags", "list", data.Tags},
		}
	case *JSDocTypeExpression:
		return "JSDocTypeExpression", []S07SyntaxField{
			{"Type", "node", data.Type},
		}
	case *JSDocNonNullableType:
		return "JSDocNonNullableType", []S07SyntaxField{
			{"Type", "node", data.Type},
		}
	case *JSDocNullableType:
		return "JSDocNullableType", []S07SyntaxField{
			{"Type", "node", data.Type},
		}
	case *JSDocAllType:
		_ = data
		return "JSDocAllType", []S07SyntaxField{}
	case *JSDocVariadicType:
		return "JSDocVariadicType", []S07SyntaxField{
			{"Type", "node", data.Type},
		}
	case *JSDocOptionalType:
		return "JSDocOptionalType", []S07SyntaxField{
			{"Type", "node", data.Type},
		}
	case *JSDocTypeTag:
		return "JSDocTypeTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"TypeExpression", "node", data.TypeExpression},
		}
	case *JSDocUnknownTag:
		return "JSDocUnknownTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
		}
	case *JSDocTemplateTag:
		return "JSDocTemplateTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"Constraint", "node", data.Constraint},
			{"TypeParameters", "list", data.TypeParameters},
		}
	case *JSDocReturnTag:
		return "JSDocReturnTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"TypeExpression", "node", data.TypeExpression},
		}
	case *JSDocPublicTag:
		return "JSDocPublicTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
		}
	case *JSDocPrivateTag:
		return "JSDocPrivateTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
		}
	case *JSDocProtectedTag:
		return "JSDocProtectedTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
		}
	case *JSDocReadonlyTag:
		return "JSDocReadonlyTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
		}
	case *JSDocOverrideTag:
		return "JSDocOverrideTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
		}
	case *JSDocDeprecatedTag:
		return "JSDocDeprecatedTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
		}
	case *JSDocSeeTag:
		return "JSDocSeeTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"NameExpression", "node", data.NameExpression},
		}
	case *JSDocImplementsTag:
		return "JSDocImplementsTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"ClassName", "node", data.ClassName},
		}
	case *JSDocAugmentsTag:
		return "JSDocAugmentsTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"ClassName", "node", data.ClassName},
		}
	case *JSDocSatisfiesTag:
		return "JSDocSatisfiesTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"TypeExpression", "node", data.TypeExpression},
		}
	case *JSDocThrowsTag:
		return "JSDocThrowsTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"TypeExpression", "node", data.TypeExpression},
		}
	case *JSDocThisTag:
		return "JSDocThisTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"TypeExpression", "node", data.TypeExpression},
		}
	case *JSDocImportTag:
		return "JSDocImportTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"ImportClause", "node", data.ImportClause},
			{"ModuleSpecifier", "node", data.ModuleSpecifier},
			{"Attributes", "node", data.Attributes},
		}
	case *JSDocCallbackTag:
		return "JSDocCallbackTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"TypeExpression", "node", data.TypeExpression},
			{"name", "node", data.name},
		}
	case *JSDocOverloadTag:
		return "JSDocOverloadTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"TypeExpression", "node", data.TypeExpression},
		}
	case *JSDocTypedefTag:
		return "JSDocTypedefTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"TypeExpression", "node", data.TypeExpression},
			{"name", "node", data.name},
		}
	case *JSDocSignature:
		return "JSDocSignature", []S07SyntaxField{
			{"TypeParameters", "list", data.TypeParameters},
			{"Parameters", "list", data.Parameters},
			{"Type", "node", data.Type},
			{"FullSignature", "node", data.FullSignature},
		}
	case *JSDocNameReference:
		return "JSDocNameReference", []S07SyntaxField{
			{"name", "node", data.name},
		}
	case *SourceFile:
		return "SourceFile", []S07SyntaxField{
			{"Statements", "list", data.Statements},
			{"EndOfFileToken", "node", data.EndOfFileToken},
		}
	case *ModuleDeclaration:
		return "ModuleDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"AsteriskToken", "node", data.AsteriskToken},
			{"Body", "node", data.Body},
			{"Keyword", "kind", data.Keyword},
			{"name", "node", data.name},
			{"Attributes", "node", data.Attributes},
		}
	case *ImportEqualsDeclaration:
		return "ImportEqualsDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"IsTypeOnly", "bool", data.IsTypeOnly},
			{"name", "node", data.name},
			{"ModuleReference", "node", data.ModuleReference},
		}
	case *ExportDeclaration:
		return "ExportDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"IsTypeOnly", "bool", data.IsTypeOnly},
			{"ExportClause", "node", data.ExportClause},
			{"ModuleSpecifier", "node", data.ModuleSpecifier},
			{"Attributes", "node", data.Attributes},
		}
	case *ImportTypeNode:
		return "ImportTypeNode", []S07SyntaxField{
			{"TypeArguments", "list", data.TypeArguments},
			{"IsTypeOf", "bool", data.IsTypeOf},
			{"Argument", "node", data.Argument},
			{"Attributes", "node", data.Attributes},
			{"Qualifier", "node", data.Qualifier},
		}
	case *ImportClause:
		return "ImportClause", []S07SyntaxField{
			{"PhaseModifier", "kind", data.PhaseModifier},
			{"name", "node", data.name},
			{"NamedBindings", "node", data.NamedBindings},
		}
	case *ImportSpecifier:
		return "ImportSpecifier", []S07SyntaxField{
			{"IsTypeOnly", "bool", data.IsTypeOnly},
			{"PropertyName", "node", data.PropertyName},
			{"name", "node", data.name},
		}
	case *JSDocText:
		return "JSDocText", []S07SyntaxField{
			{"text", "strings", data.text},
		}
	case *JSDocLink:
		return "JSDocLink", []S07SyntaxField{
			{"text", "strings", data.text},
			{"name", "node", data.name},
		}
	case *JSDocLinkPlain:
		return "JSDocLinkPlain", []S07SyntaxField{
			{"text", "strings", data.text},
			{"name", "node", data.name},
		}
	case *JSDocLinkCode:
		return "JSDocLinkCode", []S07SyntaxField{
			{"text", "strings", data.text},
			{"name", "node", data.name},
		}
	case *TypeParameterDeclaration:
		return "TypeParameterDeclaration", []S07SyntaxField{
			{"modifiers", "modifiers", data.modifiers},
			{"name", "node", data.name},
			{"Constraint", "node", data.Constraint},
			{"Expression", "node", data.Expression},
			{"DefaultType", "node", data.DefaultType},
		}
	case *SyntheticReferenceExpression:
		return "SyntheticReferenceExpression", []S07SyntaxField{
			{"Expression", "node", data.Expression},
			{"ThisArg", "node", data.ThisArg},
		}
	case *JSDocTypeLiteral:
		return "JSDocTypeLiteral", []S07SyntaxField{
			{"JSDocPropertyTags", "nodes", data.JSDocPropertyTags},
			{"IsArrayType", "bool", data.IsArrayType},
		}
	case *JSDocParameterOrPropertyTag:
		return "JSDocParameterOrPropertyTag", []S07SyntaxField{
			{"TagName", "node", data.TagName},
			{"Comment", "list", data.Comment},
			{"name", "node", data.name},
			{"IsBracketed", "bool", data.IsBracketed},
			{"TypeExpression", "node", data.TypeExpression},
			{"IsNameFirst", "bool", data.IsNameFirst},
		}
	default:
		panic("S07 observer: unsupported syntax payload")
	}
}
