[package]
name = "ts_tsoptions"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
stacker = "=0.1.25"
ts_jsnum = { version = "0.1.0", path = "../ts_jsnum" }
ts_ast = { version = "0.1.0", path = "../ts_ast" }
ts_parser = { version = "0.1.0", path = "../ts_parser" }
ts_scanner = { version = "0.1.0", path = "../ts_scanner" }
ts_vfs = { version = "0.1.0", path = "../ts_vfs" }
ts_core = { version = "0.1.0", path = "../ts_core" }
ts_tspath = { version = "0.1.0", path = "../ts_tspath" }
ts_bundled = { version = "0.1.0", path = "../ts_bundled" }
ts_diagnostics = { version = "0.1.0", path = "../ts_diagnostics" }
ts_jsstring = { version = "0.1.0", path = "../ts_jsstring" }
serde_json = { version = "1", features = ["preserve_order"] }

[lints]
workspace = true
